// Generated by CIRCT firtool-1.149.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Hive_HiveWorker_62_Verification_Assert();	// src/hive/scala/main/HiveWorker.scala:165:9
  `ifndef SYNTHESIS	// src/hive/scala/main/HiveWorker.scala:165:9
    always @(posedge Hive_HiveWorker_62.clock) begin	// src/hive/scala/main/HiveWorker.scala:60:7, :165:9
      if (~Hive_HiveWorker_62.reset & Hive_HiveWorker_62.io_loadVInLock
          & Hive_HiveWorker_62.io_loadWInLock) begin	// src/hive/scala/main/HiveWorker.scala:60:7, :75:14, :165:{9,27}
        if (`ASSERT_VERBOSE_COND_)	// src/hive/scala/main/HiveWorker.scala:165:9
          $error("Assertion failed: HiveWorker: loadVInLock and loadWInLock asserted simultaneously (mutually exclusive load modes)\n");	// src/hive/scala/main/HiveWorker.scala:165:9
        if (`STOP_COND_)	// src/hive/scala/main/HiveWorker.scala:165:9
          $fatal;	// src/hive/scala/main/HiveWorker.scala:165:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

