// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Llc(	// src/llc/scala/main/Llc.scala:15:7
  input          clock,	// src/llc/scala/main/Llc.scala:15:7
                 reset,	// src/llc/scala/main/Llc.scala:15:7
                 io_cpu_aw_valid,	// src/llc/scala/main/Llc.scala:16:14
  output         io_cpu_aw_ready,	// src/llc/scala/main/Llc.scala:16:14
  input  [31:0]  io_cpu_aw_payload_addr,	// src/llc/scala/main/Llc.scala:16:14
  input  [3:0]   io_cpu_aw_payload_id,	// src/llc/scala/main/Llc.scala:16:14
                 io_cpu_aw_payload_region,	// src/llc/scala/main/Llc.scala:16:14
  input  [7:0]   io_cpu_aw_payload_len,	// src/llc/scala/main/Llc.scala:16:14
  input  [2:0]   io_cpu_aw_payload_size,	// src/llc/scala/main/Llc.scala:16:14
  input  [1:0]   io_cpu_aw_payload_burst,	// src/llc/scala/main/Llc.scala:16:14
  input          io_cpu_aw_payload_lock,	// src/llc/scala/main/Llc.scala:16:14
  input  [3:0]   io_cpu_aw_payload_cache,	// src/llc/scala/main/Llc.scala:16:14
                 io_cpu_aw_payload_qos,	// src/llc/scala/main/Llc.scala:16:14
  input  [2:0]   io_cpu_aw_payload_prot,	// src/llc/scala/main/Llc.scala:16:14
  input          io_cpu_w_valid,	// src/llc/scala/main/Llc.scala:16:14
  output         io_cpu_w_ready,	// src/llc/scala/main/Llc.scala:16:14
  input  [255:0] io_cpu_w_payload_data,	// src/llc/scala/main/Llc.scala:16:14
  input  [31:0]  io_cpu_w_payload_strb,	// src/llc/scala/main/Llc.scala:16:14
  input          io_cpu_w_payload_last,	// src/llc/scala/main/Llc.scala:16:14
  output         io_cpu_b_valid,	// src/llc/scala/main/Llc.scala:16:14
  input          io_cpu_b_ready,	// src/llc/scala/main/Llc.scala:16:14
  output [3:0]   io_cpu_b_payload_id,	// src/llc/scala/main/Llc.scala:16:14
  output [1:0]   io_cpu_b_payload_resp,	// src/llc/scala/main/Llc.scala:16:14
  input          io_cpu_ar_valid,	// src/llc/scala/main/Llc.scala:16:14
  output         io_cpu_ar_ready,	// src/llc/scala/main/Llc.scala:16:14
  input  [31:0]  io_cpu_ar_payload_addr,	// src/llc/scala/main/Llc.scala:16:14
  input  [3:0]   io_cpu_ar_payload_id,	// src/llc/scala/main/Llc.scala:16:14
                 io_cpu_ar_payload_region,	// src/llc/scala/main/Llc.scala:16:14
  input  [7:0]   io_cpu_ar_payload_len,	// src/llc/scala/main/Llc.scala:16:14
  input  [2:0]   io_cpu_ar_payload_size,	// src/llc/scala/main/Llc.scala:16:14
  input  [1:0]   io_cpu_ar_payload_burst,	// src/llc/scala/main/Llc.scala:16:14
  input          io_cpu_ar_payload_lock,	// src/llc/scala/main/Llc.scala:16:14
  input  [3:0]   io_cpu_ar_payload_cache,	// src/llc/scala/main/Llc.scala:16:14
                 io_cpu_ar_payload_qos,	// src/llc/scala/main/Llc.scala:16:14
  input  [2:0]   io_cpu_ar_payload_prot,	// src/llc/scala/main/Llc.scala:16:14
  output         io_cpu_r_valid,	// src/llc/scala/main/Llc.scala:16:14
  input          io_cpu_r_ready,	// src/llc/scala/main/Llc.scala:16:14
  output [255:0] io_cpu_r_payload_data,	// src/llc/scala/main/Llc.scala:16:14
  output [3:0]   io_cpu_r_payload_id,	// src/llc/scala/main/Llc.scala:16:14
  output [1:0]   io_cpu_r_payload_resp,	// src/llc/scala/main/Llc.scala:16:14
  output         io_cpu_r_payload_last,	// src/llc/scala/main/Llc.scala:16:14
                 io_mem_aw_valid,	// src/llc/scala/main/Llc.scala:16:14
  input          io_mem_aw_ready,	// src/llc/scala/main/Llc.scala:16:14
  output [31:0]  io_mem_aw_payload_addr,	// src/llc/scala/main/Llc.scala:16:14
  output [3:0]   io_mem_aw_payload_id,	// src/llc/scala/main/Llc.scala:16:14
                 io_mem_aw_payload_region,	// src/llc/scala/main/Llc.scala:16:14
  output [7:0]   io_mem_aw_payload_len,	// src/llc/scala/main/Llc.scala:16:14
  output [2:0]   io_mem_aw_payload_size,	// src/llc/scala/main/Llc.scala:16:14
  output [1:0]   io_mem_aw_payload_burst,	// src/llc/scala/main/Llc.scala:16:14
  output         io_mem_aw_payload_lock,	// src/llc/scala/main/Llc.scala:16:14
  output [3:0]   io_mem_aw_payload_cache,	// src/llc/scala/main/Llc.scala:16:14
                 io_mem_aw_payload_qos,	// src/llc/scala/main/Llc.scala:16:14
  output [2:0]   io_mem_aw_payload_prot,	// src/llc/scala/main/Llc.scala:16:14
  output         io_mem_w_valid,	// src/llc/scala/main/Llc.scala:16:14
  input          io_mem_w_ready,	// src/llc/scala/main/Llc.scala:16:14
  output [255:0] io_mem_w_payload_data,	// src/llc/scala/main/Llc.scala:16:14
  output [31:0]  io_mem_w_payload_strb,	// src/llc/scala/main/Llc.scala:16:14
  output         io_mem_w_payload_last,	// src/llc/scala/main/Llc.scala:16:14
  input          io_mem_b_valid,	// src/llc/scala/main/Llc.scala:16:14
  output         io_mem_b_ready,	// src/llc/scala/main/Llc.scala:16:14
  input  [3:0]   io_mem_b_payload_id,	// src/llc/scala/main/Llc.scala:16:14
  input  [1:0]   io_mem_b_payload_resp,	// src/llc/scala/main/Llc.scala:16:14
  output         io_mem_ar_valid,	// src/llc/scala/main/Llc.scala:16:14
  input          io_mem_ar_ready,	// src/llc/scala/main/Llc.scala:16:14
  output [31:0]  io_mem_ar_payload_addr,	// src/llc/scala/main/Llc.scala:16:14
  output [3:0]   io_mem_ar_payload_id,	// src/llc/scala/main/Llc.scala:16:14
                 io_mem_ar_payload_region,	// src/llc/scala/main/Llc.scala:16:14
  output [7:0]   io_mem_ar_payload_len,	// src/llc/scala/main/Llc.scala:16:14
  output [2:0]   io_mem_ar_payload_size,	// src/llc/scala/main/Llc.scala:16:14
  output [1:0]   io_mem_ar_payload_burst,	// src/llc/scala/main/Llc.scala:16:14
  output         io_mem_ar_payload_lock,	// src/llc/scala/main/Llc.scala:16:14
  output [3:0]   io_mem_ar_payload_cache,	// src/llc/scala/main/Llc.scala:16:14
                 io_mem_ar_payload_qos,	// src/llc/scala/main/Llc.scala:16:14
  output [2:0]   io_mem_ar_payload_prot,	// src/llc/scala/main/Llc.scala:16:14
  input          io_mem_r_valid,	// src/llc/scala/main/Llc.scala:16:14
  output         io_mem_r_ready,	// src/llc/scala/main/Llc.scala:16:14
  input  [255:0] io_mem_r_payload_data,	// src/llc/scala/main/Llc.scala:16:14
  input  [3:0]   io_mem_r_payload_id,	// src/llc/scala/main/Llc.scala:16:14
  input  [1:0]   io_mem_r_payload_resp,	// src/llc/scala/main/Llc.scala:16:14
  input          io_mem_r_payload_last,	// src/llc/scala/main/Llc.scala:16:14
                 io_ctrl_aw_valid,	// src/llc/scala/main/Llc.scala:16:14
  output         io_ctrl_aw_ready,	// src/llc/scala/main/Llc.scala:16:14
  input  [7:0]   io_ctrl_aw_payload_addr,	// src/llc/scala/main/Llc.scala:16:14
  input  [2:0]   io_ctrl_aw_payload_prot,	// src/llc/scala/main/Llc.scala:16:14
  input          io_ctrl_w_valid,	// src/llc/scala/main/Llc.scala:16:14
  output         io_ctrl_w_ready,	// src/llc/scala/main/Llc.scala:16:14
  input  [31:0]  io_ctrl_w_payload_data,	// src/llc/scala/main/Llc.scala:16:14
  input  [3:0]   io_ctrl_w_payload_strb,	// src/llc/scala/main/Llc.scala:16:14
  output         io_ctrl_b_valid,	// src/llc/scala/main/Llc.scala:16:14
  input          io_ctrl_b_ready,	// src/llc/scala/main/Llc.scala:16:14
  output [1:0]   io_ctrl_b_payload_resp,	// src/llc/scala/main/Llc.scala:16:14
  input          io_ctrl_ar_valid,	// src/llc/scala/main/Llc.scala:16:14
  output         io_ctrl_ar_ready,	// src/llc/scala/main/Llc.scala:16:14
  input  [7:0]   io_ctrl_ar_payload_addr,	// src/llc/scala/main/Llc.scala:16:14
  input  [2:0]   io_ctrl_ar_payload_prot,	// src/llc/scala/main/Llc.scala:16:14
  output         io_ctrl_r_valid,	// src/llc/scala/main/Llc.scala:16:14
  input          io_ctrl_r_ready,	// src/llc/scala/main/Llc.scala:16:14
  output [31:0]  io_ctrl_r_payload_data,	// src/llc/scala/main/Llc.scala:16:14
  output [1:0]   io_ctrl_r_payload_resp	// src/llc/scala/main/Llc.scala:16:14
);

  wire         doRead;	// src/utils/bus/regif/AxiLite4BusInterface.scala:62:40
  wire         doWrite;	// src/utils/bus/regif/AxiLite4BusInterface.scala:59:30, :61:38
  wire [63:0]  _perfCounters_io_counters_0;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_1;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_2;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_3;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_4;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_5;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_6;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_7;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_8;	// src/llc/scala/main/Llc.scala:26:28
  wire [63:0]  _perfCounters_io_counters_9;	// src/llc/scala/main/Llc.scala:26:28
  wire         _wmBuf_io_writeIn_ready;	// src/llc/scala/main/Llc.scala:25:24
  wire         _wmBuf_io_pipeOut_valid;	// src/llc/scala/main/Llc.scala:25:24
  wire [31:0]  _wmBuf_io_pipeOut_payload_address;	// src/llc/scala/main/Llc.scala:25:24
  wire [3:0]   _wmBuf_io_pipeOut_payload_id;	// src/llc/scala/main/Llc.scala:25:24
  wire [255:0] _wmBuf_io_pipeOut_payload_writeData;	// src/llc/scala/main/Llc.scala:25:24
  wire [31:0]  _wmBuf_io_pipeOut_payload_writeStrb;	// src/llc/scala/main/Llc.scala:25:24
  wire         _wmBuf_io_pipeOut_payload_beatIdx;	// src/llc/scala/main/Llc.scala:25:24
  wire         _wmBuf_io_bRespOut_valid;	// src/llc/scala/main/Llc.scala:25:24
  wire [3:0]   _wmBuf_io_bRespOut_bits_id;	// src/llc/scala/main/Llc.scala:25:24
  wire [3:0]   _wmBuf_io_bRespOut_bits_count;	// src/llc/scala/main/Llc.scala:25:24
  wire [1:0]   _wmBuf_io_bRespOut_bits_beats;	// src/llc/scala/main/Llc.scala:25:24
  wire         _wmBuf_io_snoop_hit;	// src/llc/scala/main/Llc.scala:25:24
  wire         _wmBuf_io_snoop_flushDone;	// src/llc/scala/main/Llc.scala:25:24
  wire         _wmBuf_io_flushing;	// src/llc/scala/main/Llc.scala:25:24
  wire         _wmBuf_io_mergeEvent;	// src/llc/scala/main/Llc.scala:25:24
  wire         _wbBuffer_io_enqReady;	// src/llc/scala/main/Llc.scala:24:24
  wire         _wbBuffer_io_deq_valid;	// src/llc/scala/main/Llc.scala:24:24
  wire [31:0]  _wbBuffer_io_deq_bits_address;	// src/llc/scala/main/Llc.scala:24:24
  wire [255:0] _wbBuffer_io_deq_bits_data_0;	// src/llc/scala/main/Llc.scala:24:24
  wire [255:0] _wbBuffer_io_deq_bits_data_1;	// src/llc/scala/main/Llc.scala:24:24
  wire         _wbBuffer_io_empty;	// src/llc/scala/main/Llc.scala:24:24
  wire         _wbBuffer_io_full;	// src/llc/scala/main/Llc.scala:24:24
  wire         _pipeline_io_reqIn_ready;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_respOut_valid;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_respOut_payload_isWrite;	// src/llc/scala/main/Llc.scala:23:24
  wire [255:0] _pipeline_io_respOut_payload_data_0;	// src/llc/scala/main/Llc.scala:23:24
  wire [255:0] _pipeline_io_respOut_payload_data_1;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_wbReq_valid;	// src/llc/scala/main/Llc.scala:23:24
  wire [31:0]  _pipeline_io_wbReq_bits_address;	// src/llc/scala/main/Llc.scala:23:24
  wire [255:0] _pipeline_io_wbReq_bits_data_0;	// src/llc/scala/main/Llc.scala:23:24
  wire [255:0] _pipeline_io_wbReq_bits_data_1;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_refillReq_valid;	// src/llc/scala/main/Llc.scala:23:24
  wire [31:0]  _pipeline_io_refillReq_bits_address;	// src/llc/scala/main/Llc.scala:23:24
  wire [3:0]   _pipeline_io_refillReq_bits_id;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_perfEvents_readHit;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_perfEvents_readMiss;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_perfEvents_writeHit;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_perfEvents_writeMiss;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_perfEvents_dirtyEvict;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_perfEvents_cleanEvict;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_perfEvents_mshrFullStall;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_perfEvents_refillComplete;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_flushBusy;	// src/llc/scala/main/Llc.scala:23:24
  wire         _pipeline_io_flushDone;	// src/llc/scala/main/Llc.scala:23:24
  reg  [2:0]   rdState;	// src/llc/scala/main/Llc.scala:42:26
  reg  [31:0]  rdAddr;	// src/llc/scala/main/Llc.scala:43:22
  reg  [3:0]   rdId;	// src/llc/scala/main/Llc.scala:44:22
  reg  [7:0]   rdLen;	// src/llc/scala/main/Llc.scala:45:22
  reg  [255:0] rdData_0;	// src/llc/scala/main/Llc.scala:46:22
  reg  [255:0] rdData_1;	// src/llc/scala/main/Llc.scala:46:22
  reg  [1:0]   rdBeatCnt;	// src/llc/scala/main/Llc.scala:47:26
  reg          rdReqValid;	// src/llc/scala/main/Llc.scala:48:27
  reg  [1:0]   wrState;	// src/llc/scala/main/Llc.scala:53:27
  reg  [31:0]  wrAddr;	// src/llc/scala/main/Llc.scala:54:23
  reg  [3:0]   wrId;	// src/llc/scala/main/Llc.scala:55:23
  reg  [7:0]   wrLen;	// src/llc/scala/main/Llc.scala:56:23
  reg  [255:0] wrBuf_0;	// src/llc/scala/main/Llc.scala:57:23
  reg  [255:0] wrBuf_1;	// src/llc/scala/main/Llc.scala:57:23
  reg  [31:0]  wrStrbBuf_0;	// src/llc/scala/main/Llc.scala:58:23
  reg  [31:0]  wrStrbBuf_1;	// src/llc/scala/main/Llc.scala:58:23
  reg  [1:0]   wrBeatRecv;	// src/llc/scala/main/Llc.scala:59:27
  reg  [1:0]   wrSendIdx;	// src/llc/scala/main/Llc.scala:60:27
  reg          wrAwValid;	// src/llc/scala/main/Llc.scala:61:27
  reg  [3:0]   bFifoId_0;	// src/llc/scala/main/Llc.scala:66:24
  reg  [3:0]   bFifoId_1;	// src/llc/scala/main/Llc.scala:66:24
  reg  [3:0]   bFifoId_2;	// src/llc/scala/main/Llc.scala:66:24
  reg  [3:0]   bFifoId_3;	// src/llc/scala/main/Llc.scala:66:24
  reg  [3:0]   bFifoCount_0;	// src/llc/scala/main/Llc.scala:67:24
  reg  [3:0]   bFifoCount_1;	// src/llc/scala/main/Llc.scala:67:24
  reg  [3:0]   bFifoCount_2;	// src/llc/scala/main/Llc.scala:67:24
  reg  [3:0]   bFifoCount_3;	// src/llc/scala/main/Llc.scala:67:24
  reg  [1:0]   bFifoBeats_0;	// src/llc/scala/main/Llc.scala:68:24
  reg  [1:0]   bFifoBeats_1;	// src/llc/scala/main/Llc.scala:68:24
  reg  [1:0]   bFifoBeats_2;	// src/llc/scala/main/Llc.scala:68:24
  reg  [1:0]   bFifoBeats_3;	// src/llc/scala/main/Llc.scala:68:24
  reg  [1:0]   bFifoHead;	// src/llc/scala/main/Llc.scala:69:28
  reg  [1:0]   bFifoTail;	// src/llc/scala/main/Llc.scala:70:28
  reg  [1:0]   bHeadBeatsRem;	// src/llc/scala/main/Llc.scala:74:30
  reg          bHeadActive;	// src/llc/scala/main/Llc.scala:75:30
  reg  [3:0]   bSending;	// src/llc/scala/main/Llc.scala:78:25
  reg  [3:0]   bSendId;	// src/llc/scala/main/Llc.scala:79:21
  wire         io_cpu_ar_ready_0 = rdState == 3'h0;	// src/llc/scala/main/Llc.scala:42:26, :82:31
  wire         _io_cpu_w_ready_T = wrState == 2'h0;	// src/llc/scala/main/Llc.scala:53:27, :91:31, :114:42
  wire         io_cpu_aw_ready_0 = _io_cpu_w_ready_T & ~wrAwValid;	// src/llc/scala/main/Llc.scala:61:27, :91:{31,44,47}
  wire         _io_cpu_w_ready_T_1 = wrState == 2'h1;	// src/llc/scala/main/Llc.scala:53:27, :100:53
  wire         io_cpu_w_ready_0 =
    (_io_cpu_w_ready_T | _io_cpu_w_ready_T_1) & ~(wrBeatRecv[1]);	// src/llc/scala/main/Llc.scala:59:27, :91:31, :100:{42,53,69}, :101:33
  wire [7:0]   _GEN = {6'h0, wrSendIdx};	// src/llc/scala/main/Llc.scala:15:7, :60:27, :136:36
  wire         wrWmBufReq_last = _GEN == wrLen;	// src/llc/scala/main/Llc.scala:56:23, :136:36
  wire         wmBuf_io_writeIn_valid = wrState == 2'h2 & _GEN <= wrLen;	// src/llc/scala/main/Llc.scala:53:27, :56:23, :136:36, :138:{40,53,67}
  reg          snoopFlushReq;	// src/llc/scala/main/Llc.scala:154:30
  wire         rdWantsPipe = rdReqValid & rdState == 3'h3;	// src/llc/scala/main/Llc.scala:42:26, :48:27, :166:17, :193:{32,44}
  wire         pipeline_io_reqIn_valid = _wmBuf_io_pipeOut_valid | rdWantsPipe;	// src/llc/scala/main/Llc.scala:25:24, :193:32, :201:21, :202:31, :205:27
  wire         io_cpu_r_valid_0 = rdState == 3'h4;	// src/llc/scala/main/Llc.scala:42:26, :157:19, :264:30
  wire         io_cpu_r_payload_last_0 = {6'h0, rdBeatCnt} == rdLen;	// src/llc/scala/main/Llc.scala:15:7, :45:22, :47:26, :268:49
  reg  [1:0]   memRdState;	// src/llc/scala/main/Llc.scala:291:29
  reg  [31:0]  memRdAddr;	// src/llc/scala/main/Llc.scala:292:25
  reg  [3:0]   memRdId;	// src/llc/scala/main/Llc.scala:293:25
  reg          refillReady;	// src/llc/scala/main/Llc.scala:294:29
  wire         io_mem_ar_valid_0 = memRdState == 2'h1;	// src/llc/scala/main/Llc.scala:291:29, :322:34
  wire         io_mem_r_ready_0 = memRdState == 2'h2;	// src/llc/scala/main/Llc.scala:291:29, :336:33
  reg  [1:0]   memWrState;	// src/llc/scala/main/Llc.scala:343:29
  reg  [31:0]  memWrAddr;	// src/llc/scala/main/Llc.scala:344:25
  reg  [255:0] memWrData_0;	// src/llc/scala/main/Llc.scala:345:25
  reg  [255:0] memWrData_1;	// src/llc/scala/main/Llc.scala:345:25
  reg  [1:0]   memWrBeatCnt;	// src/llc/scala/main/Llc.scala:346:29
  wire         _GEN_0 = memWrState == 2'h0;	// src/llc/scala/main/Llc.scala:114:42, :343:29, :351:22
  wire         io_mem_aw_valid_0 = memWrState == 2'h1;	// src/llc/scala/main/Llc.scala:343:29, :385:34
  wire         io_mem_w_valid_0 = memWrState == 2'h2;	// src/llc/scala/main/Llc.scala:343:29, :400:33
  reg  [31:0]  reg_rdata;	// src/utils/bus/regif/AxiLite4BusInterface.scala:24:32
  reg          axiAr_rValid;	// src/utils/Stream/Stream.scala:153:25
  reg  [7:0]   axiAr_rData_addr;	// src/utils/Stream/Stream.scala:154:20
  wire         io_ctrl_ar_ready_0 = ~axiAr_rValid | doRead;	// src/utils/Stream/Stream.scala:153:25, :156:16, :158:{12,21,34}, src/utils/bus/regif/AxiLite4BusInterface.scala:62:40
  reg          axiRValid;	// src/utils/bus/regif/AxiLite4BusInterface.scala:28:26
  reg          axiAw_rValid;	// src/utils/Stream/Stream.scala:153:25
  reg  [7:0]   axiAw_rData_addr;	// src/utils/Stream/Stream.scala:154:20
  wire         io_ctrl_aw_ready_0 = ~axiAw_rValid | doWrite;	// src/utils/Stream/Stream.scala:153:25, :156:16, :158:{12,21,34}, src/utils/bus/regif/AxiLite4BusInterface.scala:59:30, :61:38
  reg          axiW_rValid;	// src/utils/Stream/Stream.scala:153:25
  reg  [31:0]  axiW_rData_data;	// src/utils/Stream/Stream.scala:154:20
  reg  [3:0]   axiW_rData_strb;	// src/utils/Stream/Stream.scala:154:20
  wire         io_ctrl_w_ready_0 = ~axiW_rValid | doWrite;	// src/utils/Stream/Stream.scala:153:25, :156:16, :158:{12,21,34}, src/utils/bus/regif/AxiLite4BusInterface.scala:59:30, :61:38
  reg          axiBValid;	// src/utils/bus/regif/AxiLite4BusInterface.scala:33:26
  assign doWrite = axiAw_rValid & axiW_rValid & (~axiBValid | io_ctrl_b_ready);	// src/utils/Stream/Stream.scala:153:25, src/utils/bus/regif/AxiLite4BusInterface.scala:33:26, :59:30, :61:{38,42,54}
  assign doRead = axiAr_rValid & (~axiRValid | io_ctrl_r_ready);	// src/utils/Stream/Stream.scala:153:25, src/utils/bus/regif/AxiLite4BusInterface.scala:28:26, :62:{40,44,56}
  reg          ctrlEnable;	// src/utils/bus/regif/RegInst.scala:76:16
  reg          ctrlFlush;	// src/utils/bus/regif/RegInst.scala:76:16
  reg          ctrlInvalidate;	// src/utils/bus/regif/RegInst.scala:76:16
  wire         ctrlFlushReq = ctrlFlush | ctrlInvalidate;	// src/llc/scala/main/Llc.scala:435:36, src/utils/bus/regif/RegInst.scala:76:16
  reg          ctrlFlushReqPrev;	// src/llc/scala/main/Llc.scala:436:33
  wire         flushStartPulse =
    ctrlFlushReq & ~ctrlFlushReqPrev & ~_pipeline_io_flushBusy;	// src/llc/scala/main/Llc.scala:23:24, :435:36, :436:33, :437:{39,42,60,63}
  reg          flushDoneSticky;	// src/llc/scala/main/Llc.scala:443:32
  reg  [15:0]  wayPartCfg;	// src/utils/bus/regif/RegInst.scala:76:16
  reg          cntClrPulse;	// src/utils/bus/regif/RegInst.scala:76:16
  always @(posedge clock) begin	// src/llc/scala/main/Llc.scala:15:7
    automatic logic            _GEN_1;	// src/utils/Stream/Stream.scala:43:26
    automatic logic            _GEN_2;	// src/utils/Stream/Stream.scala:43:26
    automatic logic            _GEN_3;	// src/utils/Stream/Stream.scala:43:26
    automatic logic            _GEN_4;	// src/llc/scala/main/Llc.scala:46:22, :218:34, :219:48, :221:17
    automatic logic            _GEN_5;	// src/llc/scala/main/Llc.scala:227:28
    automatic logic            _GEN_6;	// src/llc/scala/main/Llc.scala:75:30, :226:25, :227:37, :229:23
    automatic logic            _GEN_7;	// src/llc/scala/main/Llc.scala:78:25, :218:34, :219:48, :226:25
    automatic logic            _GEN_8;	// src/llc/scala/main/Llc.scala:249:21
    automatic logic [3:0][1:0] _GEN_9;	// src/llc/scala/main/Llc.scala:251:20
    automatic logic [1:0]      _GEN_10;	// src/llc/scala/main/Llc.scala:251:20
    automatic logic            _GEN_11;	// src/llc/scala/main/Llc.scala:251:20
    automatic logic            _GEN_12;	// src/llc/scala/main/Llc.scala:218:34, :249:37, :251:29, :254:17
    automatic logic            _GEN_13;	// src/llc/scala/main/Llc.scala:218:34, :249:37, :251:29, :254:17
    automatic logic            _GEN_14;	// src/llc/scala/main/Llc.scala:298:22
    _GEN_1 = io_cpu_ar_valid & io_cpu_ar_ready_0;	// src/llc/scala/main/Llc.scala:82:31, src/utils/Stream/Stream.scala:43:26
    _GEN_2 = io_cpu_aw_valid & io_cpu_aw_ready_0;	// src/llc/scala/main/Llc.scala:91:44, src/utils/Stream/Stream.scala:43:26
    _GEN_3 = io_cpu_w_valid & io_cpu_w_ready_0;	// src/llc/scala/main/Llc.scala:100:69, src/utils/Stream/Stream.scala:43:26
    _GEN_4 = _pipeline_io_respOut_valid & ~_pipeline_io_respOut_payload_isWrite;	// src/llc/scala/main/Llc.scala:23:24, :46:22, :218:34, :219:{10,48}, :221:17
    _GEN_5 = bHeadBeatsRem == 2'h1;	// src/llc/scala/main/Llc.scala:74:30, :227:28
    _GEN_6 = bHeadActive & _GEN_5;	// src/llc/scala/main/Llc.scala:75:30, :226:25, :227:{28,37}, :229:23
    _GEN_7 = _pipeline_io_respOut_valid & _pipeline_io_respOut_payload_isWrite & _GEN_6;	// src/llc/scala/main/Llc.scala:23:24, :75:30, :78:25, :218:34, :219:48, :226:25, :227:37, :229:23
    _GEN_8 = ~bHeadActive & bFifoHead != bFifoTail;	// src/llc/scala/main/Llc.scala:69:28, :70:28, :71:32, :75:30, :249:{8,21,24}
    _GEN_9 = {{bFifoBeats_3}, {bFifoBeats_2}, {bFifoBeats_1}, {bFifoBeats_0}};	// src/llc/scala/main/Llc.scala:68:24, :251:20
    _GEN_10 = _GEN_9[bFifoHead];	// src/llc/scala/main/Llc.scala:69:28, :251:20
    _GEN_11 = _GEN_10 == 2'h0;	// src/llc/scala/main/Llc.scala:114:42, :251:20
    _GEN_12 = _GEN_8 & _GEN_11;	// src/llc/scala/main/Llc.scala:218:34, :249:{21,37}, :251:{20,29}, :254:17
    _GEN_13 = _GEN_12 | _GEN_7;	// src/llc/scala/main/Llc.scala:78:25, :218:34, :219:48, :226:25, :249:37, :251:29, :254:17
    _GEN_14 = memRdState == 2'h0;	// src/llc/scala/main/Llc.scala:114:42, :291:29, :298:22
    if (reset) begin	// src/llc/scala/main/Llc.scala:15:7
      rdState <= 3'h0;	// src/llc/scala/main/Llc.scala:42:26
      rdBeatCnt <= 2'h0;	// src/llc/scala/main/Llc.scala:47:26, :114:42
      rdReqValid <= 1'h0;	// src/llc/scala/main/Llc.scala:48:27
      wrState <= 2'h0;	// src/llc/scala/main/Llc.scala:53:27, :114:42
      wrBeatRecv <= 2'h0;	// src/llc/scala/main/Llc.scala:59:27, :114:42
      wrSendIdx <= 2'h0;	// src/llc/scala/main/Llc.scala:60:27, :114:42
      wrAwValid <= 1'h0;	// src/llc/scala/main/Llc.scala:61:27
      bFifoHead <= 2'h0;	// src/llc/scala/main/Llc.scala:69:28, :114:42
      bFifoTail <= 2'h0;	// src/llc/scala/main/Llc.scala:70:28, :114:42
      bHeadBeatsRem <= 2'h0;	// src/llc/scala/main/Llc.scala:74:30, :114:42
      bHeadActive <= 1'h0;	// src/llc/scala/main/Llc.scala:75:30
      bSending <= 4'h0;	// src/llc/scala/main/Llc.scala:78:25, :280:31
      snoopFlushReq <= 1'h0;	// src/llc/scala/main/Llc.scala:154:30
      memRdState <= 2'h0;	// src/llc/scala/main/Llc.scala:114:42, :291:29
      refillReady <= 1'h0;	// src/llc/scala/main/Llc.scala:294:29
      memWrState <= 2'h0;	// src/llc/scala/main/Llc.scala:114:42, :343:29
      memWrBeatCnt <= 2'h0;	// src/llc/scala/main/Llc.scala:114:42, :346:29
      reg_rdata <= 32'h0;	// src/utils/bus/regif/AxiLite4BusInterface.scala:24:32
      axiAr_rValid <= 1'h0;	// src/utils/Stream/Stream.scala:153:25
      axiRValid <= 1'h0;	// src/utils/bus/regif/AxiLite4BusInterface.scala:28:26
      axiAw_rValid <= 1'h0;	// src/utils/Stream/Stream.scala:153:25
      axiW_rValid <= 1'h0;	// src/utils/Stream/Stream.scala:153:25
      axiBValid <= 1'h0;	// src/utils/bus/regif/AxiLite4BusInterface.scala:33:26
      ctrlEnable <= 1'h0;	// src/utils/bus/regif/RegInst.scala:76:16
      ctrlFlush <= 1'h0;	// src/utils/bus/regif/RegInst.scala:76:16
      ctrlInvalidate <= 1'h0;	// src/utils/bus/regif/RegInst.scala:76:16
      ctrlFlushReqPrev <= 1'h0;	// src/llc/scala/main/Llc.scala:436:33
      flushDoneSticky <= 1'h0;	// src/llc/scala/main/Llc.scala:443:32
      wayPartCfg <= 16'h0;	// src/utils/bus/regif/RegInst.scala:76:16
      cntClrPulse <= 1'h0;	// src/utils/bus/regif/RegInst.scala:76:16
    end
    else begin	// src/llc/scala/main/Llc.scala:15:7
      automatic logic            _GEN_15;	// src/llc/scala/main/Llc.scala:111:22
      automatic logic            _GEN_16 =
        wmBuf_io_writeIn_valid & _wmBuf_io_writeIn_ready;	// src/llc/scala/main/Llc.scala:25:24, :138:53, src/utils/Stream/Stream.scala:43:26
      automatic logic            _GEN_17 = _GEN_16 & wrWmBufReq_last;	// src/llc/scala/main/Llc.scala:109:19, :136:36, :142:31, :144:31, :146:17, src/utils/Stream/Stream.scala:43:26
      automatic logic            _GEN_18;	// src/llc/scala/main/Llc.scala:157:19
      automatic logic            _GEN_19;	// src/llc/scala/main/Llc.scala:154:30, :157:19, :170:38, :171:23
      automatic logic            _GEN_20 = io_cpu_r_valid_0 & io_cpu_r_ready;	// src/llc/scala/main/Llc.scala:264:30, src/utils/Stream/Stream.scala:43:26
      automatic logic            _GEN_21;	// src/llc/scala/main/Llc.scala:298:22
      automatic logic            _GEN_22;	// src/utils/Stream/Stream.scala:43:26
      automatic logic            _GEN_23;	// src/llc/scala/main/Llc.scala:298:22
      automatic logic            _GEN_24;	// src/utils/Stream/Stream.scala:43:26
      automatic logic [1:0]      wstrb;	// src/utils/bus/regif/AxiLite4BusInterface.scala:40:19
      automatic logic [1:0]      _zeros_T;	// src/utils/bus/regif/BusIfBase.scala:144:38
      automatic logic [3:0][1:0] _GEN_25;	// src/llc/scala/main/Llc.scala:351:22, :353:35, :362:28, :367:27
      _GEN_15 = wrAwValid & {7'h0, wrBeatRecv} == {1'h0, wrLen} + 9'h1;	// src/llc/scala/main/Llc.scala:56:23, :59:27, :61:27, :111:{22,36,47}
      _GEN_18 = rdState == 3'h1;	// src/llc/scala/main/Llc.scala:42:26, :84:13, :157:19
      _GEN_19 = rdState == 3'h2 & _wmBuf_io_snoop_flushDone;	// src/llc/scala/main/Llc.scala:25:24, :42:26, :154:30, :157:19, :162:17, :170:38, :171:23
      _GEN_21 = memRdState == 2'h1;	// src/llc/scala/main/Llc.scala:291:29, :298:22
      _GEN_22 = io_mem_ar_valid_0 & io_mem_ar_ready;	// src/llc/scala/main/Llc.scala:322:34, src/utils/Stream/Stream.scala:43:26
      _GEN_23 = memRdState == 2'h2;	// src/llc/scala/main/Llc.scala:291:29, :298:22
      _GEN_24 = io_mem_w_valid_0 & io_mem_w_ready;	// src/llc/scala/main/Llc.scala:400:33, src/utils/Stream/Stream.scala:43:26
      wstrb = axiAr_rValid ? 2'h3 : axiW_rData_strb[1:0];	// src/utils/Stream/Stream.scala:153:25, :154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:40:19
      _zeros_T = ~wstrb;	// src/utils/bus/regif/AxiLite4BusInterface.scala:40:19, src/utils/bus/regif/BusIfBase.scala:144:38
      if (_GEN_20 & io_cpu_r_payload_last_0)	// src/llc/scala/main/Llc.scala:218:34, :268:49, :271:23, :273:31, :274:17, src/utils/Stream/Stream.scala:43:26
        rdState <= 3'h0;	// src/llc/scala/main/Llc.scala:42:26
      else if (_GEN_4)	// src/llc/scala/main/Llc.scala:46:22, :218:34, :219:48, :221:17
        rdState <= 3'h4;	// src/llc/scala/main/Llc.scala:42:26, :157:19
      else if (_GEN_18)	// src/llc/scala/main/Llc.scala:157:19
        rdState <= {2'h1, ~_wmBuf_io_snoop_hit};	// src/llc/scala/main/Llc.scala:25:24, :42:26, :48:27, :159:32, :162:17, :165:20, :166:17
      else if (_GEN_19)	// src/llc/scala/main/Llc.scala:154:30, :157:19, :170:38, :171:23
        rdState <= 3'h3;	// src/llc/scala/main/Llc.scala:42:26, :166:17
      else if (_GEN_1)	// src/utils/Stream/Stream.scala:43:26
        rdState <= 3'h1;	// src/llc/scala/main/Llc.scala:42:26, :84:13
      if (_GEN_20)	// src/utils/Stream/Stream.scala:43:26
        rdBeatCnt <= io_cpu_r_payload_last_0 ? 2'h0 : rdBeatCnt + 2'h1;	// src/llc/scala/main/Llc.scala:47:26, :114:42, :268:49, :272:{15,28}, :273:31, :275:17
      else if (_GEN_4)	// src/llc/scala/main/Llc.scala:46:22, :218:34, :219:48, :221:17
        rdBeatCnt <= 2'h0;	// src/llc/scala/main/Llc.scala:47:26, :114:42
      rdReqValid <=
        ~(pipeline_io_reqIn_valid & _pipeline_io_reqIn_ready & rdWantsPipe
          & ~_wmBuf_io_pipeOut_valid)
        & (_GEN_18 ? ~_wmBuf_io_snoop_hit | rdReqValid : _GEN_19 | rdReqValid);	// src/llc/scala/main/Llc.scala:23:24, :25:24, :48:27, :154:30, :157:19, :159:32, :165:20, :170:38, :171:23, :172:20, :193:32, :201:21, :202:31, :205:27, :211:{31,46,49,63}, :212:16, src/utils/Stream/Stream.scala:43:26
      if (_GEN_17) begin	// src/llc/scala/main/Llc.scala:109:19, :142:31, :144:31, :146:17
        wrState <= 2'h0;	// src/llc/scala/main/Llc.scala:53:27, :114:42
        wrBeatRecv <= 2'h0;	// src/llc/scala/main/Llc.scala:59:27, :114:42
      end
      else begin	// src/llc/scala/main/Llc.scala:109:19, :142:31, :144:31, :146:17
        if (_io_cpu_w_ready_T) begin	// src/llc/scala/main/Llc.scala:91:31
          if (_GEN_15)	// src/llc/scala/main/Llc.scala:111:22
            wrState <= 2'h2;	// src/llc/scala/main/Llc.scala:53:27
          else if (wrAwValid | (|wrBeatRecv))	// src/llc/scala/main/Llc.scala:59:27, :61:27, :114:{28,42}
            wrState <= 2'h1;	// src/llc/scala/main/Llc.scala:53:27
        end
        else if (_io_cpu_w_ready_T_1 & _GEN_15)	// src/llc/scala/main/Llc.scala:53:27, :100:53, :109:19, :111:22, :119:56, :120:19
          wrState <= 2'h2;	// src/llc/scala/main/Llc.scala:53:27
        if (_GEN_3)	// src/utils/Stream/Stream.scala:43:26
          wrBeatRecv <= wrBeatRecv + 2'h1;	// src/llc/scala/main/Llc.scala:59:27, :105:30
      end
      if (_GEN_16)	// src/utils/Stream/Stream.scala:43:26
        wrSendIdx <= wrSendIdx + 2'h1;	// src/llc/scala/main/Llc.scala:60:27, :143:28
      else if ((_io_cpu_w_ready_T | _io_cpu_w_ready_T_1) & _GEN_15)	// src/llc/scala/main/Llc.scala:60:27, :91:31, :100:53, :109:19, :111:{22,56}, :113:19, :119:56, :121:19
        wrSendIdx <= 2'h0;	// src/llc/scala/main/Llc.scala:60:27, :114:42
      wrAwValid <= ~_GEN_17 & (_GEN_2 | wrAwValid);	// src/llc/scala/main/Llc.scala:61:27, :92:24, :93:15, :109:19, :142:31, :144:31, :146:17, :147:17, src/utils/Stream/Stream.scala:43:26
      if (_GEN_12)	// src/llc/scala/main/Llc.scala:218:34, :249:37, :251:29, :254:17
        bFifoHead <= bFifoHead + 2'h1;	// src/llc/scala/main/Llc.scala:69:28, :256:30
      else if (_GEN_7)	// src/llc/scala/main/Llc.scala:69:28, :78:25, :218:34, :219:48, :226:25
        bFifoHead <= bFifoHead + 2'h1;	// src/llc/scala/main/Llc.scala:69:28, :232:36
      if (_wmBuf_io_bRespOut_valid)	// src/llc/scala/main/Llc.scala:25:24
        bFifoTail <= bFifoTail + 2'h1;	// src/llc/scala/main/Llc.scala:70:28, :245:28
      if (~_GEN_8 | _GEN_11) begin	// src/llc/scala/main/Llc.scala:218:34, :249:{21,37}, :251:{20,29}
        if (~_pipeline_io_respOut_valid | ~_pipeline_io_respOut_payload_isWrite
            | ~bHeadActive | _GEN_5) begin	// src/llc/scala/main/Llc.scala:23:24, :74:30, :75:30, :218:34, :219:48, :226:25, :227:{28,37}
        end
        else	// src/llc/scala/main/Llc.scala:74:30, :218:34, :219:48, :226:25, :227:37
          bHeadBeatsRem <= bHeadBeatsRem - 2'h1;	// src/llc/scala/main/Llc.scala:74:30, :234:42
      end
      else	// src/llc/scala/main/Llc.scala:218:34, :249:37, :251:29
        bHeadBeatsRem <= _GEN_10;	// src/llc/scala/main/Llc.scala:74:30, :251:20
      bHeadActive <=
        _GEN_8 & ~_GEN_11
        | (~_pipeline_io_respOut_valid | ~_pipeline_io_respOut_payload_isWrite | ~_GEN_6)
        & bHeadActive;	// src/llc/scala/main/Llc.scala:23:24, :75:30, :218:34, :219:48, :226:25, :227:37, :229:23, :249:{21,37}, :251:{20,29}, :258:21
      if ((|bSending) & io_cpu_b_ready)	// src/llc/scala/main/Llc.scala:78:25, :280:31, src/utils/Stream/Stream.scala:43:26
        bSending <= bSending - 4'h1;	// src/llc/scala/main/Llc.scala:78:25, :286:26
      else if (_GEN_13) begin	// src/llc/scala/main/Llc.scala:218:34, :249:37, :251:29, :254:17
        automatic logic [3:0][3:0] _GEN_26;	// src/llc/scala/main/Llc.scala:230:23
        _GEN_26 = {{bFifoCount_3}, {bFifoCount_2}, {bFifoCount_1}, {bFifoCount_0}};	// src/llc/scala/main/Llc.scala:67:24, :230:23
        bSending <= _GEN_26[bFifoHead];	// src/llc/scala/main/Llc.scala:69:28, :78:25, :230:23
      end
      snoopFlushReq <=
        _GEN_18 ? _wmBuf_io_snoop_hit | snoopFlushReq : ~_GEN_19 & snoopFlushReq;	// src/llc/scala/main/Llc.scala:25:24, :154:30, :157:19, :159:32, :161:23, :170:38, :171:23
      if (_GEN_14) begin	// src/llc/scala/main/Llc.scala:298:22
        if (_pipeline_io_refillReq_valid)	// src/llc/scala/main/Llc.scala:23:24
          memRdState <= 2'h1;	// src/llc/scala/main/Llc.scala:291:29
      end
      else if (_GEN_21) begin	// src/llc/scala/main/Llc.scala:298:22
        if (_GEN_22)	// src/utils/Stream/Stream.scala:43:26
          memRdState <= 2'h2;	// src/llc/scala/main/Llc.scala:291:29
      end
      else if (_GEN_23 & io_mem_r_valid & io_mem_r_ready_0 & io_mem_r_payload_last)	// src/llc/scala/main/Llc.scala:291:29, :298:22, :315:{26,70}, :316:20, :336:33, src/utils/Stream/Stream.scala:43:26
        memRdState <= 2'h0;	// src/llc/scala/main/Llc.scala:114:42, :291:29
      refillReady <=
        ~_GEN_14 & (_GEN_21 ? _GEN_22 | refillReady : ~_GEN_23 & refillReady);	// src/llc/scala/main/Llc.scala:294:29, :298:22, :300:19, :308:28, :309:21, :314:19, src/utils/Stream/Stream.scala:43:26
      _GEN_25 =
        {{(&memWrState) & io_mem_b_valid & (&memWrState) ? 2'h0 : memWrState},
         {_GEN_24 & memWrBeatCnt == 2'h1 ? 2'h3 : memWrState},
         {io_mem_aw_valid_0 & io_mem_aw_ready ? 2'h2 : memWrState},
         {_wbBuffer_io_deq_valid ? 2'h1 : memWrState}};	// src/llc/scala/main/Llc.scala:24:24, :114:42, :343:29, :346:29, :351:22, :353:35, :357:23, :362:28, :363:20, :367:27, :369:{27,57}, :370:22, :375:27, :376:20, :382:37, :385:34, src/utils/Stream/Stream.scala:43:26
      memWrState <= _GEN_25[memWrState];	// src/llc/scala/main/Llc.scala:343:29, :351:22, :353:35, :362:28, :367:27
      if (_GEN_0) begin	// src/llc/scala/main/Llc.scala:351:22
        if (_wbBuffer_io_deq_valid)	// src/llc/scala/main/Llc.scala:24:24
          memWrBeatCnt <= 2'h0;	// src/llc/scala/main/Llc.scala:114:42, :346:29
      end
      else if (memWrState == 2'h1 | ~(memWrState == 2'h2 & _GEN_24)) begin	// src/llc/scala/main/Llc.scala:343:29, :346:29, :351:22, :367:27, :368:22, src/utils/Stream/Stream.scala:43:26
      end
      else	// src/llc/scala/main/Llc.scala:346:29, :351:22
        memWrBeatCnt <= memWrBeatCnt + 2'h1;	// src/llc/scala/main/Llc.scala:346:29, :368:38
      reg_rdata <=
        axiAr_rValid | axiRValid & ~io_ctrl_r_ready
          ? (axiAr_rData_addr[7:2] == 6'h24
               ? {31'h0, cntClrPulse}
               : axiAr_rData_addr[7:2] == 6'h23 | axiAr_rData_addr[7:2] == 6'h22
                 | axiAr_rData_addr[7:2] == 6'h21 | axiAr_rData_addr[7:2] == 6'h20
                 | axiAr_rData_addr[7:2] == 6'h1F | axiAr_rData_addr[7:2] == 6'h1E
                 | axiAr_rData_addr[7:2] == 6'h1D | axiAr_rData_addr[7:2] == 6'h1C
                 | axiAr_rData_addr[7:2] == 6'h1B | axiAr_rData_addr[7:2] == 6'h1A
                 | axiAr_rData_addr[7:2] == 6'h19 | axiAr_rData_addr[7:2] == 6'h18
                   ? 32'h0
                   : axiAr_rData_addr[7:2] == 6'h17
                       ? _perfCounters_io_counters_9[63:32]
                       : axiAr_rData_addr[7:2] == 6'h16
                           ? _perfCounters_io_counters_9[31:0]
                           : axiAr_rData_addr[7:2] == 6'h15
                               ? _perfCounters_io_counters_8[63:32]
                               : axiAr_rData_addr[7:2] == 6'h14
                                   ? _perfCounters_io_counters_8[31:0]
                                   : axiAr_rData_addr[7:2] == 6'h13
                                       ? _perfCounters_io_counters_7[63:32]
                                       : axiAr_rData_addr[7:2] == 6'h12
                                           ? _perfCounters_io_counters_7[31:0]
                                           : axiAr_rData_addr[7:2] == 6'h11
                                               ? _perfCounters_io_counters_6[63:32]
                                               : axiAr_rData_addr[7:2] == 6'h10
                                                   ? _perfCounters_io_counters_6[31:0]
                                                   : axiAr_rData_addr[7:2] == 6'hF
                                                       ? _perfCounters_io_counters_5[63:32]
                                                       : axiAr_rData_addr[7:2] == 6'hE
                                                           ? _perfCounters_io_counters_5[31:0]
                                                           : axiAr_rData_addr[7:2] == 6'hD
                                                               ? _perfCounters_io_counters_4[63:32]
                                                               : axiAr_rData_addr[7:2] == 6'hC
                                                                   ? _perfCounters_io_counters_4[31:0]
                                                                   : axiAr_rData_addr[7:2] == 6'hB
                                                                       ? _perfCounters_io_counters_3[63:32]
                                                                       : axiAr_rData_addr[7:2] == 6'hA
                                                                           ? _perfCounters_io_counters_3[31:0]
                                                                           : axiAr_rData_addr[7:2] == 6'h9
                                                                               ? _perfCounters_io_counters_2[63:32]
                                                                               : axiAr_rData_addr[7:2] == 6'h8
                                                                                   ? _perfCounters_io_counters_2[31:0]
                                                                                   : axiAr_rData_addr[7:2] == 6'h7
                                                                                       ? _perfCounters_io_counters_1[63:32]
                                                                                       : axiAr_rData_addr[7:2] == 6'h6
                                                                                           ? _perfCounters_io_counters_1[31:0]
                                                                                           : axiAr_rData_addr[7:2] == 6'h5
                                                                                               ? _perfCounters_io_counters_0[63:32]
                                                                                               : axiAr_rData_addr[7:2] == 6'h4
                                                                                                   ? _perfCounters_io_counters_0[31:0]
                                                                                                   : axiAr_rData_addr[7:2] == 6'h2
                                                                                                       ? {16'h0,
                                                                                                          wayPartCfg}
                                                                                                       : axiAr_rData_addr[7:2] == 6'h1
                                                                                                           ? {26'h0,
                                                                                                              flushDoneSticky,
                                                                                                              _pipeline_io_flushBusy,
                                                                                                              _wmBuf_io_flushing,
                                                                                                              _pipeline_io_perfEvents_mshrFullStall,
                                                                                                              _wbBuffer_io_full,
                                                                                                              _wbBuffer_io_empty}
                                                                                                           : axiAr_rData_addr[7:2] == 6'h0
                                                                                                               ? {29'h0,
                                                                                                                  ctrlInvalidate,
                                                                                                                  ctrlFlush,
                                                                                                                  ctrlEnable}
                                                                                                               : 32'h0)
          : 32'h0;	// src/llc/scala/main/Llc.scala:15:7, :23:24, :24:24, :25:24, :26:28, :443:32, :475:41, :479:41, src/utils/Stream/Stream.scala:153:25, :154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:24:32, :28:26, :60:{29,44,47}, :78:27, src/utils/bus/regif/BusIf.scala:298:15, :315:19, :319:17, src/utils/bus/regif/RegBase.scala:38:8, src/utils/bus/regif/RegInst.scala:76:16, :303:{27,39}, :304:20
      if (io_ctrl_ar_ready_0)	// src/utils/Stream/Stream.scala:156:16, :158:{21,34}
        axiAr_rValid <= io_ctrl_ar_valid;	// src/utils/Stream/Stream.scala:153:25
      axiRValid <= doRead | ~io_ctrl_r_ready & axiRValid;	// src/utils/bus/regif/AxiLite4BusInterface.scala:28:26, :62:40, :67:{20,32}, :68:{16,28}
      if (io_ctrl_aw_ready_0)	// src/utils/Stream/Stream.scala:156:16, :158:{21,34}
        axiAw_rValid <= io_ctrl_aw_valid;	// src/utils/Stream/Stream.scala:153:25
      if (io_ctrl_w_ready_0)	// src/utils/Stream/Stream.scala:156:16, :158:{21,34}
        axiW_rValid <= io_ctrl_w_valid;	// src/utils/Stream/Stream.scala:153:25
      axiBValid <= doWrite | ~io_ctrl_b_ready & axiBValid;	// src/utils/bus/regif/AxiLite4BusInterface.scala:33:26, :59:30, :61:38, :71:{20,32}, :72:{17,29}
      if (axiAw_rData_addr == 8'h0 & doWrite) begin	// src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:59:30, :61:38, src/utils/bus/regif/BusIfBase.scala:143:33, src/utils/bus/regif/RegBase.scala:29:{63,74}
        ctrlEnable <= ctrlEnable & _zeros_T[0] | axiW_rData_data[0] & wstrb[0];	// src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:40:19, src/utils/bus/regif/BusIfBase.scala:13:36, :143:33, :144:{34,38}, :162:{32,47,65}, src/utils/bus/regif/RegInst.scala:76:16
        ctrlFlush <= ctrlFlush & _zeros_T[0] | axiW_rData_data[1] & wstrb[0];	// src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:40:19, src/utils/bus/regif/BusIfBase.scala:13:36, :143:33, :144:{34,38}, :162:{32,47,65}, src/utils/bus/regif/RegInst.scala:76:16
        ctrlInvalidate <= ctrlInvalidate & _zeros_T[0] | axiW_rData_data[2] & wstrb[0];	// src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:40:19, src/utils/bus/regif/BusIfBase.scala:13:36, :143:33, :144:{34,38}, :162:{32,47,65}, src/utils/bus/regif/RegInst.scala:76:16
      end
      ctrlFlushReqPrev <= ctrlFlushReq;	// src/llc/scala/main/Llc.scala:435:36, :436:33
      flushDoneSticky <= ~flushStartPulse & (_pipeline_io_flushDone | flushDoneSticky);	// src/llc/scala/main/Llc.scala:23:24, :437:{39,60}, :443:32, :444:{31,49}, :445:{31,49}
      if (axiAw_rData_addr == 8'h8 & doWrite)	// src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:59:30, :61:38, src/utils/bus/regif/RegBase.scala:29:{63,74}
        wayPartCfg <=
          wayPartCfg & {{8{_zeros_T[1]}}, {8{_zeros_T[0]}}} | axiW_rData_data[15:0]
          & {{8{wstrb[1]}}, {8{wstrb[0]}}};	// src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:40:19, src/utils/bus/regif/BusIfBase.scala:13:36, :143:33, :144:{34,38}, :162:{32,47,65}, src/utils/bus/regif/RegInst.scala:76:16
      cntClrPulse <=
        axiAw_rData_addr == 8'h90 & doWrite & axiW_rData_data[0] & wstrb[0]
        & (cntClrPulse & _zeros_T[0] | ~cntClrPulse & wstrb[0]);	// src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:40:19, :59:30, :61:38, src/utils/bus/regif/BusIfBase.scala:13:36, :65:64, :143:33, :144:{34,38}, :164:{32,47,50,59}, src/utils/bus/regif/RegBase.scala:27:61, :29:{63,74}, :175:22, :176:{11,20}, :178:11, src/utils/bus/regif/RegInst.scala:76:16
    end
    if (_GEN_1) begin	// src/utils/Stream/Stream.scala:43:26
      rdAddr <= io_cpu_ar_payload_addr;	// src/llc/scala/main/Llc.scala:43:22
      rdId <= io_cpu_ar_payload_id;	// src/llc/scala/main/Llc.scala:44:22
      rdLen <= io_cpu_ar_payload_len;	// src/llc/scala/main/Llc.scala:45:22
    end
    if (_GEN_4) begin	// src/llc/scala/main/Llc.scala:46:22, :218:34, :219:48, :221:17
      rdData_0 <= _pipeline_io_respOut_payload_data_0;	// src/llc/scala/main/Llc.scala:23:24, :46:22
      rdData_1 <= _pipeline_io_respOut_payload_data_1;	// src/llc/scala/main/Llc.scala:23:24, :46:22
    end
    if (_GEN_2) begin	// src/utils/Stream/Stream.scala:43:26
      wrAddr <= io_cpu_aw_payload_addr;	// src/llc/scala/main/Llc.scala:54:23
      wrId <= io_cpu_aw_payload_id;	// src/llc/scala/main/Llc.scala:55:23
      wrLen <= io_cpu_aw_payload_len;	// src/llc/scala/main/Llc.scala:56:23
    end
    if (_GEN_3 & ~(wrBeatRecv[0])) begin	// <stdin>:5563:19, src/llc/scala/main/Llc.scala:57:23, :59:27, :102:23, :103:27, src/utils/Stream/Stream.scala:43:26
      wrBuf_0 <= io_cpu_w_payload_data;	// src/llc/scala/main/Llc.scala:57:23
      wrStrbBuf_0 <= io_cpu_w_payload_strb;	// src/llc/scala/main/Llc.scala:58:23
    end
    if (_GEN_3 & wrBeatRecv[0]) begin	// <stdin>:5563:19, src/llc/scala/main/Llc.scala:57:23, :59:27, :102:23, :103:27, src/utils/Stream/Stream.scala:43:26
      wrBuf_1 <= io_cpu_w_payload_data;	// src/llc/scala/main/Llc.scala:57:23
      wrStrbBuf_1 <= io_cpu_w_payload_strb;	// src/llc/scala/main/Llc.scala:58:23
    end
    if (_wmBuf_io_bRespOut_valid & bFifoTail == 2'h0) begin	// src/llc/scala/main/Llc.scala:25:24, :66:24, :70:28, :114:42, :241:33, :242:27
      bFifoId_0 <= _wmBuf_io_bRespOut_bits_id;	// src/llc/scala/main/Llc.scala:25:24, :66:24
      bFifoCount_0 <= _wmBuf_io_bRespOut_bits_count;	// src/llc/scala/main/Llc.scala:25:24, :67:24
      bFifoBeats_0 <= _wmBuf_io_bRespOut_bits_beats;	// src/llc/scala/main/Llc.scala:25:24, :68:24
    end
    if (_wmBuf_io_bRespOut_valid & bFifoTail == 2'h1) begin	// src/llc/scala/main/Llc.scala:25:24, :66:24, :70:28, :241:33, :242:27
      bFifoId_1 <= _wmBuf_io_bRespOut_bits_id;	// src/llc/scala/main/Llc.scala:25:24, :66:24
      bFifoCount_1 <= _wmBuf_io_bRespOut_bits_count;	// src/llc/scala/main/Llc.scala:25:24, :67:24
      bFifoBeats_1 <= _wmBuf_io_bRespOut_bits_beats;	// src/llc/scala/main/Llc.scala:25:24, :68:24
    end
    if (_wmBuf_io_bRespOut_valid & bFifoTail == 2'h2) begin	// src/llc/scala/main/Llc.scala:25:24, :66:24, :70:28, :241:33, :242:27
      bFifoId_2 <= _wmBuf_io_bRespOut_bits_id;	// src/llc/scala/main/Llc.scala:25:24, :66:24
      bFifoCount_2 <= _wmBuf_io_bRespOut_bits_count;	// src/llc/scala/main/Llc.scala:25:24, :67:24
      bFifoBeats_2 <= _wmBuf_io_bRespOut_bits_beats;	// src/llc/scala/main/Llc.scala:25:24, :68:24
    end
    if (_wmBuf_io_bRespOut_valid & (&bFifoTail)) begin	// src/llc/scala/main/Llc.scala:25:24, :66:24, :70:28, :241:33, :242:27
      bFifoId_3 <= _wmBuf_io_bRespOut_bits_id;	// src/llc/scala/main/Llc.scala:25:24, :66:24
      bFifoCount_3 <= _wmBuf_io_bRespOut_bits_count;	// src/llc/scala/main/Llc.scala:25:24, :67:24
      bFifoBeats_3 <= _wmBuf_io_bRespOut_bits_beats;	// src/llc/scala/main/Llc.scala:25:24, :68:24
    end
    if (_GEN_13) begin	// src/llc/scala/main/Llc.scala:218:34, :249:37, :251:29, :254:17, :255:17
      automatic logic [3:0][3:0] _GEN_27;	// src/llc/scala/main/Llc.scala:231:23
      _GEN_27 = {{bFifoId_3}, {bFifoId_2}, {bFifoId_1}, {bFifoId_0}};	// src/llc/scala/main/Llc.scala:66:24, :231:23
      bSendId <= _GEN_27[bFifoHead];	// src/llc/scala/main/Llc.scala:69:28, :79:21, :231:23
    end
    if (_GEN_14 & _pipeline_io_refillReq_valid) begin	// src/llc/scala/main/Llc.scala:23:24, :292:25, :298:22, :301:41, :302:20
      memRdAddr <= _pipeline_io_refillReq_bits_address;	// src/llc/scala/main/Llc.scala:23:24, :292:25
      memRdId <= _pipeline_io_refillReq_bits_id;	// src/llc/scala/main/Llc.scala:23:24, :293:25
    end
    if (_GEN_0 & _wbBuffer_io_deq_valid) begin	// src/llc/scala/main/Llc.scala:24:24, :344:25, :351:22, :353:35, :354:23
      memWrAddr <= _wbBuffer_io_deq_bits_address;	// src/llc/scala/main/Llc.scala:24:24, :344:25
      memWrData_0 <= _wbBuffer_io_deq_bits_data_0;	// src/llc/scala/main/Llc.scala:24:24, :345:25
      memWrData_1 <= _wbBuffer_io_deq_bits_data_1;	// src/llc/scala/main/Llc.scala:24:24, :345:25
    end
    if (io_ctrl_ar_ready_0)	// src/utils/Stream/Stream.scala:156:16, :158:{21,34}
      axiAr_rData_addr <= io_ctrl_ar_payload_addr;	// src/utils/Stream/Stream.scala:154:20
    if (io_ctrl_aw_ready_0)	// src/utils/Stream/Stream.scala:156:16, :158:{21,34}
      axiAw_rData_addr <= io_ctrl_aw_payload_addr;	// src/utils/Stream/Stream.scala:154:20
    if (io_ctrl_w_ready_0) begin	// src/utils/Stream/Stream.scala:156:16, :158:{21,34}
      axiW_rData_data <= io_ctrl_w_payload_data;	// src/utils/Stream/Stream.scala:154:20
      axiW_rData_strb <= io_ctrl_w_payload_strb;	// src/utils/Stream/Stream.scala:154:20
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/llc/scala/main/Llc.scala:15:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/llc/scala/main/Llc.scala:15:7
      `FIRRTL_BEFORE_INITIAL	// src/llc/scala/main/Llc.scala:15:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/llc/scala/main/Llc.scala:15:7
      automatic logic [31:0] _RANDOM[0:60];	// src/llc/scala/main/Llc.scala:15:7
      `ifdef INIT_RANDOM_PROLOG_	// src/llc/scala/main/Llc.scala:15:7
        `INIT_RANDOM_PROLOG_	// src/llc/scala/main/Llc.scala:15:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/llc/scala/main/Llc.scala:15:7
        for (logic [5:0] i = 6'h0; i < 6'h3D; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// src/llc/scala/main/Llc.scala:15:7
        end	// src/llc/scala/main/Llc.scala:15:7
        rdState = _RANDOM[6'h0][2:0];	// src/llc/scala/main/Llc.scala:15:7, :42:26
        rdAddr = {_RANDOM[6'h0][31:3], _RANDOM[6'h1][2:0]};	// src/llc/scala/main/Llc.scala:15:7, :42:26, :43:22
        rdId = _RANDOM[6'h1][6:3];	// src/llc/scala/main/Llc.scala:15:7, :43:22, :44:22
        rdLen = _RANDOM[6'h1][14:7];	// src/llc/scala/main/Llc.scala:15:7, :43:22, :45:22
        rdData_0 =
          {_RANDOM[6'h1][31:15],
           _RANDOM[6'h2],
           _RANDOM[6'h3],
           _RANDOM[6'h4],
           _RANDOM[6'h5],
           _RANDOM[6'h6],
           _RANDOM[6'h7],
           _RANDOM[6'h8],
           _RANDOM[6'h9][14:0]};	// src/llc/scala/main/Llc.scala:15:7, :43:22, :46:22
        rdData_1 =
          {_RANDOM[6'h9][31:15],
           _RANDOM[6'hA],
           _RANDOM[6'hB],
           _RANDOM[6'hC],
           _RANDOM[6'hD],
           _RANDOM[6'hE],
           _RANDOM[6'hF],
           _RANDOM[6'h10],
           _RANDOM[6'h11][14:0]};	// src/llc/scala/main/Llc.scala:15:7, :46:22
        rdBeatCnt = _RANDOM[6'h11][16:15];	// src/llc/scala/main/Llc.scala:15:7, :46:22, :47:26
        rdReqValid = _RANDOM[6'h11][17];	// src/llc/scala/main/Llc.scala:15:7, :46:22, :48:27
        wrState = _RANDOM[6'h11][19:18];	// src/llc/scala/main/Llc.scala:15:7, :46:22, :53:27
        wrAddr = {_RANDOM[6'h11][31:20], _RANDOM[6'h12][19:0]};	// src/llc/scala/main/Llc.scala:15:7, :46:22, :54:23
        wrId = _RANDOM[6'h12][23:20];	// src/llc/scala/main/Llc.scala:15:7, :54:23, :55:23
        wrLen = _RANDOM[6'h12][31:24];	// src/llc/scala/main/Llc.scala:15:7, :54:23, :56:23
        wrBuf_0 =
          {_RANDOM[6'h13],
           _RANDOM[6'h14],
           _RANDOM[6'h15],
           _RANDOM[6'h16],
           _RANDOM[6'h17],
           _RANDOM[6'h18],
           _RANDOM[6'h19],
           _RANDOM[6'h1A]};	// src/llc/scala/main/Llc.scala:15:7, :57:23
        wrBuf_1 =
          {_RANDOM[6'h1B],
           _RANDOM[6'h1C],
           _RANDOM[6'h1D],
           _RANDOM[6'h1E],
           _RANDOM[6'h1F],
           _RANDOM[6'h20],
           _RANDOM[6'h21],
           _RANDOM[6'h22]};	// src/llc/scala/main/Llc.scala:15:7, :57:23
        wrStrbBuf_0 = _RANDOM[6'h23];	// src/llc/scala/main/Llc.scala:15:7, :58:23
        wrStrbBuf_1 = _RANDOM[6'h24];	// src/llc/scala/main/Llc.scala:15:7, :58:23
        wrBeatRecv = _RANDOM[6'h25][1:0];	// src/llc/scala/main/Llc.scala:15:7, :59:27
        wrSendIdx = _RANDOM[6'h25][3:2];	// src/llc/scala/main/Llc.scala:15:7, :59:27, :60:27
        wrAwValid = _RANDOM[6'h25][4];	// src/llc/scala/main/Llc.scala:15:7, :59:27, :61:27
        bFifoId_0 = _RANDOM[6'h25][8:5];	// src/llc/scala/main/Llc.scala:15:7, :59:27, :66:24
        bFifoId_1 = _RANDOM[6'h25][12:9];	// src/llc/scala/main/Llc.scala:15:7, :59:27, :66:24
        bFifoId_2 = _RANDOM[6'h25][16:13];	// src/llc/scala/main/Llc.scala:15:7, :59:27, :66:24
        bFifoId_3 = _RANDOM[6'h25][20:17];	// src/llc/scala/main/Llc.scala:15:7, :59:27, :66:24
        bFifoCount_0 = _RANDOM[6'h25][24:21];	// src/llc/scala/main/Llc.scala:15:7, :59:27, :67:24
        bFifoCount_1 = _RANDOM[6'h25][28:25];	// src/llc/scala/main/Llc.scala:15:7, :59:27, :67:24
        bFifoCount_2 = {_RANDOM[6'h25][31:29], _RANDOM[6'h26][0]};	// src/llc/scala/main/Llc.scala:15:7, :59:27, :67:24
        bFifoCount_3 = _RANDOM[6'h26][4:1];	// src/llc/scala/main/Llc.scala:15:7, :67:24
        bFifoBeats_0 = _RANDOM[6'h26][6:5];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :68:24
        bFifoBeats_1 = _RANDOM[6'h26][8:7];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :68:24
        bFifoBeats_2 = _RANDOM[6'h26][10:9];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :68:24
        bFifoBeats_3 = _RANDOM[6'h26][12:11];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :68:24
        bFifoHead = _RANDOM[6'h26][14:13];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :69:28
        bFifoTail = _RANDOM[6'h26][16:15];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :70:28
        bHeadBeatsRem = _RANDOM[6'h26][18:17];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :74:30
        bHeadActive = _RANDOM[6'h26][19];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :75:30
        bSending = _RANDOM[6'h26][23:20];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :78:25
        bSendId = _RANDOM[6'h26][27:24];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :79:21
        snoopFlushReq = _RANDOM[6'h26][28];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :154:30
        memRdState = _RANDOM[6'h26][30:29];	// src/llc/scala/main/Llc.scala:15:7, :67:24, :291:29
        memRdAddr = {_RANDOM[6'h26][31], _RANDOM[6'h27][30:0]};	// src/llc/scala/main/Llc.scala:15:7, :67:24, :292:25
        memRdId = {_RANDOM[6'h27][31], _RANDOM[6'h28][2:0]};	// src/llc/scala/main/Llc.scala:15:7, :292:25, :293:25
        refillReady = _RANDOM[6'h28][3];	// src/llc/scala/main/Llc.scala:15:7, :293:25, :294:29
        memWrState = _RANDOM[6'h28][5:4];	// src/llc/scala/main/Llc.scala:15:7, :293:25, :343:29
        memWrAddr = {_RANDOM[6'h28][31:6], _RANDOM[6'h29][5:0]};	// src/llc/scala/main/Llc.scala:15:7, :293:25, :344:25
        memWrData_0 =
          {_RANDOM[6'h29][31:6],
           _RANDOM[6'h2A],
           _RANDOM[6'h2B],
           _RANDOM[6'h2C],
           _RANDOM[6'h2D],
           _RANDOM[6'h2E],
           _RANDOM[6'h2F],
           _RANDOM[6'h30],
           _RANDOM[6'h31][5:0]};	// src/llc/scala/main/Llc.scala:15:7, :344:25, :345:25
        memWrData_1 =
          {_RANDOM[6'h31][31:6],
           _RANDOM[6'h32],
           _RANDOM[6'h33],
           _RANDOM[6'h34],
           _RANDOM[6'h35],
           _RANDOM[6'h36],
           _RANDOM[6'h37],
           _RANDOM[6'h38],
           _RANDOM[6'h39][5:0]};	// src/llc/scala/main/Llc.scala:15:7, :345:25
        memWrBeatCnt = _RANDOM[6'h39][7:6];	// src/llc/scala/main/Llc.scala:15:7, :345:25, :346:29
        reg_rdata = {_RANDOM[6'h39][31:9], _RANDOM[6'h3A][8:0]};	// src/llc/scala/main/Llc.scala:15:7, :345:25, src/utils/bus/regif/AxiLite4BusInterface.scala:24:32
        axiAr_rValid = _RANDOM[6'h3A][9];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:153:25, src/utils/bus/regif/AxiLite4BusInterface.scala:24:32
        axiAr_rData_addr = _RANDOM[6'h3A][17:10];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:24:32
        axiRValid = _RANDOM[6'h3A][21];	// src/llc/scala/main/Llc.scala:15:7, src/utils/bus/regif/AxiLite4BusInterface.scala:24:32, :28:26
        axiAw_rValid = _RANDOM[6'h3A][22];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:153:25, src/utils/bus/regif/AxiLite4BusInterface.scala:24:32
        axiAw_rData_addr = _RANDOM[6'h3A][30:23];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:24:32
        axiW_rValid = _RANDOM[6'h3B][2];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:153:25
        axiW_rData_data = {_RANDOM[6'h3B][31:3], _RANDOM[6'h3C][2:0]};	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:153:25, :154:20
        axiW_rData_strb = _RANDOM[6'h3C][6:3];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20
        axiBValid = _RANDOM[6'h3C][7];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/AxiLite4BusInterface.scala:33:26
        ctrlEnable = _RANDOM[6'h3C][8];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/RegInst.scala:76:16
        ctrlFlush = _RANDOM[6'h3C][9];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/RegInst.scala:76:16
        ctrlInvalidate = _RANDOM[6'h3C][10];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/RegInst.scala:76:16
        ctrlFlushReqPrev = _RANDOM[6'h3C][11];	// src/llc/scala/main/Llc.scala:15:7, :436:33, src/utils/Stream/Stream.scala:154:20
        flushDoneSticky = _RANDOM[6'h3C][12];	// src/llc/scala/main/Llc.scala:15:7, :443:32, src/utils/Stream/Stream.scala:154:20
        wayPartCfg = _RANDOM[6'h3C][28:13];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/RegInst.scala:76:16
        cntClrPulse = _RANDOM[6'h3C][29];	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:154:20, src/utils/bus/regif/RegInst.scala:76:16
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/llc/scala/main/Llc.scala:15:7
      `FIRRTL_AFTER_INITIAL	// src/llc/scala/main/Llc.scala:15:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  LlcPipeline pipeline (	// src/llc/scala/main/Llc.scala:23:24
    .clock                        (clock),
    .reset                        (reset),
    .io_reqIn_valid               (pipeline_io_reqIn_valid),	// src/llc/scala/main/Llc.scala:201:21, :202:31, :205:27
    .io_reqIn_ready               (_pipeline_io_reqIn_ready),
    .io_reqIn_payload_isWrite     (_wmBuf_io_pipeOut_valid),	// src/llc/scala/main/Llc.scala:25:24
    .io_reqIn_payload_address
      (_wmBuf_io_pipeOut_valid ? _wmBuf_io_pipeOut_payload_address : rdAddr),	// src/llc/scala/main/Llc.scala:25:24, :43:22, :201:21, :203:31, :205:27
    .io_reqIn_payload_id
      (_wmBuf_io_pipeOut_valid ? _wmBuf_io_pipeOut_payload_id : rdId),	// src/llc/scala/main/Llc.scala:25:24, :44:22, :201:21, :203:31, :205:27
    .io_reqIn_payload_writeData
      (_wmBuf_io_pipeOut_valid ? _wmBuf_io_pipeOut_payload_writeData : 256'h0),	// src/llc/scala/main/Llc.scala:25:24, :189:23, :201:21, :203:31, :205:27
    .io_reqIn_payload_writeStrb
      (_wmBuf_io_pipeOut_valid ? _wmBuf_io_pipeOut_payload_writeStrb : 32'h0),	// src/llc/scala/main/Llc.scala:25:24, :201:21, :203:31, :205:27
    .io_reqIn_payload_beatIdx
      (_wmBuf_io_pipeOut_valid & _wmBuf_io_pipeOut_payload_beatIdx),	// src/llc/scala/main/Llc.scala:25:24, :201:21, :203:31, :205:27
    .io_respOut_valid             (_pipeline_io_respOut_valid),
    .io_respOut_payload_isWrite   (_pipeline_io_respOut_payload_isWrite),
    .io_respOut_payload_data_0    (_pipeline_io_respOut_payload_data_0),
    .io_respOut_payload_data_1    (_pipeline_io_respOut_payload_data_1),
    .io_wbReq_valid               (_pipeline_io_wbReq_valid),
    .io_wbReq_bits_address        (_pipeline_io_wbReq_bits_address),
    .io_wbReq_bits_data_0         (_pipeline_io_wbReq_bits_data_0),
    .io_wbReq_bits_data_1         (_pipeline_io_wbReq_bits_data_1),
    .io_wbDone                    ((&memWrState) & io_mem_b_valid),	// src/llc/scala/main/Llc.scala:343:29, :382:{37,53}, src/utils/Stream/Stream.scala:43:26
    .io_refillReq_valid           (_pipeline_io_refillReq_valid),
    .io_refillReq_bits_address    (_pipeline_io_refillReq_bits_address),
    .io_refillReq_bits_id         (_pipeline_io_refillReq_bits_id),
    .io_refillReady               (refillReady),	// src/llc/scala/main/Llc.scala:294:29
    .io_refillData_valid          (io_mem_r_valid & io_mem_r_ready_0),	// src/llc/scala/main/Llc.scala:336:33, src/utils/Stream/Stream.scala:43:26
    .io_refillData_bits_data      (io_mem_r_payload_data),
    .io_refillData_bits_last      (io_mem_r_payload_last),
    .io_perfEvents_readHit        (_pipeline_io_perfEvents_readHit),
    .io_perfEvents_readMiss       (_pipeline_io_perfEvents_readMiss),
    .io_perfEvents_writeHit       (_pipeline_io_perfEvents_writeHit),
    .io_perfEvents_writeMiss      (_pipeline_io_perfEvents_writeMiss),
    .io_perfEvents_dirtyEvict     (_pipeline_io_perfEvents_dirtyEvict),
    .io_perfEvents_cleanEvict     (_pipeline_io_perfEvents_cleanEvict),
    .io_perfEvents_mshrFullStall  (_pipeline_io_perfEvents_mshrFullStall),
    .io_perfEvents_refillComplete (_pipeline_io_perfEvents_refillComplete),
    .io_flushStart                (flushStartPulse),	// src/llc/scala/main/Llc.scala:437:{39,60}
    .io_flushIsInvalidate         (ctrlInvalidate),	// src/utils/bus/regif/RegInst.scala:76:16
    .io_flushBusy                 (_pipeline_io_flushBusy),
    .io_flushDone                 (_pipeline_io_flushDone),
    .io_wbBufEmpty                (_wbBuffer_io_empty),	// src/llc/scala/main/Llc.scala:24:24
    .io_wbBufEnqReady             (_wbBuffer_io_enqReady)	// src/llc/scala/main/Llc.scala:24:24
  );	// src/llc/scala/main/Llc.scala:23:24
  LlcWbBuffer wbBuffer (	// src/llc/scala/main/Llc.scala:24:24
    .clock               (clock),
    .reset               (reset),
    .io_enq_valid        (_pipeline_io_wbReq_valid),	// src/llc/scala/main/Llc.scala:23:24
    .io_enq_bits_address (_pipeline_io_wbReq_bits_address),	// src/llc/scala/main/Llc.scala:23:24
    .io_enq_bits_data_0  (_pipeline_io_wbReq_bits_data_0),	// src/llc/scala/main/Llc.scala:23:24
    .io_enq_bits_data_1  (_pipeline_io_wbReq_bits_data_1),	// src/llc/scala/main/Llc.scala:23:24
    .io_enqReady         (_wbBuffer_io_enqReady),
    .io_deq_valid        (_wbBuffer_io_deq_valid),
    .io_deq_bits_address (_wbBuffer_io_deq_bits_address),
    .io_deq_bits_data_0  (_wbBuffer_io_deq_bits_data_0),
    .io_deq_bits_data_1  (_wbBuffer_io_deq_bits_data_1),
    .io_deqReady         (_GEN_0 & _wbBuffer_io_deq_valid),	// src/llc/scala/main/Llc.scala:24:24, :348:24, :351:22, :353:35
    .io_empty            (_wbBuffer_io_empty),
    .io_full             (_wbBuffer_io_full)
  );	// src/llc/scala/main/Llc.scala:24:24
  LlcWriteMergeBuffer wmBuf (	// src/llc/scala/main/Llc.scala:25:24
    .clock                        (clock),
    .reset                        (reset),
    .io_writeIn_valid             (wmBuf_io_writeIn_valid),	// src/llc/scala/main/Llc.scala:138:53
    .io_writeIn_ready             (_wmBuf_io_writeIn_ready),
    .io_writeIn_payload_address   (wrAddr),	// src/llc/scala/main/Llc.scala:54:23
    .io_writeIn_payload_beatIdx   (wrSendIdx[0]),	// src/llc/scala/main/Llc.scala:60:27, :132:22
    .io_writeIn_payload_data      (wrSendIdx[0] ? wrBuf_1 : wrBuf_0),	// <stdin>:5599:31, src/llc/scala/main/Llc.scala:57:23, :60:27, :133:22
    .io_writeIn_payload_strb      (wrSendIdx[0] ? wrStrbBuf_1 : wrStrbBuf_0),	// <stdin>:5599:31, src/llc/scala/main/Llc.scala:58:23, :60:27, :134:22
    .io_writeIn_payload_id        (wrId),	// src/llc/scala/main/Llc.scala:55:23
    .io_writeIn_payload_last      (wrWmBufReq_last),	// src/llc/scala/main/Llc.scala:136:36
    .io_pipeOut_valid             (_wmBuf_io_pipeOut_valid),
    .io_pipeOut_ready             (_wmBuf_io_pipeOut_valid & _pipeline_io_reqIn_ready),	// src/llc/scala/main/Llc.scala:23:24, :25:24, :199:29, :201:21, :204:31
    .io_pipeOut_payload_address   (_wmBuf_io_pipeOut_payload_address),
    .io_pipeOut_payload_id        (_wmBuf_io_pipeOut_payload_id),
    .io_pipeOut_payload_writeData (_wmBuf_io_pipeOut_payload_writeData),
    .io_pipeOut_payload_writeStrb (_wmBuf_io_pipeOut_payload_writeStrb),
    .io_pipeOut_payload_beatIdx   (_wmBuf_io_pipeOut_payload_beatIdx),
    .io_bRespOut_valid            (_wmBuf_io_bRespOut_valid),
    .io_bRespOut_bits_id          (_wmBuf_io_bRespOut_bits_id),
    .io_bRespOut_bits_count       (_wmBuf_io_bRespOut_bits_count),
    .io_bRespOut_bits_beats       (_wmBuf_io_bRespOut_bits_beats),
    .io_snoop_address             (rdAddr),	// src/llc/scala/main/Llc.scala:43:22
    .io_snoop_hit                 (_wmBuf_io_snoop_hit),
    .io_snoop_flushReq            (snoopFlushReq),	// src/llc/scala/main/Llc.scala:154:30
    .io_snoop_flushDone           (_wmBuf_io_snoop_flushDone),
    .io_flushing                  (_wmBuf_io_flushing),
    .io_mergeEvent                (_wmBuf_io_mergeEvent)
  );	// src/llc/scala/main/Llc.scala:25:24
  LlcPerfCounters perfCounters (	// src/llc/scala/main/Llc.scala:26:28
    .clock                    (clock),
    .reset                    (reset),
    .io_events_readHit        (_pipeline_io_perfEvents_readHit),	// src/llc/scala/main/Llc.scala:23:24
    .io_events_readMiss       (_pipeline_io_perfEvents_readMiss),	// src/llc/scala/main/Llc.scala:23:24
    .io_events_writeHit       (_pipeline_io_perfEvents_writeHit),	// src/llc/scala/main/Llc.scala:23:24
    .io_events_writeMiss      (_pipeline_io_perfEvents_writeMiss),	// src/llc/scala/main/Llc.scala:23:24
    .io_events_dirtyEvict     (_pipeline_io_perfEvents_dirtyEvict),	// src/llc/scala/main/Llc.scala:23:24
    .io_events_cleanEvict     (_pipeline_io_perfEvents_cleanEvict),	// src/llc/scala/main/Llc.scala:23:24
    .io_events_mshrFullStall  (_pipeline_io_perfEvents_mshrFullStall),	// src/llc/scala/main/Llc.scala:23:24
    .io_events_wbBufFullStall (_wbBuffer_io_full),	// src/llc/scala/main/Llc.scala:24:24
    .io_events_writeMerge     (_wmBuf_io_mergeEvent),	// src/llc/scala/main/Llc.scala:25:24
    .io_events_refillComplete (_pipeline_io_perfEvents_refillComplete),	// src/llc/scala/main/Llc.scala:23:24
    .io_counters_0            (_perfCounters_io_counters_0),
    .io_counters_1            (_perfCounters_io_counters_1),
    .io_counters_2            (_perfCounters_io_counters_2),
    .io_counters_3            (_perfCounters_io_counters_3),
    .io_counters_4            (_perfCounters_io_counters_4),
    .io_counters_5            (_perfCounters_io_counters_5),
    .io_counters_6            (_perfCounters_io_counters_6),
    .io_counters_7            (_perfCounters_io_counters_7),
    .io_counters_8            (_perfCounters_io_counters_8),
    .io_counters_9            (_perfCounters_io_counters_9),
    .io_clear                 (cntClrPulse)	// src/utils/bus/regif/RegInst.scala:76:16
  );	// src/llc/scala/main/Llc.scala:26:28
  assign io_cpu_aw_ready = io_cpu_aw_ready_0;	// src/llc/scala/main/Llc.scala:15:7, :91:44
  assign io_cpu_w_ready = io_cpu_w_ready_0;	// src/llc/scala/main/Llc.scala:15:7, :100:69
  assign io_cpu_b_valid = |bSending;	// src/llc/scala/main/Llc.scala:15:7, :78:25, :280:31
  assign io_cpu_b_payload_id = bSendId;	// src/llc/scala/main/Llc.scala:15:7, :79:21
  assign io_cpu_b_payload_resp = 2'h0;	// src/llc/scala/main/Llc.scala:15:7, :114:42
  assign io_cpu_ar_ready = io_cpu_ar_ready_0;	// src/llc/scala/main/Llc.scala:15:7, :82:31
  assign io_cpu_r_valid = io_cpu_r_valid_0;	// src/llc/scala/main/Llc.scala:15:7, :264:30
  assign io_cpu_r_payload_data = rdBeatCnt[0] ? rdData_1 : rdData_0;	// <stdin>:5738:37, src/llc/scala/main/Llc.scala:15:7, :46:22, :47:26, :265:25
  assign io_cpu_r_payload_id = rdId;	// src/llc/scala/main/Llc.scala:15:7, :44:22
  assign io_cpu_r_payload_resp = 2'h0;	// src/llc/scala/main/Llc.scala:15:7, :114:42
  assign io_cpu_r_payload_last = io_cpu_r_payload_last_0;	// src/llc/scala/main/Llc.scala:15:7, :268:49
  assign io_mem_aw_valid = io_mem_aw_valid_0;	// src/llc/scala/main/Llc.scala:15:7, :385:34
  assign io_mem_aw_payload_addr = memWrAddr;	// src/llc/scala/main/Llc.scala:15:7, :344:25
  assign io_mem_aw_payload_id = 4'h0;	// src/llc/scala/main/Llc.scala:15:7, :280:31
  assign io_mem_aw_payload_region = 4'h0;	// src/llc/scala/main/Llc.scala:15:7, :280:31
  assign io_mem_aw_payload_len = 8'h1;	// src/llc/scala/main/Llc.scala:15:7, :325:35
  assign io_mem_aw_payload_size = 3'h5;	// src/llc/scala/main/Llc.scala:15:7, :326:36
  assign io_mem_aw_payload_burst = 2'h1;	// src/llc/scala/main/Llc.scala:15:7
  assign io_mem_aw_payload_lock = 1'h0;	// src/llc/scala/main/Llc.scala:15:7
  assign io_mem_aw_payload_cache = 4'h0;	// src/llc/scala/main/Llc.scala:15:7, :280:31
  assign io_mem_aw_payload_qos = 4'h0;	// src/llc/scala/main/Llc.scala:15:7, :280:31
  assign io_mem_aw_payload_prot = 3'h0;	// src/llc/scala/main/Llc.scala:15:7
  assign io_mem_w_valid = io_mem_w_valid_0;	// src/llc/scala/main/Llc.scala:15:7, :400:33
  assign io_mem_w_payload_data = memWrBeatCnt[0] ? memWrData_1 : memWrData_0;	// <stdin>:5862:37, src/llc/scala/main/Llc.scala:15:7, :345:25, :346:29, :401:25
  assign io_mem_w_payload_strb = 32'hFFFFFFFF;	// src/llc/scala/main/Llc.scala:15:7, :402:42
  assign io_mem_w_payload_last = memWrBeatCnt == 2'h1;	// src/llc/scala/main/Llc.scala:15:7, :346:29, :403:52
  assign io_mem_b_ready = &memWrState;	// src/llc/scala/main/Llc.scala:15:7, :343:29, :382:37
  assign io_mem_ar_valid = io_mem_ar_valid_0;	// src/llc/scala/main/Llc.scala:15:7, :322:34
  assign io_mem_ar_payload_addr = memRdAddr;	// src/llc/scala/main/Llc.scala:15:7, :292:25
  assign io_mem_ar_payload_id = memRdId;	// src/llc/scala/main/Llc.scala:15:7, :293:25
  assign io_mem_ar_payload_region = 4'h0;	// src/llc/scala/main/Llc.scala:15:7, :280:31
  assign io_mem_ar_payload_len = 8'h1;	// src/llc/scala/main/Llc.scala:15:7, :325:35
  assign io_mem_ar_payload_size = 3'h5;	// src/llc/scala/main/Llc.scala:15:7, :326:36
  assign io_mem_ar_payload_burst = 2'h1;	// src/llc/scala/main/Llc.scala:15:7
  assign io_mem_ar_payload_lock = 1'h0;	// src/llc/scala/main/Llc.scala:15:7
  assign io_mem_ar_payload_cache = 4'h0;	// src/llc/scala/main/Llc.scala:15:7, :280:31
  assign io_mem_ar_payload_qos = 4'h0;	// src/llc/scala/main/Llc.scala:15:7, :280:31
  assign io_mem_ar_payload_prot = 3'h0;	// src/llc/scala/main/Llc.scala:15:7
  assign io_mem_r_ready = io_mem_r_ready_0;	// src/llc/scala/main/Llc.scala:15:7, :336:33
  assign io_ctrl_aw_ready = io_ctrl_aw_ready_0;	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:156:16, :158:{21,34}
  assign io_ctrl_w_ready = io_ctrl_w_ready_0;	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:156:16, :158:{21,34}
  assign io_ctrl_b_valid = axiBValid;	// src/llc/scala/main/Llc.scala:15:7, src/utils/bus/regif/AxiLite4BusInterface.scala:33:26
  assign io_ctrl_b_payload_resp = 2'h0;	// src/llc/scala/main/Llc.scala:15:7, :114:42
  assign io_ctrl_ar_ready = io_ctrl_ar_ready_0;	// src/llc/scala/main/Llc.scala:15:7, src/utils/Stream/Stream.scala:156:16, :158:{21,34}
  assign io_ctrl_r_valid = axiRValid;	// src/llc/scala/main/Llc.scala:15:7, src/utils/bus/regif/AxiLite4BusInterface.scala:28:26
  assign io_ctrl_r_payload_data = reg_rdata;	// src/llc/scala/main/Llc.scala:15:7, src/utils/bus/regif/AxiLite4BusInterface.scala:24:32
  assign io_ctrl_r_payload_resp = 2'h0;	// src/llc/scala/main/Llc.scala:15:7, :114:42
endmodule

