// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LlcDataArray(	// src/llc/scala/main/LlcDataArray.scala:30:7
  input          clock,	// src/llc/scala/main/LlcDataArray.scala:30:7
                 io_read_enable,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input  [8:0]   io_read_set,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input  [2:0]   io_read_way,	// src/llc/scala/main/LlcDataArray.scala:31:14
  output [255:0] io_readResp_data_0,	// src/llc/scala/main/LlcDataArray.scala:31:14
                 io_readResp_data_1,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input          io_write_enable,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input  [8:0]   io_write_set,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input  [2:0]   io_write_way,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input  [255:0] io_write_data,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input          io_writeLine_enable,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input  [8:0]   io_writeLine_set,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input  [2:0]   io_writeLine_way,	// src/llc/scala/main/LlcDataArray.scala:31:14
  input  [255:0] io_writeLine_data_0,	// src/llc/scala/main/LlcDataArray.scala:31:14
                 io_writeLine_data_1	// src/llc/scala/main/LlcDataArray.scala:31:14
);

  wire [511:0]    _dataMems_7_ext_R0_data;	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _dataMems_6_ext_R0_data;	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _dataMems_5_ext_R0_data;	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _dataMems_4_ext_R0_data;	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _dataMems_3_ext_R0_data;	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _dataMems_2_ext_R0_data;	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _dataMems_1_ext_R0_data;	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _dataMems_0_ext_R0_data;	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _GEN = {2{io_write_data}};	// src/llc/scala/main/LlcDataArray.scala:40:48
  wire [511:0]    _GEN_0 = {io_writeLine_data_1, io_writeLine_data_0};	// src/llc/scala/main/LlcDataArray.scala:40:48
  reg  [2:0]      wayReg;	// src/llc/scala/main/LlcDataArray.scala:45:23
  wire [7:0][7:0] _GEN_1 =
    {{_dataMems_7_ext_R0_data[7:0]},
     {_dataMems_6_ext_R0_data[7:0]},
     {_dataMems_5_ext_R0_data[7:0]},
     {_dataMems_4_ext_R0_data[7:0]},
     {_dataMems_3_ext_R0_data[7:0]},
     {_dataMems_2_ext_R0_data[7:0]},
     {_dataMems_1_ext_R0_data[7:0]},
     {_dataMems_0_ext_R0_data[7:0]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_2 =
    {{_dataMems_7_ext_R0_data[15:8]},
     {_dataMems_6_ext_R0_data[15:8]},
     {_dataMems_5_ext_R0_data[15:8]},
     {_dataMems_4_ext_R0_data[15:8]},
     {_dataMems_3_ext_R0_data[15:8]},
     {_dataMems_2_ext_R0_data[15:8]},
     {_dataMems_1_ext_R0_data[15:8]},
     {_dataMems_0_ext_R0_data[15:8]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_3 =
    {{_dataMems_7_ext_R0_data[23:16]},
     {_dataMems_6_ext_R0_data[23:16]},
     {_dataMems_5_ext_R0_data[23:16]},
     {_dataMems_4_ext_R0_data[23:16]},
     {_dataMems_3_ext_R0_data[23:16]},
     {_dataMems_2_ext_R0_data[23:16]},
     {_dataMems_1_ext_R0_data[23:16]},
     {_dataMems_0_ext_R0_data[23:16]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_4 =
    {{_dataMems_7_ext_R0_data[31:24]},
     {_dataMems_6_ext_R0_data[31:24]},
     {_dataMems_5_ext_R0_data[31:24]},
     {_dataMems_4_ext_R0_data[31:24]},
     {_dataMems_3_ext_R0_data[31:24]},
     {_dataMems_2_ext_R0_data[31:24]},
     {_dataMems_1_ext_R0_data[31:24]},
     {_dataMems_0_ext_R0_data[31:24]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_5 =
    {{_dataMems_7_ext_R0_data[39:32]},
     {_dataMems_6_ext_R0_data[39:32]},
     {_dataMems_5_ext_R0_data[39:32]},
     {_dataMems_4_ext_R0_data[39:32]},
     {_dataMems_3_ext_R0_data[39:32]},
     {_dataMems_2_ext_R0_data[39:32]},
     {_dataMems_1_ext_R0_data[39:32]},
     {_dataMems_0_ext_R0_data[39:32]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_6 =
    {{_dataMems_7_ext_R0_data[47:40]},
     {_dataMems_6_ext_R0_data[47:40]},
     {_dataMems_5_ext_R0_data[47:40]},
     {_dataMems_4_ext_R0_data[47:40]},
     {_dataMems_3_ext_R0_data[47:40]},
     {_dataMems_2_ext_R0_data[47:40]},
     {_dataMems_1_ext_R0_data[47:40]},
     {_dataMems_0_ext_R0_data[47:40]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_7 =
    {{_dataMems_7_ext_R0_data[55:48]},
     {_dataMems_6_ext_R0_data[55:48]},
     {_dataMems_5_ext_R0_data[55:48]},
     {_dataMems_4_ext_R0_data[55:48]},
     {_dataMems_3_ext_R0_data[55:48]},
     {_dataMems_2_ext_R0_data[55:48]},
     {_dataMems_1_ext_R0_data[55:48]},
     {_dataMems_0_ext_R0_data[55:48]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_8 =
    {{_dataMems_7_ext_R0_data[63:56]},
     {_dataMems_6_ext_R0_data[63:56]},
     {_dataMems_5_ext_R0_data[63:56]},
     {_dataMems_4_ext_R0_data[63:56]},
     {_dataMems_3_ext_R0_data[63:56]},
     {_dataMems_2_ext_R0_data[63:56]},
     {_dataMems_1_ext_R0_data[63:56]},
     {_dataMems_0_ext_R0_data[63:56]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_9 =
    {{_dataMems_7_ext_R0_data[71:64]},
     {_dataMems_6_ext_R0_data[71:64]},
     {_dataMems_5_ext_R0_data[71:64]},
     {_dataMems_4_ext_R0_data[71:64]},
     {_dataMems_3_ext_R0_data[71:64]},
     {_dataMems_2_ext_R0_data[71:64]},
     {_dataMems_1_ext_R0_data[71:64]},
     {_dataMems_0_ext_R0_data[71:64]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_10 =
    {{_dataMems_7_ext_R0_data[79:72]},
     {_dataMems_6_ext_R0_data[79:72]},
     {_dataMems_5_ext_R0_data[79:72]},
     {_dataMems_4_ext_R0_data[79:72]},
     {_dataMems_3_ext_R0_data[79:72]},
     {_dataMems_2_ext_R0_data[79:72]},
     {_dataMems_1_ext_R0_data[79:72]},
     {_dataMems_0_ext_R0_data[79:72]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_11 =
    {{_dataMems_7_ext_R0_data[87:80]},
     {_dataMems_6_ext_R0_data[87:80]},
     {_dataMems_5_ext_R0_data[87:80]},
     {_dataMems_4_ext_R0_data[87:80]},
     {_dataMems_3_ext_R0_data[87:80]},
     {_dataMems_2_ext_R0_data[87:80]},
     {_dataMems_1_ext_R0_data[87:80]},
     {_dataMems_0_ext_R0_data[87:80]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_12 =
    {{_dataMems_7_ext_R0_data[95:88]},
     {_dataMems_6_ext_R0_data[95:88]},
     {_dataMems_5_ext_R0_data[95:88]},
     {_dataMems_4_ext_R0_data[95:88]},
     {_dataMems_3_ext_R0_data[95:88]},
     {_dataMems_2_ext_R0_data[95:88]},
     {_dataMems_1_ext_R0_data[95:88]},
     {_dataMems_0_ext_R0_data[95:88]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_13 =
    {{_dataMems_7_ext_R0_data[103:96]},
     {_dataMems_6_ext_R0_data[103:96]},
     {_dataMems_5_ext_R0_data[103:96]},
     {_dataMems_4_ext_R0_data[103:96]},
     {_dataMems_3_ext_R0_data[103:96]},
     {_dataMems_2_ext_R0_data[103:96]},
     {_dataMems_1_ext_R0_data[103:96]},
     {_dataMems_0_ext_R0_data[103:96]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_14 =
    {{_dataMems_7_ext_R0_data[111:104]},
     {_dataMems_6_ext_R0_data[111:104]},
     {_dataMems_5_ext_R0_data[111:104]},
     {_dataMems_4_ext_R0_data[111:104]},
     {_dataMems_3_ext_R0_data[111:104]},
     {_dataMems_2_ext_R0_data[111:104]},
     {_dataMems_1_ext_R0_data[111:104]},
     {_dataMems_0_ext_R0_data[111:104]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_15 =
    {{_dataMems_7_ext_R0_data[119:112]},
     {_dataMems_6_ext_R0_data[119:112]},
     {_dataMems_5_ext_R0_data[119:112]},
     {_dataMems_4_ext_R0_data[119:112]},
     {_dataMems_3_ext_R0_data[119:112]},
     {_dataMems_2_ext_R0_data[119:112]},
     {_dataMems_1_ext_R0_data[119:112]},
     {_dataMems_0_ext_R0_data[119:112]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_16 =
    {{_dataMems_7_ext_R0_data[127:120]},
     {_dataMems_6_ext_R0_data[127:120]},
     {_dataMems_5_ext_R0_data[127:120]},
     {_dataMems_4_ext_R0_data[127:120]},
     {_dataMems_3_ext_R0_data[127:120]},
     {_dataMems_2_ext_R0_data[127:120]},
     {_dataMems_1_ext_R0_data[127:120]},
     {_dataMems_0_ext_R0_data[127:120]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_17 =
    {{_dataMems_7_ext_R0_data[135:128]},
     {_dataMems_6_ext_R0_data[135:128]},
     {_dataMems_5_ext_R0_data[135:128]},
     {_dataMems_4_ext_R0_data[135:128]},
     {_dataMems_3_ext_R0_data[135:128]},
     {_dataMems_2_ext_R0_data[135:128]},
     {_dataMems_1_ext_R0_data[135:128]},
     {_dataMems_0_ext_R0_data[135:128]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_18 =
    {{_dataMems_7_ext_R0_data[143:136]},
     {_dataMems_6_ext_R0_data[143:136]},
     {_dataMems_5_ext_R0_data[143:136]},
     {_dataMems_4_ext_R0_data[143:136]},
     {_dataMems_3_ext_R0_data[143:136]},
     {_dataMems_2_ext_R0_data[143:136]},
     {_dataMems_1_ext_R0_data[143:136]},
     {_dataMems_0_ext_R0_data[143:136]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_19 =
    {{_dataMems_7_ext_R0_data[151:144]},
     {_dataMems_6_ext_R0_data[151:144]},
     {_dataMems_5_ext_R0_data[151:144]},
     {_dataMems_4_ext_R0_data[151:144]},
     {_dataMems_3_ext_R0_data[151:144]},
     {_dataMems_2_ext_R0_data[151:144]},
     {_dataMems_1_ext_R0_data[151:144]},
     {_dataMems_0_ext_R0_data[151:144]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_20 =
    {{_dataMems_7_ext_R0_data[159:152]},
     {_dataMems_6_ext_R0_data[159:152]},
     {_dataMems_5_ext_R0_data[159:152]},
     {_dataMems_4_ext_R0_data[159:152]},
     {_dataMems_3_ext_R0_data[159:152]},
     {_dataMems_2_ext_R0_data[159:152]},
     {_dataMems_1_ext_R0_data[159:152]},
     {_dataMems_0_ext_R0_data[159:152]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_21 =
    {{_dataMems_7_ext_R0_data[167:160]},
     {_dataMems_6_ext_R0_data[167:160]},
     {_dataMems_5_ext_R0_data[167:160]},
     {_dataMems_4_ext_R0_data[167:160]},
     {_dataMems_3_ext_R0_data[167:160]},
     {_dataMems_2_ext_R0_data[167:160]},
     {_dataMems_1_ext_R0_data[167:160]},
     {_dataMems_0_ext_R0_data[167:160]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_22 =
    {{_dataMems_7_ext_R0_data[175:168]},
     {_dataMems_6_ext_R0_data[175:168]},
     {_dataMems_5_ext_R0_data[175:168]},
     {_dataMems_4_ext_R0_data[175:168]},
     {_dataMems_3_ext_R0_data[175:168]},
     {_dataMems_2_ext_R0_data[175:168]},
     {_dataMems_1_ext_R0_data[175:168]},
     {_dataMems_0_ext_R0_data[175:168]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_23 =
    {{_dataMems_7_ext_R0_data[183:176]},
     {_dataMems_6_ext_R0_data[183:176]},
     {_dataMems_5_ext_R0_data[183:176]},
     {_dataMems_4_ext_R0_data[183:176]},
     {_dataMems_3_ext_R0_data[183:176]},
     {_dataMems_2_ext_R0_data[183:176]},
     {_dataMems_1_ext_R0_data[183:176]},
     {_dataMems_0_ext_R0_data[183:176]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_24 =
    {{_dataMems_7_ext_R0_data[191:184]},
     {_dataMems_6_ext_R0_data[191:184]},
     {_dataMems_5_ext_R0_data[191:184]},
     {_dataMems_4_ext_R0_data[191:184]},
     {_dataMems_3_ext_R0_data[191:184]},
     {_dataMems_2_ext_R0_data[191:184]},
     {_dataMems_1_ext_R0_data[191:184]},
     {_dataMems_0_ext_R0_data[191:184]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_25 =
    {{_dataMems_7_ext_R0_data[199:192]},
     {_dataMems_6_ext_R0_data[199:192]},
     {_dataMems_5_ext_R0_data[199:192]},
     {_dataMems_4_ext_R0_data[199:192]},
     {_dataMems_3_ext_R0_data[199:192]},
     {_dataMems_2_ext_R0_data[199:192]},
     {_dataMems_1_ext_R0_data[199:192]},
     {_dataMems_0_ext_R0_data[199:192]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_26 =
    {{_dataMems_7_ext_R0_data[207:200]},
     {_dataMems_6_ext_R0_data[207:200]},
     {_dataMems_5_ext_R0_data[207:200]},
     {_dataMems_4_ext_R0_data[207:200]},
     {_dataMems_3_ext_R0_data[207:200]},
     {_dataMems_2_ext_R0_data[207:200]},
     {_dataMems_1_ext_R0_data[207:200]},
     {_dataMems_0_ext_R0_data[207:200]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_27 =
    {{_dataMems_7_ext_R0_data[215:208]},
     {_dataMems_6_ext_R0_data[215:208]},
     {_dataMems_5_ext_R0_data[215:208]},
     {_dataMems_4_ext_R0_data[215:208]},
     {_dataMems_3_ext_R0_data[215:208]},
     {_dataMems_2_ext_R0_data[215:208]},
     {_dataMems_1_ext_R0_data[215:208]},
     {_dataMems_0_ext_R0_data[215:208]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_28 =
    {{_dataMems_7_ext_R0_data[223:216]},
     {_dataMems_6_ext_R0_data[223:216]},
     {_dataMems_5_ext_R0_data[223:216]},
     {_dataMems_4_ext_R0_data[223:216]},
     {_dataMems_3_ext_R0_data[223:216]},
     {_dataMems_2_ext_R0_data[223:216]},
     {_dataMems_1_ext_R0_data[223:216]},
     {_dataMems_0_ext_R0_data[223:216]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_29 =
    {{_dataMems_7_ext_R0_data[231:224]},
     {_dataMems_6_ext_R0_data[231:224]},
     {_dataMems_5_ext_R0_data[231:224]},
     {_dataMems_4_ext_R0_data[231:224]},
     {_dataMems_3_ext_R0_data[231:224]},
     {_dataMems_2_ext_R0_data[231:224]},
     {_dataMems_1_ext_R0_data[231:224]},
     {_dataMems_0_ext_R0_data[231:224]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_30 =
    {{_dataMems_7_ext_R0_data[239:232]},
     {_dataMems_6_ext_R0_data[239:232]},
     {_dataMems_5_ext_R0_data[239:232]},
     {_dataMems_4_ext_R0_data[239:232]},
     {_dataMems_3_ext_R0_data[239:232]},
     {_dataMems_2_ext_R0_data[239:232]},
     {_dataMems_1_ext_R0_data[239:232]},
     {_dataMems_0_ext_R0_data[239:232]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_31 =
    {{_dataMems_7_ext_R0_data[247:240]},
     {_dataMems_6_ext_R0_data[247:240]},
     {_dataMems_5_ext_R0_data[247:240]},
     {_dataMems_4_ext_R0_data[247:240]},
     {_dataMems_3_ext_R0_data[247:240]},
     {_dataMems_2_ext_R0_data[247:240]},
     {_dataMems_1_ext_R0_data[247:240]},
     {_dataMems_0_ext_R0_data[247:240]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_32 =
    {{_dataMems_7_ext_R0_data[255:248]},
     {_dataMems_6_ext_R0_data[255:248]},
     {_dataMems_5_ext_R0_data[255:248]},
     {_dataMems_4_ext_R0_data[255:248]},
     {_dataMems_3_ext_R0_data[255:248]},
     {_dataMems_2_ext_R0_data[255:248]},
     {_dataMems_1_ext_R0_data[255:248]},
     {_dataMems_0_ext_R0_data[255:248]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_33 =
    {{_dataMems_7_ext_R0_data[263:256]},
     {_dataMems_6_ext_R0_data[263:256]},
     {_dataMems_5_ext_R0_data[263:256]},
     {_dataMems_4_ext_R0_data[263:256]},
     {_dataMems_3_ext_R0_data[263:256]},
     {_dataMems_2_ext_R0_data[263:256]},
     {_dataMems_1_ext_R0_data[263:256]},
     {_dataMems_0_ext_R0_data[263:256]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_34 =
    {{_dataMems_7_ext_R0_data[271:264]},
     {_dataMems_6_ext_R0_data[271:264]},
     {_dataMems_5_ext_R0_data[271:264]},
     {_dataMems_4_ext_R0_data[271:264]},
     {_dataMems_3_ext_R0_data[271:264]},
     {_dataMems_2_ext_R0_data[271:264]},
     {_dataMems_1_ext_R0_data[271:264]},
     {_dataMems_0_ext_R0_data[271:264]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_35 =
    {{_dataMems_7_ext_R0_data[279:272]},
     {_dataMems_6_ext_R0_data[279:272]},
     {_dataMems_5_ext_R0_data[279:272]},
     {_dataMems_4_ext_R0_data[279:272]},
     {_dataMems_3_ext_R0_data[279:272]},
     {_dataMems_2_ext_R0_data[279:272]},
     {_dataMems_1_ext_R0_data[279:272]},
     {_dataMems_0_ext_R0_data[279:272]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_36 =
    {{_dataMems_7_ext_R0_data[287:280]},
     {_dataMems_6_ext_R0_data[287:280]},
     {_dataMems_5_ext_R0_data[287:280]},
     {_dataMems_4_ext_R0_data[287:280]},
     {_dataMems_3_ext_R0_data[287:280]},
     {_dataMems_2_ext_R0_data[287:280]},
     {_dataMems_1_ext_R0_data[287:280]},
     {_dataMems_0_ext_R0_data[287:280]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_37 =
    {{_dataMems_7_ext_R0_data[295:288]},
     {_dataMems_6_ext_R0_data[295:288]},
     {_dataMems_5_ext_R0_data[295:288]},
     {_dataMems_4_ext_R0_data[295:288]},
     {_dataMems_3_ext_R0_data[295:288]},
     {_dataMems_2_ext_R0_data[295:288]},
     {_dataMems_1_ext_R0_data[295:288]},
     {_dataMems_0_ext_R0_data[295:288]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_38 =
    {{_dataMems_7_ext_R0_data[303:296]},
     {_dataMems_6_ext_R0_data[303:296]},
     {_dataMems_5_ext_R0_data[303:296]},
     {_dataMems_4_ext_R0_data[303:296]},
     {_dataMems_3_ext_R0_data[303:296]},
     {_dataMems_2_ext_R0_data[303:296]},
     {_dataMems_1_ext_R0_data[303:296]},
     {_dataMems_0_ext_R0_data[303:296]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_39 =
    {{_dataMems_7_ext_R0_data[311:304]},
     {_dataMems_6_ext_R0_data[311:304]},
     {_dataMems_5_ext_R0_data[311:304]},
     {_dataMems_4_ext_R0_data[311:304]},
     {_dataMems_3_ext_R0_data[311:304]},
     {_dataMems_2_ext_R0_data[311:304]},
     {_dataMems_1_ext_R0_data[311:304]},
     {_dataMems_0_ext_R0_data[311:304]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_40 =
    {{_dataMems_7_ext_R0_data[319:312]},
     {_dataMems_6_ext_R0_data[319:312]},
     {_dataMems_5_ext_R0_data[319:312]},
     {_dataMems_4_ext_R0_data[319:312]},
     {_dataMems_3_ext_R0_data[319:312]},
     {_dataMems_2_ext_R0_data[319:312]},
     {_dataMems_1_ext_R0_data[319:312]},
     {_dataMems_0_ext_R0_data[319:312]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_41 =
    {{_dataMems_7_ext_R0_data[327:320]},
     {_dataMems_6_ext_R0_data[327:320]},
     {_dataMems_5_ext_R0_data[327:320]},
     {_dataMems_4_ext_R0_data[327:320]},
     {_dataMems_3_ext_R0_data[327:320]},
     {_dataMems_2_ext_R0_data[327:320]},
     {_dataMems_1_ext_R0_data[327:320]},
     {_dataMems_0_ext_R0_data[327:320]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_42 =
    {{_dataMems_7_ext_R0_data[335:328]},
     {_dataMems_6_ext_R0_data[335:328]},
     {_dataMems_5_ext_R0_data[335:328]},
     {_dataMems_4_ext_R0_data[335:328]},
     {_dataMems_3_ext_R0_data[335:328]},
     {_dataMems_2_ext_R0_data[335:328]},
     {_dataMems_1_ext_R0_data[335:328]},
     {_dataMems_0_ext_R0_data[335:328]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_43 =
    {{_dataMems_7_ext_R0_data[343:336]},
     {_dataMems_6_ext_R0_data[343:336]},
     {_dataMems_5_ext_R0_data[343:336]},
     {_dataMems_4_ext_R0_data[343:336]},
     {_dataMems_3_ext_R0_data[343:336]},
     {_dataMems_2_ext_R0_data[343:336]},
     {_dataMems_1_ext_R0_data[343:336]},
     {_dataMems_0_ext_R0_data[343:336]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_44 =
    {{_dataMems_7_ext_R0_data[351:344]},
     {_dataMems_6_ext_R0_data[351:344]},
     {_dataMems_5_ext_R0_data[351:344]},
     {_dataMems_4_ext_R0_data[351:344]},
     {_dataMems_3_ext_R0_data[351:344]},
     {_dataMems_2_ext_R0_data[351:344]},
     {_dataMems_1_ext_R0_data[351:344]},
     {_dataMems_0_ext_R0_data[351:344]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_45 =
    {{_dataMems_7_ext_R0_data[359:352]},
     {_dataMems_6_ext_R0_data[359:352]},
     {_dataMems_5_ext_R0_data[359:352]},
     {_dataMems_4_ext_R0_data[359:352]},
     {_dataMems_3_ext_R0_data[359:352]},
     {_dataMems_2_ext_R0_data[359:352]},
     {_dataMems_1_ext_R0_data[359:352]},
     {_dataMems_0_ext_R0_data[359:352]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_46 =
    {{_dataMems_7_ext_R0_data[367:360]},
     {_dataMems_6_ext_R0_data[367:360]},
     {_dataMems_5_ext_R0_data[367:360]},
     {_dataMems_4_ext_R0_data[367:360]},
     {_dataMems_3_ext_R0_data[367:360]},
     {_dataMems_2_ext_R0_data[367:360]},
     {_dataMems_1_ext_R0_data[367:360]},
     {_dataMems_0_ext_R0_data[367:360]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_47 =
    {{_dataMems_7_ext_R0_data[375:368]},
     {_dataMems_6_ext_R0_data[375:368]},
     {_dataMems_5_ext_R0_data[375:368]},
     {_dataMems_4_ext_R0_data[375:368]},
     {_dataMems_3_ext_R0_data[375:368]},
     {_dataMems_2_ext_R0_data[375:368]},
     {_dataMems_1_ext_R0_data[375:368]},
     {_dataMems_0_ext_R0_data[375:368]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_48 =
    {{_dataMems_7_ext_R0_data[383:376]},
     {_dataMems_6_ext_R0_data[383:376]},
     {_dataMems_5_ext_R0_data[383:376]},
     {_dataMems_4_ext_R0_data[383:376]},
     {_dataMems_3_ext_R0_data[383:376]},
     {_dataMems_2_ext_R0_data[383:376]},
     {_dataMems_1_ext_R0_data[383:376]},
     {_dataMems_0_ext_R0_data[383:376]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_49 =
    {{_dataMems_7_ext_R0_data[391:384]},
     {_dataMems_6_ext_R0_data[391:384]},
     {_dataMems_5_ext_R0_data[391:384]},
     {_dataMems_4_ext_R0_data[391:384]},
     {_dataMems_3_ext_R0_data[391:384]},
     {_dataMems_2_ext_R0_data[391:384]},
     {_dataMems_1_ext_R0_data[391:384]},
     {_dataMems_0_ext_R0_data[391:384]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_50 =
    {{_dataMems_7_ext_R0_data[399:392]},
     {_dataMems_6_ext_R0_data[399:392]},
     {_dataMems_5_ext_R0_data[399:392]},
     {_dataMems_4_ext_R0_data[399:392]},
     {_dataMems_3_ext_R0_data[399:392]},
     {_dataMems_2_ext_R0_data[399:392]},
     {_dataMems_1_ext_R0_data[399:392]},
     {_dataMems_0_ext_R0_data[399:392]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_51 =
    {{_dataMems_7_ext_R0_data[407:400]},
     {_dataMems_6_ext_R0_data[407:400]},
     {_dataMems_5_ext_R0_data[407:400]},
     {_dataMems_4_ext_R0_data[407:400]},
     {_dataMems_3_ext_R0_data[407:400]},
     {_dataMems_2_ext_R0_data[407:400]},
     {_dataMems_1_ext_R0_data[407:400]},
     {_dataMems_0_ext_R0_data[407:400]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_52 =
    {{_dataMems_7_ext_R0_data[415:408]},
     {_dataMems_6_ext_R0_data[415:408]},
     {_dataMems_5_ext_R0_data[415:408]},
     {_dataMems_4_ext_R0_data[415:408]},
     {_dataMems_3_ext_R0_data[415:408]},
     {_dataMems_2_ext_R0_data[415:408]},
     {_dataMems_1_ext_R0_data[415:408]},
     {_dataMems_0_ext_R0_data[415:408]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_53 =
    {{_dataMems_7_ext_R0_data[423:416]},
     {_dataMems_6_ext_R0_data[423:416]},
     {_dataMems_5_ext_R0_data[423:416]},
     {_dataMems_4_ext_R0_data[423:416]},
     {_dataMems_3_ext_R0_data[423:416]},
     {_dataMems_2_ext_R0_data[423:416]},
     {_dataMems_1_ext_R0_data[423:416]},
     {_dataMems_0_ext_R0_data[423:416]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_54 =
    {{_dataMems_7_ext_R0_data[431:424]},
     {_dataMems_6_ext_R0_data[431:424]},
     {_dataMems_5_ext_R0_data[431:424]},
     {_dataMems_4_ext_R0_data[431:424]},
     {_dataMems_3_ext_R0_data[431:424]},
     {_dataMems_2_ext_R0_data[431:424]},
     {_dataMems_1_ext_R0_data[431:424]},
     {_dataMems_0_ext_R0_data[431:424]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_55 =
    {{_dataMems_7_ext_R0_data[439:432]},
     {_dataMems_6_ext_R0_data[439:432]},
     {_dataMems_5_ext_R0_data[439:432]},
     {_dataMems_4_ext_R0_data[439:432]},
     {_dataMems_3_ext_R0_data[439:432]},
     {_dataMems_2_ext_R0_data[439:432]},
     {_dataMems_1_ext_R0_data[439:432]},
     {_dataMems_0_ext_R0_data[439:432]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_56 =
    {{_dataMems_7_ext_R0_data[447:440]},
     {_dataMems_6_ext_R0_data[447:440]},
     {_dataMems_5_ext_R0_data[447:440]},
     {_dataMems_4_ext_R0_data[447:440]},
     {_dataMems_3_ext_R0_data[447:440]},
     {_dataMems_2_ext_R0_data[447:440]},
     {_dataMems_1_ext_R0_data[447:440]},
     {_dataMems_0_ext_R0_data[447:440]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_57 =
    {{_dataMems_7_ext_R0_data[455:448]},
     {_dataMems_6_ext_R0_data[455:448]},
     {_dataMems_5_ext_R0_data[455:448]},
     {_dataMems_4_ext_R0_data[455:448]},
     {_dataMems_3_ext_R0_data[455:448]},
     {_dataMems_2_ext_R0_data[455:448]},
     {_dataMems_1_ext_R0_data[455:448]},
     {_dataMems_0_ext_R0_data[455:448]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_58 =
    {{_dataMems_7_ext_R0_data[463:456]},
     {_dataMems_6_ext_R0_data[463:456]},
     {_dataMems_5_ext_R0_data[463:456]},
     {_dataMems_4_ext_R0_data[463:456]},
     {_dataMems_3_ext_R0_data[463:456]},
     {_dataMems_2_ext_R0_data[463:456]},
     {_dataMems_1_ext_R0_data[463:456]},
     {_dataMems_0_ext_R0_data[463:456]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_59 =
    {{_dataMems_7_ext_R0_data[471:464]},
     {_dataMems_6_ext_R0_data[471:464]},
     {_dataMems_5_ext_R0_data[471:464]},
     {_dataMems_4_ext_R0_data[471:464]},
     {_dataMems_3_ext_R0_data[471:464]},
     {_dataMems_2_ext_R0_data[471:464]},
     {_dataMems_1_ext_R0_data[471:464]},
     {_dataMems_0_ext_R0_data[471:464]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_60 =
    {{_dataMems_7_ext_R0_data[479:472]},
     {_dataMems_6_ext_R0_data[479:472]},
     {_dataMems_5_ext_R0_data[479:472]},
     {_dataMems_4_ext_R0_data[479:472]},
     {_dataMems_3_ext_R0_data[479:472]},
     {_dataMems_2_ext_R0_data[479:472]},
     {_dataMems_1_ext_R0_data[479:472]},
     {_dataMems_0_ext_R0_data[479:472]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_61 =
    {{_dataMems_7_ext_R0_data[487:480]},
     {_dataMems_6_ext_R0_data[487:480]},
     {_dataMems_5_ext_R0_data[487:480]},
     {_dataMems_4_ext_R0_data[487:480]},
     {_dataMems_3_ext_R0_data[487:480]},
     {_dataMems_2_ext_R0_data[487:480]},
     {_dataMems_1_ext_R0_data[487:480]},
     {_dataMems_0_ext_R0_data[487:480]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_62 =
    {{_dataMems_7_ext_R0_data[495:488]},
     {_dataMems_6_ext_R0_data[495:488]},
     {_dataMems_5_ext_R0_data[495:488]},
     {_dataMems_4_ext_R0_data[495:488]},
     {_dataMems_3_ext_R0_data[495:488]},
     {_dataMems_2_ext_R0_data[495:488]},
     {_dataMems_1_ext_R0_data[495:488]},
     {_dataMems_0_ext_R0_data[495:488]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_63 =
    {{_dataMems_7_ext_R0_data[503:496]},
     {_dataMems_6_ext_R0_data[503:496]},
     {_dataMems_5_ext_R0_data[503:496]},
     {_dataMems_4_ext_R0_data[503:496]},
     {_dataMems_3_ext_R0_data[503:496]},
     {_dataMems_2_ext_R0_data[503:496]},
     {_dataMems_1_ext_R0_data[503:496]},
     {_dataMems_0_ext_R0_data[503:496]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  wire [7:0][7:0] _GEN_64 =
    {{_dataMems_7_ext_R0_data[511:504]},
     {_dataMems_6_ext_R0_data[511:504]},
     {_dataMems_5_ext_R0_data[511:504]},
     {_dataMems_4_ext_R0_data[511:504]},
     {_dataMems_3_ext_R0_data[511:504]},
     {_dataMems_2_ext_R0_data[511:504]},
     {_dataMems_1_ext_R0_data[511:504]},
     {_dataMems_0_ext_R0_data[511:504]}};	// src/llc/scala/main/LlcDataArray.scala:40:48, :50:28
  always @(posedge clock)	// src/llc/scala/main/LlcDataArray.scala:30:7
    wayReg <= io_read_way;	// src/llc/scala/main/LlcDataArray.scala:45:23
  `ifdef ENABLE_INITIAL_REG_	// src/llc/scala/main/LlcDataArray.scala:30:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/llc/scala/main/LlcDataArray.scala:30:7
      `FIRRTL_BEFORE_INITIAL	// src/llc/scala/main/LlcDataArray.scala:30:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/llc/scala/main/LlcDataArray.scala:30:7
      automatic logic [31:0] _RANDOM[0:0];	// src/llc/scala/main/LlcDataArray.scala:30:7
      `ifdef INIT_RANDOM_PROLOG_	// src/llc/scala/main/LlcDataArray.scala:30:7
        `INIT_RANDOM_PROLOG_	// src/llc/scala/main/LlcDataArray.scala:30:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/llc/scala/main/LlcDataArray.scala:30:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/llc/scala/main/LlcDataArray.scala:30:7
        wayReg = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/llc/scala/main/LlcDataArray.scala:30:7, :45:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/llc/scala/main/LlcDataArray.scala:30:7
      `FIRRTL_AFTER_INITIAL	// src/llc/scala/main/LlcDataArray.scala:30:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  dataMems_512x512 dataMems_0_ext (	// src/llc/scala/main/LlcDataArray.scala:40:48
    .R0_addr (io_read_set),
    .R0_en   (io_read_enable),
    .R0_clk  (clock),
    .R0_data (_dataMems_0_ext_R0_data),
    .W0_addr (io_writeLine_set),
    .W0_en   (io_writeLine_enable & io_writeLine_way == 3'h0),	// src/llc/scala/main/LlcDataArray.scala:40:48, :72:25, :79:29, :92:{29,38}
    .W0_clk  (clock),
    .W0_data (_GEN_0),	// src/llc/scala/main/LlcDataArray.scala:40:48
    .W1_addr (io_write_set),
    .W1_en   (io_write_enable & io_write_way == 3'h0),	// src/llc/scala/main/LlcDataArray.scala:40:48, :57:25, :72:{25,34}
    .W1_clk  (clock),
    .W1_data (_GEN)	// src/llc/scala/main/LlcDataArray.scala:40:48
  );	// src/llc/scala/main/LlcDataArray.scala:40:48
  dataMems_512x512 dataMems_1_ext (	// src/llc/scala/main/LlcDataArray.scala:40:48
    .R0_addr (io_read_set),
    .R0_en   (io_read_enable),
    .R0_clk  (clock),
    .R0_data (_dataMems_1_ext_R0_data),
    .W0_addr (io_writeLine_set),
    .W0_en   (io_writeLine_enable & io_writeLine_way == 3'h1),	// src/llc/scala/main/LlcDataArray.scala:40:48, :72:25, :79:29, :92:{29,38}
    .W0_clk  (clock),
    .W0_data (_GEN_0),	// src/llc/scala/main/LlcDataArray.scala:40:48
    .W1_addr (io_write_set),
    .W1_en   (io_write_enable & io_write_way == 3'h1),	// src/llc/scala/main/LlcDataArray.scala:40:48, :57:25, :72:{25,34}
    .W1_clk  (clock),
    .W1_data (_GEN)	// src/llc/scala/main/LlcDataArray.scala:40:48
  );	// src/llc/scala/main/LlcDataArray.scala:40:48
  dataMems_512x512 dataMems_2_ext (	// src/llc/scala/main/LlcDataArray.scala:40:48
    .R0_addr (io_read_set),
    .R0_en   (io_read_enable),
    .R0_clk  (clock),
    .R0_data (_dataMems_2_ext_R0_data),
    .W0_addr (io_write_set),
    .W0_en   (io_write_enable & io_write_way == 3'h2),	// src/llc/scala/main/LlcDataArray.scala:40:48, :57:25, :72:{25,34}
    .W0_clk  (clock),
    .W0_data (_GEN),	// src/llc/scala/main/LlcDataArray.scala:40:48
    .W1_addr (io_writeLine_set),
    .W1_en   (io_writeLine_enable & io_writeLine_way == 3'h2),	// src/llc/scala/main/LlcDataArray.scala:40:48, :72:25, :79:29, :92:{29,38}
    .W1_clk  (clock),
    .W1_data (_GEN_0)	// src/llc/scala/main/LlcDataArray.scala:40:48
  );	// src/llc/scala/main/LlcDataArray.scala:40:48
  dataMems_512x512 dataMems_3_ext (	// src/llc/scala/main/LlcDataArray.scala:40:48
    .R0_addr (io_read_set),
    .R0_en   (io_read_enable),
    .R0_clk  (clock),
    .R0_data (_dataMems_3_ext_R0_data),
    .W0_addr (io_write_set),
    .W0_en   (io_write_enable & io_write_way == 3'h3),	// src/llc/scala/main/LlcDataArray.scala:40:48, :57:25, :72:{25,34}
    .W0_clk  (clock),
    .W0_data (_GEN),	// src/llc/scala/main/LlcDataArray.scala:40:48
    .W1_addr (io_writeLine_set),
    .W1_en   (io_writeLine_enable & io_writeLine_way == 3'h3),	// src/llc/scala/main/LlcDataArray.scala:40:48, :72:25, :79:29, :92:{29,38}
    .W1_clk  (clock),
    .W1_data (_GEN_0)	// src/llc/scala/main/LlcDataArray.scala:40:48
  );	// src/llc/scala/main/LlcDataArray.scala:40:48
  dataMems_512x512 dataMems_4_ext (	// src/llc/scala/main/LlcDataArray.scala:40:48
    .R0_addr (io_read_set),
    .R0_en   (io_read_enable),
    .R0_clk  (clock),
    .R0_data (_dataMems_4_ext_R0_data),
    .W0_addr (io_write_set),
    .W0_en   (io_write_enable & io_write_way == 3'h4),	// src/llc/scala/main/LlcDataArray.scala:40:48, :57:25, :72:{25,34}
    .W0_clk  (clock),
    .W0_data (_GEN),	// src/llc/scala/main/LlcDataArray.scala:40:48
    .W1_addr (io_writeLine_set),
    .W1_en   (io_writeLine_enable & io_writeLine_way == 3'h4),	// src/llc/scala/main/LlcDataArray.scala:40:48, :72:25, :79:29, :92:{29,38}
    .W1_clk  (clock),
    .W1_data (_GEN_0)	// src/llc/scala/main/LlcDataArray.scala:40:48
  );	// src/llc/scala/main/LlcDataArray.scala:40:48
  dataMems_512x512 dataMems_5_ext (	// src/llc/scala/main/LlcDataArray.scala:40:48
    .R0_addr (io_read_set),
    .R0_en   (io_read_enable),
    .R0_clk  (clock),
    .R0_data (_dataMems_5_ext_R0_data),
    .W0_addr (io_write_set),
    .W0_en   (io_write_enable & io_write_way == 3'h5),	// src/llc/scala/main/LlcDataArray.scala:40:48, :57:25, :72:{25,34}
    .W0_clk  (clock),
    .W0_data (_GEN),	// src/llc/scala/main/LlcDataArray.scala:40:48
    .W1_addr (io_writeLine_set),
    .W1_en   (io_writeLine_enable & io_writeLine_way == 3'h5),	// src/llc/scala/main/LlcDataArray.scala:40:48, :72:25, :79:29, :92:{29,38}
    .W1_clk  (clock),
    .W1_data (_GEN_0)	// src/llc/scala/main/LlcDataArray.scala:40:48
  );	// src/llc/scala/main/LlcDataArray.scala:40:48
  dataMems_512x512 dataMems_6_ext (	// src/llc/scala/main/LlcDataArray.scala:40:48
    .R0_addr (io_read_set),
    .R0_en   (io_read_enable),
    .R0_clk  (clock),
    .R0_data (_dataMems_6_ext_R0_data),
    .W0_addr (io_write_set),
    .W0_en   (io_write_enable & io_write_way == 3'h6),	// src/llc/scala/main/LlcDataArray.scala:40:48, :57:25, :72:{25,34}
    .W0_clk  (clock),
    .W0_data (_GEN),	// src/llc/scala/main/LlcDataArray.scala:40:48
    .W1_addr (io_writeLine_set),
    .W1_en   (io_writeLine_enable & io_writeLine_way == 3'h6),	// src/llc/scala/main/LlcDataArray.scala:40:48, :72:25, :79:29, :92:{29,38}
    .W1_clk  (clock),
    .W1_data (_GEN_0)	// src/llc/scala/main/LlcDataArray.scala:40:48
  );	// src/llc/scala/main/LlcDataArray.scala:40:48
  dataMems_512x512 dataMems_7_ext (	// src/llc/scala/main/LlcDataArray.scala:40:48
    .R0_addr (io_read_set),
    .R0_en   (io_read_enable),
    .R0_clk  (clock),
    .R0_data (_dataMems_7_ext_R0_data),
    .W0_addr (io_write_set),
    .W0_en   (io_write_enable & (&io_write_way)),	// src/llc/scala/main/LlcDataArray.scala:40:48, :57:25, :72:{25,34}
    .W0_clk  (clock),
    .W0_data (_GEN),	// src/llc/scala/main/LlcDataArray.scala:40:48
    .W1_addr (io_writeLine_set),
    .W1_en   (io_writeLine_enable & (&io_writeLine_way)),	// src/llc/scala/main/LlcDataArray.scala:40:48, :79:29, :92:{29,38}
    .W1_clk  (clock),
    .W1_data (_GEN_0)	// src/llc/scala/main/LlcDataArray.scala:40:48
  );	// src/llc/scala/main/LlcDataArray.scala:40:48
  assign io_readResp_data_0 =
    {_GEN_32[wayReg],
     _GEN_31[wayReg],
     _GEN_30[wayReg],
     _GEN_29[wayReg],
     _GEN_28[wayReg],
     _GEN_27[wayReg],
     _GEN_26[wayReg],
     _GEN_25[wayReg],
     _GEN_24[wayReg],
     _GEN_23[wayReg],
     _GEN_22[wayReg],
     _GEN_21[wayReg],
     _GEN_20[wayReg],
     _GEN_19[wayReg],
     _GEN_18[wayReg],
     _GEN_17[wayReg],
     _GEN_16[wayReg],
     _GEN_15[wayReg],
     _GEN_14[wayReg],
     _GEN_13[wayReg],
     _GEN_12[wayReg],
     _GEN_11[wayReg],
     _GEN_10[wayReg],
     _GEN_9[wayReg],
     _GEN_8[wayReg],
     _GEN_7[wayReg],
     _GEN_6[wayReg],
     _GEN_5[wayReg],
     _GEN_4[wayReg],
     _GEN_3[wayReg],
     _GEN_2[wayReg],
     _GEN_1[wayReg]};	// src/llc/scala/main/LlcDataArray.scala:30:7, :45:23, :50:28, :53:41
  assign io_readResp_data_1 =
    {_GEN_64[wayReg],
     _GEN_63[wayReg],
     _GEN_62[wayReg],
     _GEN_61[wayReg],
     _GEN_60[wayReg],
     _GEN_59[wayReg],
     _GEN_58[wayReg],
     _GEN_57[wayReg],
     _GEN_56[wayReg],
     _GEN_55[wayReg],
     _GEN_54[wayReg],
     _GEN_53[wayReg],
     _GEN_52[wayReg],
     _GEN_51[wayReg],
     _GEN_50[wayReg],
     _GEN_49[wayReg],
     _GEN_48[wayReg],
     _GEN_47[wayReg],
     _GEN_46[wayReg],
     _GEN_45[wayReg],
     _GEN_44[wayReg],
     _GEN_43[wayReg],
     _GEN_42[wayReg],
     _GEN_41[wayReg],
     _GEN_40[wayReg],
     _GEN_39[wayReg],
     _GEN_38[wayReg],
     _GEN_37[wayReg],
     _GEN_36[wayReg],
     _GEN_35[wayReg],
     _GEN_34[wayReg],
     _GEN_33[wayReg]};	// src/llc/scala/main/LlcDataArray.scala:30:7, :45:23, :50:28, :53:41
endmodule

