// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LlcPipeline(	// src/llc/scala/main/LlcPipeline.scala:27:7
  input          clock,	// src/llc/scala/main/LlcPipeline.scala:27:7
                 reset,	// src/llc/scala/main/LlcPipeline.scala:27:7
                 io_reqIn_valid,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output         io_reqIn_ready,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input          io_reqIn_payload_isWrite,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input  [31:0]  io_reqIn_payload_address,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input  [3:0]   io_reqIn_payload_id,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input  [255:0] io_reqIn_payload_writeData,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input  [31:0]  io_reqIn_payload_writeStrb,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input          io_reqIn_payload_beatIdx,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output         io_respOut_valid,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_respOut_payload_isWrite,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output [255:0] io_respOut_payload_data_0,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_respOut_payload_data_1,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output         io_wbReq_valid,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output [31:0]  io_wbReq_bits_address,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output [255:0] io_wbReq_bits_data_0,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_wbReq_bits_data_1,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input          io_wbDone,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output         io_refillReq_valid,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output [31:0]  io_refillReq_bits_address,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output [3:0]   io_refillReq_bits_id,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input          io_refillReady,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_refillData_valid,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input  [255:0] io_refillData_bits_data,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input          io_refillData_bits_last,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output         io_perfEvents_readHit,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_perfEvents_readMiss,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_perfEvents_writeHit,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_perfEvents_writeMiss,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_perfEvents_dirtyEvict,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_perfEvents_cleanEvict,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_perfEvents_mshrFullStall,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_perfEvents_refillComplete,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input          io_flushStart,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_flushIsInvalidate,	// src/llc/scala/main/LlcPipeline.scala:28:14
  output         io_flushBusy,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_flushDone,	// src/llc/scala/main/LlcPipeline.scala:28:14
  input          io_wbBufEmpty,	// src/llc/scala/main/LlcPipeline.scala:28:14
                 io_wbBufEnqReady	// src/llc/scala/main/LlcPipeline.scala:28:14
);

  reg  [3:0]       flushState;	// src/llc/scala/main/LlcPipeline.scala:392:27
  wire             s2Stall;	// src/llc/scala/main/LlcPipeline.scala:292:{22,32}
  wire             io_reqIn_ready_0;	// src/llc/scala/main/LlcPipeline.scala:194:{36,48,64}
  wire             _mshr_io_allocReady;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_wbReq_valid;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [31:0]      _mshr_io_wbReq_bits_address;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [255:0]     _mshr_io_wbReq_bits_data_0;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [255:0]     _mshr_io_wbReq_bits_data_1;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_complete_valid;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [8:0]       _mshr_io_complete_bits_set;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [2:0]       _mshr_io_complete_bits_way;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [16:0]      _mshr_io_complete_bits_tag;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [255:0]     _mshr_io_complete_bits_data_0;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [255:0]     _mshr_io_complete_bits_data_1;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_complete_bits_dirty;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_complete_bits_reqType;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_complete_bits_earlyRespDone;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_earlyResp_valid;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [255:0]     _mshr_io_earlyResp_bits_data;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_earlyResp_bits_beatIdx;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_allIdle;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire             _mshr_io_addrMatch_hit;	// src/llc/scala/main/LlcPipeline.scala:75:28
  wire [2:0]       _wayPartition_io_victimWay;	// src/llc/scala/main/LlcPipeline.scala:74:28
  wire [2:0]       _plru_io_queryResp_victimWay;	// src/llc/scala/main/LlcPipeline.scala:73:28
  wire [255:0]     _dataArray_io_readResp_data_0;	// src/llc/scala/main/LlcPipeline.scala:72:28
  wire [255:0]     _dataArray_io_readResp_data_1;	// src/llc/scala/main/LlcPipeline.scala:72:28
  wire [16:0]      _tagArray_io_readResp_tags_0;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire [16:0]      _tagArray_io_readResp_tags_1;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire [16:0]      _tagArray_io_readResp_tags_2;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire [16:0]      _tagArray_io_readResp_tags_3;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire [16:0]      _tagArray_io_readResp_tags_4;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire [16:0]      _tagArray_io_readResp_tags_5;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire [16:0]      _tagArray_io_readResp_tags_6;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire [16:0]      _tagArray_io_readResp_tags_7;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_valids_0;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_valids_1;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_valids_2;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_valids_3;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_valids_4;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_valids_5;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_valids_6;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_valids_7;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_dirtys_0;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_dirtys_1;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_dirtys_2;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_dirtys_3;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_dirtys_4;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_dirtys_5;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_dirtys_6;	// src/llc/scala/main/LlcPipeline.scala:71:28
  wire             _tagArray_io_readResp_dirtys_7;	// src/llc/scala/main/LlcPipeline.scala:71:28
  reg              respValidReg;	// src/llc/scala/main/LlcPipeline.scala:93:29
  reg              respDataReg_isWrite;	// src/llc/scala/main/LlcPipeline.scala:94:25
  reg  [255:0]     respDataReg_data_0;	// src/llc/scala/main/LlcPipeline.scala:94:25
  reg  [255:0]     respDataReg_data_1;	// src/llc/scala/main/LlcPipeline.scala:94:25
  reg              s1Valid;	// src/llc/scala/main/LlcPipeline.scala:115:24
  reg              s2Valid;	// src/llc/scala/main/LlcPipeline.scala:116:24
  reg              replayValid;	// src/llc/scala/main/LlcPipeline.scala:119:28
  reg              replayReq_isWrite;	// src/llc/scala/main/LlcPipeline.scala:120:24
  reg  [31:0]      replayReq_address;	// src/llc/scala/main/LlcPipeline.scala:120:24
  reg  [3:0]       replayReq_id;	// src/llc/scala/main/LlcPipeline.scala:120:24
  reg  [255:0]     replayReq_writeData;	// src/llc/scala/main/LlcPipeline.scala:120:24
  reg  [31:0]      replayReq_writeStrb;	// src/llc/scala/main/LlcPipeline.scala:120:24
  reg              replayReq_beatIdx;	// src/llc/scala/main/LlcPipeline.scala:120:24
  wire             _pipelineStall_T = _mshr_io_complete_valid | s2Stall;	// src/llc/scala/main/LlcPipeline.scala:75:28, :125:34, :292:{22,32}
  wire             s0Fire =
    (io_reqIn_valid & io_reqIn_ready_0 | replayValid) & ~_pipelineStall_T & ~s1Valid
    & ~(|flushState);	// src/llc/scala/main/LlcPipeline.scala:115:24, :119:28, :125:34, :180:{21,39}, :184:{31,47,65,77,80}, :194:{36,48,64}, :392:27, :404:29, src/utils/Stream/Stream.scala:43:26
  wire [31:0]      s0Req_address =
    replayValid ? replayReq_address : io_reqIn_payload_address;	// src/llc/scala/main/LlcPipeline.scala:119:28, :120:24, :185:19
  assign io_reqIn_ready_0 = ~_pipelineStall_T & ~s1Valid & ~replayValid & ~(|flushState);	// src/llc/scala/main/LlcPipeline.scala:115:24, :119:28, :125:34, :180:{21,39,51}, :184:80, :194:{36,48,64}, :392:27, :404:29
  reg              s1Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:203:18
  reg  [31:0]      s1Req_address;	// src/llc/scala/main/LlcPipeline.scala:203:18
  reg  [3:0]       s1Req_id;	// src/llc/scala/main/LlcPipeline.scala:203:18
  reg  [255:0]     s1Req_writeData;	// src/llc/scala/main/LlcPipeline.scala:203:18
  reg  [31:0]      s1Req_writeStrb;	// src/llc/scala/main/LlcPipeline.scala:203:18
  reg              s1Req_beatIdx;	// src/llc/scala/main/LlcPipeline.scala:203:18
  reg  [8:0]       s1Set;	// src/llc/scala/main/LlcPipeline.scala:204:18
  reg  [16:0]      s1Tag;	// src/llc/scala/main/LlcPipeline.scala:205:18
  wire             hitVec_1 =
    _tagArray_io_readResp_valids_1 & _tagArray_io_readResp_tags_1 == s1Tag;	// src/llc/scala/main/LlcPipeline.scala:71:28, :205:18, :222:{65,79}
  wire             hitVec_2 =
    _tagArray_io_readResp_valids_2 & _tagArray_io_readResp_tags_2 == s1Tag;	// src/llc/scala/main/LlcPipeline.scala:71:28, :205:18, :222:{65,79}
  wire             hitVec_3 =
    _tagArray_io_readResp_valids_3 & _tagArray_io_readResp_tags_3 == s1Tag;	// src/llc/scala/main/LlcPipeline.scala:71:28, :205:18, :222:{65,79}
  wire             hitVec_4 =
    _tagArray_io_readResp_valids_4 & _tagArray_io_readResp_tags_4 == s1Tag;	// src/llc/scala/main/LlcPipeline.scala:71:28, :205:18, :222:{65,79}
  wire             hitVec_5 =
    _tagArray_io_readResp_valids_5 & _tagArray_io_readResp_tags_5 == s1Tag;	// src/llc/scala/main/LlcPipeline.scala:71:28, :205:18, :222:{65,79}
  wire             hitVec_6 =
    _tagArray_io_readResp_valids_6 & _tagArray_io_readResp_tags_6 == s1Tag;	// src/llc/scala/main/LlcPipeline.scala:71:28, :205:18, :222:{65,79}
  wire             hitVec_7 =
    _tagArray_io_readResp_valids_7 & _tagArray_io_readResp_tags_7 == s1Tag;	// src/llc/scala/main/LlcPipeline.scala:71:28, :205:18, :222:{65,79}
  wire [7:0]       _hitWay_T =
    {hitVec_7,
     hitVec_6,
     hitVec_5,
     hitVec_4,
     hitVec_3,
     hitVec_2,
     hitVec_1,
     _tagArray_io_readResp_valids_0 & _tagArray_io_readResp_tags_0 == s1Tag};	// src/llc/scala/main/LlcPipeline.scala:71:28, :205:18, :222:{65,79}, :223:24
  wire [2:0]       _hitWay_T_2 =
    {hitVec_7, hitVec_6, hitVec_5} | {hitVec_3, hitVec_2, hitVec_1};	// src/llc/scala/main/LlcPipeline.scala:222:65, src/main/scala/chisel3/util/OneHot.scala:30:18, :31:18, :32:28
  wire [2:0]       hitWay =
    {|{hitVec_7, hitVec_6, hitVec_5, hitVec_4},
     |(_hitWay_T_2[2:1]),
     _hitWay_T_2[2] | _hitWay_T_2[0]};	// src/llc/scala/main/LlcPipeline.scala:222:65, src/main/scala/chisel3/util/OneHot.scala:30:18, :31:18, :32:{10,14,28}
  wire             _GEN = s1Valid & ~_pipelineStall_T;	// src/llc/scala/main/LlcPipeline.scala:115:24, :125:34, :180:21, :240:16
  reg              s2Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:247:25
  reg  [31:0]      s2Req_address;	// src/llc/scala/main/LlcPipeline.scala:247:25
  reg  [3:0]       s2Req_id;	// src/llc/scala/main/LlcPipeline.scala:247:25
  reg  [255:0]     s2Req_writeData;	// src/llc/scala/main/LlcPipeline.scala:247:25
  reg  [31:0]      s2Req_writeStrb;	// src/llc/scala/main/LlcPipeline.scala:247:25
  reg              s2Req_beatIdx;	// src/llc/scala/main/LlcPipeline.scala:247:25
  reg  [8:0]       s2Set;	// src/llc/scala/main/LlcPipeline.scala:248:25
  reg  [16:0]      s2Tag;	// src/llc/scala/main/LlcPipeline.scala:249:25
  reg              s2Hit;	// src/llc/scala/main/LlcPipeline.scala:250:29
  reg  [2:0]       s2HitWay;	// src/llc/scala/main/LlcPipeline.scala:251:25
  reg  [2:0]       s2VictimWay;	// src/llc/scala/main/LlcPipeline.scala:252:25
  reg              s2VictimValid;	// src/llc/scala/main/LlcPipeline.scala:253:26
  reg              s2VictimDirty;	// src/llc/scala/main/LlcPipeline.scala:254:26
  reg  [16:0]      s2VictimTag;	// src/llc/scala/main/LlcPipeline.scala:255:25
  wire [31:0]      mshr_io_addrMatch_query = {s2Req_address[31:6], 6'h0};	// src/llc/scala/main/LlcPipeline.scala:247:25, :285:44
  wire             s2Miss = s2Valid & ~s2Hit;	// src/llc/scala/main/LlcPipeline.scala:116:24, :250:29, :289:{32,35}
  wire             s2MshrFull = s2Miss & ~_mshr_io_allocReady & ~_mshr_io_addrMatch_hit;	// src/llc/scala/main/LlcPipeline.scala:75:28, :289:32, :291:{31,34,54,57}
  assign s2Stall = s2Valid & ~s2Hit & (s2MshrFull | s2Miss & _mshr_io_addrMatch_hit);	// src/llc/scala/main/LlcPipeline.scala:75:28, :116:24, :250:29, :289:{32,35}, :290:31, :291:{31,54}, :292:{22,32,47}
  wire             _hitFire_T = s2Valid & s2Hit;	// src/llc/scala/main/LlcPipeline.scala:116:24, :250:29, :295:16
  wire             _GEN_0 = _hitFire_T & ~_mshr_io_complete_valid;	// src/llc/scala/main/LlcPipeline.scala:75:28, :295:{16,25,28}
  wire             dataArray_io_write_enable = _GEN_0 & s2Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:146:32, :247:25, :295:{25,56}, :296:25
  wire             _GEN_1 = _GEN_0 & s2Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:147:32, :247:25, :295:{25,56}, :296:25, :299:34
  wire [8:0]       dataArray_io_write_set = _GEN_1 ? s2Set : 9'h0;	// src/llc/scala/main/LlcPipeline.scala:147:32, :248:25, :295:56, :296:25, :299:34
  wire [2:0]       dataArray_io_write_way = _GEN_1 ? s2HitWay : 3'h0;	// src/llc/scala/main/LlcPipeline.scala:147:32, :148:32, :251:25, :295:56, :296:25, :299:34, :300:34
  wire             allocFire =
    s2Valid & ~s2Hit & ~_mshr_io_addrMatch_hit & _mshr_io_allocReady
    & ~_mshr_io_complete_valid;	// src/llc/scala/main/LlcPipeline.scala:75:28, :116:24, :250:29, :289:35, :291:57, :295:28, :330:{27,37,53,75}
  wire             _GEN_2 = _mshr_io_complete_valid | dataArray_io_write_enable;	// src/llc/scala/main/LlcPipeline.scala:75:28, :146:32, :295:56, :296:25, :349:24, :357:30
  reg              flushInv;	// src/llc/scala/main/LlcPipeline.scala:393:27
  reg  [8:0]       curSet;	// src/llc/scala/main/LlcPipeline.scala:394:27
  reg  [2:0]       curWay;	// src/llc/scala/main/LlcPipeline.scala:395:27
  reg  [16:0]      latchedTags_0;	// src/llc/scala/main/LlcPipeline.scala:398:26
  reg  [16:0]      latchedTags_1;	// src/llc/scala/main/LlcPipeline.scala:398:26
  reg  [16:0]      latchedTags_2;	// src/llc/scala/main/LlcPipeline.scala:398:26
  reg  [16:0]      latchedTags_3;	// src/llc/scala/main/LlcPipeline.scala:398:26
  reg  [16:0]      latchedTags_4;	// src/llc/scala/main/LlcPipeline.scala:398:26
  reg  [16:0]      latchedTags_5;	// src/llc/scala/main/LlcPipeline.scala:398:26
  reg  [16:0]      latchedTags_6;	// src/llc/scala/main/LlcPipeline.scala:398:26
  reg  [16:0]      latchedTags_7;	// src/llc/scala/main/LlcPipeline.scala:398:26
  reg              latchedValids_0;	// src/llc/scala/main/LlcPipeline.scala:399:26
  reg              latchedValids_1;	// src/llc/scala/main/LlcPipeline.scala:399:26
  reg              latchedValids_2;	// src/llc/scala/main/LlcPipeline.scala:399:26
  reg              latchedValids_3;	// src/llc/scala/main/LlcPipeline.scala:399:26
  reg              latchedValids_4;	// src/llc/scala/main/LlcPipeline.scala:399:26
  reg              latchedValids_5;	// src/llc/scala/main/LlcPipeline.scala:399:26
  reg              latchedValids_6;	// src/llc/scala/main/LlcPipeline.scala:399:26
  reg              latchedValids_7;	// src/llc/scala/main/LlcPipeline.scala:399:26
  reg              latchedDirtys_0;	// src/llc/scala/main/LlcPipeline.scala:400:26
  reg              latchedDirtys_1;	// src/llc/scala/main/LlcPipeline.scala:400:26
  reg              latchedDirtys_2;	// src/llc/scala/main/LlcPipeline.scala:400:26
  reg              latchedDirtys_3;	// src/llc/scala/main/LlcPipeline.scala:400:26
  reg              latchedDirtys_4;	// src/llc/scala/main/LlcPipeline.scala:400:26
  reg              latchedDirtys_5;	// src/llc/scala/main/LlcPipeline.scala:400:26
  reg              latchedDirtys_6;	// src/llc/scala/main/LlcPipeline.scala:400:26
  reg              latchedDirtys_7;	// src/llc/scala/main/LlcPipeline.scala:400:26
  reg  [255:0]     flushLineData_0;	// src/llc/scala/main/LlcPipeline.scala:402:26
  reg  [255:0]     flushLineData_1;	// src/llc/scala/main/LlcPipeline.scala:402:26
  wire             _GEN_3 = flushState == 4'h0;	// src/llc/scala/main/LlcPipeline.scala:174:38, :392:27, :418:22
  wire             _GEN_4 = flushState == 4'h1;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :424:20
  wire             _GEN_5 = flushState == 4'h2;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :428:40
  wire             _GEN_6 = _GEN_3 | _GEN_4;	// src/llc/scala/main/LlcPipeline.scala:197:16, :418:22
  wire             _GEN_7 = flushState == 4'h3;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :433:18
  wire             _GEN_8 = flushState == 4'h4;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :440:18
  wire             _GEN_9 = flushState == 4'h5;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :445:20
  wire             _GEN_10 = _GEN_3 | _GEN_4 | _GEN_5 | _GEN_7 | _GEN_8;	// src/llc/scala/main/LlcPipeline.scala:240:35, :418:22
  wire             _GEN_11 = _GEN_10 | ~_GEN_9;	// src/llc/scala/main/LlcPipeline.scala:240:35, :418:22
  wire             _GEN_12 = flushState == 4'h6;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :458:18
  wire             _GEN_13 = flushState == 4'h7;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :463:18
  wire             _GEN_14 =
    _GEN_3 | _GEN_4 | _GEN_5 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_12;	// src/llc/scala/main/LlcPipeline.scala:412:21, :418:22
  wire [7:0][16:0] _GEN_15 =
    {{latchedTags_7},
     {latchedTags_6},
     {latchedTags_5},
     {latchedTags_4},
     {latchedTags_3},
     {latchedTags_2},
     {latchedTags_1},
     {latchedTags_0}};	// src/llc/scala/main/LlcPipeline.scala:398:26, :467:35
  wire [16:0]      _GEN_16 = _GEN_15[curWay];	// src/llc/scala/main/LlcPipeline.scala:395:27, :467:35
  wire             _GEN_17 = _GEN_14 | ~_GEN_13;	// src/llc/scala/main/LlcPipeline.scala:412:21, :418:22
  wire             _GEN_18 = flushState == 4'h8;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :448:20
  wire             _GEN_19 =
    _GEN_3 | _GEN_4 | _GEN_5 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_12 | _GEN_13;	// src/llc/scala/main/LlcPipeline.scala:349:24, :418:22
  wire             _GEN_20 = _GEN_19 | ~_GEN_18;	// src/llc/scala/main/LlcPipeline.scala:349:24, :418:22
  wire             _hitFire_T_2 = _hitFire_T & ~_mshr_io_complete_valid;	// src/llc/scala/main/LlcPipeline.scala:75:28, :295:{16,28}, :513:34
  wire             _io_perfEvents_cleanEvict_T = allocFire & s2VictimValid;	// src/llc/scala/main/LlcPipeline.scala:253:26, :330:{27,37,53,75}, :520:45
  always @(posedge clock) begin	// src/llc/scala/main/LlcPipeline.scala:27:7
    automatic logic _GEN_21;	// src/llc/scala/main/LlcPipeline.scala:272:23
    automatic logic _GEN_22 =
      _mshr_io_complete_valid & ~_mshr_io_complete_bits_earlyRespDone;	// src/llc/scala/main/LlcPipeline.scala:75:28, :295:56, :349:24, :371:{10,44}, :373:27
    _GEN_21 = _mshr_io_complete_valid & s1Valid;	// src/llc/scala/main/LlcPipeline.scala:75:28, :115:24, :272:23
    if (reset) begin	// src/llc/scala/main/LlcPipeline.scala:27:7
      respValidReg <= 1'h0;	// src/llc/scala/main/LlcPipeline.scala:93:29
      s1Valid <= 1'h0;	// src/llc/scala/main/LlcPipeline.scala:93:29, :115:24
      s2Valid <= 1'h0;	// src/llc/scala/main/LlcPipeline.scala:93:29, :116:24
      replayValid <= 1'h0;	// src/llc/scala/main/LlcPipeline.scala:93:29, :119:28
      s2Hit <= 1'h0;	// src/llc/scala/main/LlcPipeline.scala:93:29, :250:29
      flushState <= 4'h0;	// src/llc/scala/main/LlcPipeline.scala:174:38, :392:27
      flushInv <= 1'h0;	// src/llc/scala/main/LlcPipeline.scala:93:29, :393:27
      curSet <= 9'h0;	// src/llc/scala/main/LlcPipeline.scala:394:27
      curWay <= 3'h0;	// src/llc/scala/main/LlcPipeline.scala:395:27
    end
    else begin	// src/llc/scala/main/LlcPipeline.scala:27:7
      automatic logic [7:0]       _GEN_23;	// src/llc/scala/main/LlcPipeline.scala:443:42
      automatic logic             _GEN_24;	// src/llc/scala/main/LlcPipeline.scala:443:42
      automatic logic [7:0]       _GEN_25;	// src/llc/scala/main/LlcPipeline.scala:443:42
      automatic logic [15:0][3:0] _GEN_26;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :420:27, :428:27, :433:18, :440:18, :444:20, :458:18, :463:18, :469:30, :480:18, :483:41, :499:27, :502:18
      _GEN_23 =
        {{latchedValids_7},
         {latchedValids_6},
         {latchedValids_5},
         {latchedValids_4},
         {latchedValids_3},
         {latchedValids_2},
         {latchedValids_1},
         {latchedValids_0}};	// src/llc/scala/main/LlcPipeline.scala:399:26, :443:42
      _GEN_24 = _GEN_23[curWay];	// src/llc/scala/main/LlcPipeline.scala:395:27, :443:42
      respValidReg <=
        _mshr_io_complete_valid & ~_mshr_io_complete_bits_earlyRespDone | _GEN_0
        | _mshr_io_earlyResp_valid;	// src/llc/scala/main/LlcPipeline.scala:75:28, :93:29, :97:25, :103:39, :104:25, :295:{25,56}, :315:22, :349:24, :371:{10,44}
      s1Valid <= ~(_GEN_21 | _GEN) & (s0Fire | s1Valid);	// src/llc/scala/main/LlcPipeline.scala:115:24, :184:{47,65,77}, :207:16, :208:13, :240:16, :257:35, :268:19, :272:{23,35}, :275:17
      s2Valid <= ~(allocFire | _GEN_0) & (_GEN | s2Valid);	// src/llc/scala/main/LlcPipeline.scala:116:24, :240:16, :257:35, :258:19, :295:{25,56}, :326:13, :330:{27,37,53,75}, :344:19, :345:13
      replayValid <=
        _GEN_21 | ~(replayValid & ~_pipelineStall_T & ~s1Valid) & replayValid;	// src/llc/scala/main/LlcPipeline.scala:115:24, :119:28, :125:34, :180:{21,39}, :190:{20,38,51}, :191:17, :272:{23,35}, :273:17
      if (_GEN)	// src/llc/scala/main/LlcPipeline.scala:240:16
        s2Hit <= |_hitWay_T;	// src/llc/scala/main/LlcPipeline.scala:223:{24,31}, :250:29
      _GEN_25 =
        {{latchedDirtys_7},
         {latchedDirtys_6},
         {latchedDirtys_5},
         {latchedDirtys_4},
         {latchedDirtys_3},
         {latchedDirtys_2},
         {latchedDirtys_1},
         {latchedDirtys_0}};	// src/llc/scala/main/LlcPipeline.scala:400:26, :443:42
      _GEN_26 =
        {{flushState},
         {flushState},
         {flushState},
         {flushState},
         {4'h0},
         {io_wbBufEmpty ? 4'hB : flushState},
         {(&curWay) ? {&curSet, 3'h2} : 4'h4},
         {4'h9},
         {io_wbBufEnqReady ? 4'h8 : flushState},
         {4'h7},
         {4'h6},
         {_GEN_24 & _GEN_25[curWay] ? 4'h5 : {3'h4, ~(flushInv & _GEN_24)}},
         {4'h4},
         {4'h3},
         {~s1Valid & ~s2Valid & ~replayValid & _mshr_io_allIdle ? 4'h2 : flushState},
         {io_flushStart ? 4'h1 : flushState}};	// src/llc/scala/main/LlcPipeline.scala:75:28, :115:24, :116:24, :119:28, :174:38, :180:{39,51}, :392:27, :393:27, :394:27, :395:27, :408:{32,35,44,60}, :418:22, :420:27, :424:20, :428:{27,40}, :433:18, :440:18, :443:42, :444:20, :445:20, :446:{27,53}, :448:20, :451:20, :458:18, :463:18, :469:30, :470:20, :480:18, :483:{19,41}, :485:{21,43}, :486:22, :489:22, :494:20, :499:{27,40}, :502:18
      flushState <= _GEN_26[flushState];	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :420:27, :428:27, :433:18, :440:18, :444:20, :458:18, :463:18, :469:30, :480:18, :483:41, :499:27, :502:18
      if (_GEN_3 & io_flushStart)	// src/llc/scala/main/LlcPipeline.scala:393:27, :418:22, :420:27, :421:20
        flushInv <= io_flushIsInvalidate;	// src/llc/scala/main/LlcPipeline.scala:393:27
      if (_GEN_3) begin	// src/llc/scala/main/LlcPipeline.scala:418:22
        if (io_flushStart) begin	// src/llc/scala/main/LlcPipeline.scala:28:14
          curSet <= 9'h0;	// src/llc/scala/main/LlcPipeline.scala:394:27
          curWay <= 3'h0;	// src/llc/scala/main/LlcPipeline.scala:395:27
        end
      end
      else begin	// src/llc/scala/main/LlcPipeline.scala:418:22
        automatic logic _GEN_27;	// src/llc/scala/main/LlcPipeline.scala:418:22
        automatic logic _GEN_28 =
          _GEN_4 | _GEN_5 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_12 | _GEN_13 | _GEN_18;	// src/llc/scala/main/LlcPipeline.scala:394:27, :418:22
        _GEN_27 = flushState == 4'h9;	// src/llc/scala/main/LlcPipeline.scala:392:27, :418:22, :451:20
        if (_GEN_28 | ~(_GEN_27 & (&curWay)) | (&curSet)) begin	// src/llc/scala/main/LlcPipeline.scala:394:27, :395:27, :418:22, :483:{19,41}, :485:{21,43}
        end
        else	// src/llc/scala/main/LlcPipeline.scala:394:27, :418:22, :483:41, :485:43
          curSet <= curSet + 9'h1;	// src/llc/scala/main/LlcPipeline.scala:394:27, :488:32
        if (_GEN_28 | ~_GEN_27) begin	// src/llc/scala/main/LlcPipeline.scala:394:27, :395:27, :418:22
        end
        else	// src/llc/scala/main/LlcPipeline.scala:395:27, :418:22
          curWay <= (&curWay) ? 3'h0 : curWay + 3'h1;	// src/llc/scala/main/LlcPipeline.scala:395:27, :424:20, :483:{19,41}, :484:16, :493:{20,30}
      end
    end
    respDataReg_isWrite <=
      _GEN_22
        ? _mshr_io_complete_bits_reqType
        : _GEN_0 ? s2Req_isWrite : ~_mshr_io_earlyResp_valid & respDataReg_isWrite;	// src/llc/scala/main/LlcPipeline.scala:75:28, :94:25, :103:39, :105:25, :247:25, :295:{25,56}, :316:25, :349:24, :371:44, :373:27
    if (_GEN_22) begin	// src/llc/scala/main/LlcPipeline.scala:295:56, :349:24, :371:44, :373:27
      respDataReg_data_0 <= _mshr_io_complete_bits_data_0;	// src/llc/scala/main/LlcPipeline.scala:75:28, :94:25
      respDataReg_data_1 <= _mshr_io_complete_bits_data_1;	// src/llc/scala/main/LlcPipeline.scala:75:28, :94:25
    end
    else if (_GEN_0) begin	// src/llc/scala/main/LlcPipeline.scala:295:25
      respDataReg_data_0 <= _dataArray_io_readResp_data_0;	// src/llc/scala/main/LlcPipeline.scala:72:28, :94:25
      respDataReg_data_1 <= _dataArray_io_readResp_data_1;	// src/llc/scala/main/LlcPipeline.scala:72:28, :94:25
    end
    else if (_mshr_io_earlyResp_valid) begin	// src/llc/scala/main/LlcPipeline.scala:75:28
      respDataReg_data_0 <=
        _mshr_io_earlyResp_bits_beatIdx ? 256'h0 : _mshr_io_earlyResp_bits_data;	// src/llc/scala/main/LlcPipeline.scala:75:28, :94:25, :109:33
      respDataReg_data_1 <=
        _mshr_io_earlyResp_bits_beatIdx ? _mshr_io_earlyResp_bits_data : 256'h0;	// src/llc/scala/main/LlcPipeline.scala:75:28, :94:25, :109:33
    end
    if (_GEN_21) begin	// src/llc/scala/main/LlcPipeline.scala:272:23
      replayReq_isWrite <= s1Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:120:24, :203:18
      replayReq_address <= s1Req_address;	// src/llc/scala/main/LlcPipeline.scala:120:24, :203:18
      replayReq_id <= s1Req_id;	// src/llc/scala/main/LlcPipeline.scala:120:24, :203:18
      replayReq_writeData <= s1Req_writeData;	// src/llc/scala/main/LlcPipeline.scala:120:24, :203:18
      replayReq_writeStrb <= s1Req_writeStrb;	// src/llc/scala/main/LlcPipeline.scala:120:24, :203:18
      replayReq_beatIdx <= s1Req_beatIdx;	// src/llc/scala/main/LlcPipeline.scala:120:24, :203:18
    end
    if (s0Fire) begin	// src/llc/scala/main/LlcPipeline.scala:184:{47,65,77}
      s1Req_isWrite <= replayValid ? replayReq_isWrite : io_reqIn_payload_isWrite;	// src/llc/scala/main/LlcPipeline.scala:119:28, :120:24, :185:19, :203:18
      s1Req_address <= s0Req_address;	// src/llc/scala/main/LlcPipeline.scala:185:19, :203:18
      s1Req_id <= replayValid ? replayReq_id : io_reqIn_payload_id;	// src/llc/scala/main/LlcPipeline.scala:119:28, :120:24, :185:19, :203:18
      s1Req_writeData <= replayValid ? replayReq_writeData : io_reqIn_payload_writeData;	// src/llc/scala/main/LlcPipeline.scala:119:28, :120:24, :185:19, :203:18
      s1Req_writeStrb <= replayValid ? replayReq_writeStrb : io_reqIn_payload_writeStrb;	// src/llc/scala/main/LlcPipeline.scala:119:28, :120:24, :185:19, :203:18
      s1Req_beatIdx <= replayValid ? replayReq_beatIdx : io_reqIn_payload_beatIdx;	// src/llc/scala/main/LlcPipeline.scala:119:28, :120:24, :185:19, :203:18
      s1Set <= s0Req_address[14:6];	// src/llc/scala/main/LlcPipeline.scala:185:19, :186:29, :204:18
      s1Tag <= s0Req_address[31:15];	// src/llc/scala/main/LlcPipeline.scala:185:19, :187:29, :205:18
    end
    if (_GEN) begin	// src/llc/scala/main/LlcPipeline.scala:240:16
      automatic logic [7:0]       _GEN_29 =
        {{_tagArray_io_readResp_valids_7},
         {_tagArray_io_readResp_valids_6},
         {_tagArray_io_readResp_valids_5},
         {_tagArray_io_readResp_valids_4},
         {_tagArray_io_readResp_valids_3},
         {_tagArray_io_readResp_valids_2},
         {_tagArray_io_readResp_valids_1},
         {_tagArray_io_readResp_valids_0}};	// src/llc/scala/main/LlcPipeline.scala:71:28, :265:19
      automatic logic [7:0]       _GEN_30 =
        {{_tagArray_io_readResp_dirtys_7},
         {_tagArray_io_readResp_dirtys_6},
         {_tagArray_io_readResp_dirtys_5},
         {_tagArray_io_readResp_dirtys_4},
         {_tagArray_io_readResp_dirtys_3},
         {_tagArray_io_readResp_dirtys_2},
         {_tagArray_io_readResp_dirtys_1},
         {_tagArray_io_readResp_dirtys_0}};	// src/llc/scala/main/LlcPipeline.scala:71:28, :266:19
      automatic logic [7:0][16:0] _GEN_31 =
        {{_tagArray_io_readResp_tags_7},
         {_tagArray_io_readResp_tags_6},
         {_tagArray_io_readResp_tags_5},
         {_tagArray_io_readResp_tags_4},
         {_tagArray_io_readResp_tags_3},
         {_tagArray_io_readResp_tags_2},
         {_tagArray_io_readResp_tags_1},
         {_tagArray_io_readResp_tags_0}};	// src/llc/scala/main/LlcPipeline.scala:71:28, :267:19
      s2Req_isWrite <= s1Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:203:18, :247:25
      s2Req_address <= s1Req_address;	// src/llc/scala/main/LlcPipeline.scala:203:18, :247:25
      s2Req_id <= s1Req_id;	// src/llc/scala/main/LlcPipeline.scala:203:18, :247:25
      s2Req_writeData <= s1Req_writeData;	// src/llc/scala/main/LlcPipeline.scala:203:18, :247:25
      s2Req_writeStrb <= s1Req_writeStrb;	// src/llc/scala/main/LlcPipeline.scala:203:18, :247:25
      s2Req_beatIdx <= s1Req_beatIdx;	// src/llc/scala/main/LlcPipeline.scala:203:18, :247:25
      s2Set <= s1Set;	// src/llc/scala/main/LlcPipeline.scala:204:18, :248:25
      s2Tag <= s1Tag;	// src/llc/scala/main/LlcPipeline.scala:205:18, :249:25
      s2HitWay <= hitWay;	// src/llc/scala/main/LlcPipeline.scala:251:25, src/main/scala/chisel3/util/OneHot.scala:32:10
      s2VictimWay <= _wayPartition_io_victimWay;	// src/llc/scala/main/LlcPipeline.scala:74:28, :252:25
      s2VictimValid <= _GEN_29[_wayPartition_io_victimWay];	// src/llc/scala/main/LlcPipeline.scala:74:28, :253:26, :265:19
      s2VictimDirty <= _GEN_30[_wayPartition_io_victimWay];	// src/llc/scala/main/LlcPipeline.scala:74:28, :254:26, :266:19
      s2VictimTag <= _GEN_31[_wayPartition_io_victimWay];	// src/llc/scala/main/LlcPipeline.scala:74:28, :255:25, :267:19
    end
    if (_GEN_3 | _GEN_4 | _GEN_5 | ~_GEN_7) begin	// src/llc/scala/main/LlcPipeline.scala:398:26, :400:26, :418:22
    end
    else begin	// src/llc/scala/main/LlcPipeline.scala:400:26, :418:22
      latchedTags_0 <= _tagArray_io_readResp_tags_0;	// src/llc/scala/main/LlcPipeline.scala:71:28, :398:26
      latchedTags_1 <= _tagArray_io_readResp_tags_1;	// src/llc/scala/main/LlcPipeline.scala:71:28, :398:26
      latchedTags_2 <= _tagArray_io_readResp_tags_2;	// src/llc/scala/main/LlcPipeline.scala:71:28, :398:26
      latchedTags_3 <= _tagArray_io_readResp_tags_3;	// src/llc/scala/main/LlcPipeline.scala:71:28, :398:26
      latchedTags_4 <= _tagArray_io_readResp_tags_4;	// src/llc/scala/main/LlcPipeline.scala:71:28, :398:26
      latchedTags_5 <= _tagArray_io_readResp_tags_5;	// src/llc/scala/main/LlcPipeline.scala:71:28, :398:26
      latchedTags_6 <= _tagArray_io_readResp_tags_6;	// src/llc/scala/main/LlcPipeline.scala:71:28, :398:26
      latchedTags_7 <= _tagArray_io_readResp_tags_7;	// src/llc/scala/main/LlcPipeline.scala:71:28, :398:26
      latchedValids_0 <= _tagArray_io_readResp_valids_0;	// src/llc/scala/main/LlcPipeline.scala:71:28, :399:26
      latchedValids_1 <= _tagArray_io_readResp_valids_1;	// src/llc/scala/main/LlcPipeline.scala:71:28, :399:26
      latchedValids_2 <= _tagArray_io_readResp_valids_2;	// src/llc/scala/main/LlcPipeline.scala:71:28, :399:26
      latchedValids_3 <= _tagArray_io_readResp_valids_3;	// src/llc/scala/main/LlcPipeline.scala:71:28, :399:26
      latchedValids_4 <= _tagArray_io_readResp_valids_4;	// src/llc/scala/main/LlcPipeline.scala:71:28, :399:26
      latchedValids_5 <= _tagArray_io_readResp_valids_5;	// src/llc/scala/main/LlcPipeline.scala:71:28, :399:26
      latchedValids_6 <= _tagArray_io_readResp_valids_6;	// src/llc/scala/main/LlcPipeline.scala:71:28, :399:26
      latchedValids_7 <= _tagArray_io_readResp_valids_7;	// src/llc/scala/main/LlcPipeline.scala:71:28, :399:26
      latchedDirtys_0 <= _tagArray_io_readResp_dirtys_0;	// src/llc/scala/main/LlcPipeline.scala:71:28, :400:26
      latchedDirtys_1 <= _tagArray_io_readResp_dirtys_1;	// src/llc/scala/main/LlcPipeline.scala:71:28, :400:26
      latchedDirtys_2 <= _tagArray_io_readResp_dirtys_2;	// src/llc/scala/main/LlcPipeline.scala:71:28, :400:26
      latchedDirtys_3 <= _tagArray_io_readResp_dirtys_3;	// src/llc/scala/main/LlcPipeline.scala:71:28, :400:26
      latchedDirtys_4 <= _tagArray_io_readResp_dirtys_4;	// src/llc/scala/main/LlcPipeline.scala:71:28, :400:26
      latchedDirtys_5 <= _tagArray_io_readResp_dirtys_5;	// src/llc/scala/main/LlcPipeline.scala:71:28, :400:26
      latchedDirtys_6 <= _tagArray_io_readResp_dirtys_6;	// src/llc/scala/main/LlcPipeline.scala:71:28, :400:26
      latchedDirtys_7 <= _tagArray_io_readResp_dirtys_7;	// src/llc/scala/main/LlcPipeline.scala:71:28, :400:26
    end
    if (_GEN_3 | _GEN_4 | _GEN_5 | _GEN_7 | _GEN_8 | _GEN_9 | ~_GEN_12) begin	// src/llc/scala/main/LlcPipeline.scala:402:26, :418:22
    end
    else begin	// src/llc/scala/main/LlcPipeline.scala:402:26, :418:22
      flushLineData_0 <= _dataArray_io_readResp_data_0;	// src/llc/scala/main/LlcPipeline.scala:72:28, :402:26
      flushLineData_1 <= _dataArray_io_readResp_data_1;	// src/llc/scala/main/LlcPipeline.scala:72:28, :402:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/llc/scala/main/LlcPipeline.scala:27:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/llc/scala/main/LlcPipeline.scala:27:7
      `FIRRTL_BEFORE_INITIAL	// src/llc/scala/main/LlcPipeline.scala:27:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/llc/scala/main/LlcPipeline.scala:27:7
      automatic logic [31:0] _RANDOM[0:70];	// src/llc/scala/main/LlcPipeline.scala:27:7
      `ifdef INIT_RANDOM_PROLOG_	// src/llc/scala/main/LlcPipeline.scala:27:7
        `INIT_RANDOM_PROLOG_	// src/llc/scala/main/LlcPipeline.scala:27:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/llc/scala/main/LlcPipeline.scala:27:7
        for (logic [6:0] i = 7'h0; i < 7'h47; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;	// src/llc/scala/main/LlcPipeline.scala:27:7
        end	// src/llc/scala/main/LlcPipeline.scala:27:7
        respValidReg = _RANDOM[7'h0][0];	// src/llc/scala/main/LlcPipeline.scala:27:7, :93:29
        respDataReg_isWrite = _RANDOM[7'h0][1];	// src/llc/scala/main/LlcPipeline.scala:27:7, :93:29, :94:25
        respDataReg_data_0 =
          {_RANDOM[7'h0][31:6],
           _RANDOM[7'h1],
           _RANDOM[7'h2],
           _RANDOM[7'h3],
           _RANDOM[7'h4],
           _RANDOM[7'h5],
           _RANDOM[7'h6],
           _RANDOM[7'h7],
           _RANDOM[7'h8][5:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :93:29, :94:25
        respDataReg_data_1 =
          {_RANDOM[7'h8][31:6],
           _RANDOM[7'h9],
           _RANDOM[7'hA],
           _RANDOM[7'hB],
           _RANDOM[7'hC],
           _RANDOM[7'hD],
           _RANDOM[7'hE],
           _RANDOM[7'hF],
           _RANDOM[7'h10][5:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25
        s1Valid = _RANDOM[7'h10][6];	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25, :115:24
        s2Valid = _RANDOM[7'h10][7];	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25, :116:24
        replayValid = _RANDOM[7'h10][8];	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25, :119:28
        replayReq_isWrite = _RANDOM[7'h10][9];	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25, :120:24
        replayReq_address = {_RANDOM[7'h10][31:10], _RANDOM[7'h11][9:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25, :120:24
        replayReq_id = _RANDOM[7'h11][13:10];	// src/llc/scala/main/LlcPipeline.scala:27:7, :120:24
        replayReq_writeData =
          {_RANDOM[7'h11][31:14],
           _RANDOM[7'h12],
           _RANDOM[7'h13],
           _RANDOM[7'h14],
           _RANDOM[7'h15],
           _RANDOM[7'h16],
           _RANDOM[7'h17],
           _RANDOM[7'h18],
           _RANDOM[7'h19][13:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :120:24
        replayReq_writeStrb = {_RANDOM[7'h19][31:14], _RANDOM[7'h1A][13:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :120:24
        replayReq_beatIdx = _RANDOM[7'h1A][14];	// src/llc/scala/main/LlcPipeline.scala:27:7, :120:24
        s1Req_isWrite = _RANDOM[7'h1A][15];	// src/llc/scala/main/LlcPipeline.scala:27:7, :120:24, :203:18
        s1Req_address = {_RANDOM[7'h1A][31:16], _RANDOM[7'h1B][15:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :120:24, :203:18
        s1Req_id = _RANDOM[7'h1B][19:16];	// src/llc/scala/main/LlcPipeline.scala:27:7, :203:18
        s1Req_writeData =
          {_RANDOM[7'h1B][31:20],
           _RANDOM[7'h1C],
           _RANDOM[7'h1D],
           _RANDOM[7'h1E],
           _RANDOM[7'h1F],
           _RANDOM[7'h20],
           _RANDOM[7'h21],
           _RANDOM[7'h22],
           _RANDOM[7'h23][19:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :203:18
        s1Req_writeStrb = {_RANDOM[7'h23][31:20], _RANDOM[7'h24][19:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :203:18
        s1Req_beatIdx = _RANDOM[7'h24][20];	// src/llc/scala/main/LlcPipeline.scala:27:7, :203:18
        s1Set = _RANDOM[7'h24][29:21];	// src/llc/scala/main/LlcPipeline.scala:27:7, :203:18, :204:18
        s1Tag = {_RANDOM[7'h24][31:30], _RANDOM[7'h25][14:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :203:18, :205:18
        s2Req_isWrite = _RANDOM[7'h25][15];	// src/llc/scala/main/LlcPipeline.scala:27:7, :205:18, :247:25
        s2Req_address = {_RANDOM[7'h25][31:16], _RANDOM[7'h26][15:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :205:18, :247:25
        s2Req_id = _RANDOM[7'h26][19:16];	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25
        s2Req_writeData =
          {_RANDOM[7'h26][31:20],
           _RANDOM[7'h27],
           _RANDOM[7'h28],
           _RANDOM[7'h29],
           _RANDOM[7'h2A],
           _RANDOM[7'h2B],
           _RANDOM[7'h2C],
           _RANDOM[7'h2D],
           _RANDOM[7'h2E][19:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25
        s2Req_writeStrb = {_RANDOM[7'h2E][31:20], _RANDOM[7'h2F][19:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25
        s2Req_beatIdx = _RANDOM[7'h2F][20];	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25
        s2Set = _RANDOM[7'h2F][29:21];	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25, :248:25
        s2Tag = {_RANDOM[7'h2F][31:30], _RANDOM[7'h30][14:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25, :249:25
        s2Hit = _RANDOM[7'h30][15];	// src/llc/scala/main/LlcPipeline.scala:27:7, :249:25, :250:29
        s2HitWay = _RANDOM[7'h30][18:16];	// src/llc/scala/main/LlcPipeline.scala:27:7, :249:25, :251:25
        s2VictimWay = _RANDOM[7'h30][21:19];	// src/llc/scala/main/LlcPipeline.scala:27:7, :249:25, :252:25
        s2VictimValid = _RANDOM[7'h30][22];	// src/llc/scala/main/LlcPipeline.scala:27:7, :249:25, :253:26
        s2VictimDirty = _RANDOM[7'h30][23];	// src/llc/scala/main/LlcPipeline.scala:27:7, :249:25, :254:26
        s2VictimTag = {_RANDOM[7'h30][31:24], _RANDOM[7'h31][8:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :249:25, :255:25
        flushState = _RANDOM[7'h31][12:9];	// src/llc/scala/main/LlcPipeline.scala:27:7, :255:25, :392:27
        flushInv = _RANDOM[7'h31][13];	// src/llc/scala/main/LlcPipeline.scala:27:7, :255:25, :393:27
        curSet = _RANDOM[7'h31][22:14];	// src/llc/scala/main/LlcPipeline.scala:27:7, :255:25, :394:27
        curWay = _RANDOM[7'h31][25:23];	// src/llc/scala/main/LlcPipeline.scala:27:7, :255:25, :395:27
        latchedTags_0 = {_RANDOM[7'h31][31:26], _RANDOM[7'h32][10:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :255:25, :398:26
        latchedTags_1 = _RANDOM[7'h32][27:11];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26
        latchedTags_2 = {_RANDOM[7'h32][31:28], _RANDOM[7'h33][12:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26
        latchedTags_3 = _RANDOM[7'h33][29:13];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26
        latchedTags_4 = {_RANDOM[7'h33][31:30], _RANDOM[7'h34][14:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26
        latchedTags_5 = _RANDOM[7'h34][31:15];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26
        latchedTags_6 = _RANDOM[7'h35][16:0];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26
        latchedTags_7 = {_RANDOM[7'h35][31:17], _RANDOM[7'h36][1:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26
        latchedValids_0 = _RANDOM[7'h36][2];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :399:26
        latchedValids_1 = _RANDOM[7'h36][3];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :399:26
        latchedValids_2 = _RANDOM[7'h36][4];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :399:26
        latchedValids_3 = _RANDOM[7'h36][5];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :399:26
        latchedValids_4 = _RANDOM[7'h36][6];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :399:26
        latchedValids_5 = _RANDOM[7'h36][7];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :399:26
        latchedValids_6 = _RANDOM[7'h36][8];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :399:26
        latchedValids_7 = _RANDOM[7'h36][9];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :399:26
        latchedDirtys_0 = _RANDOM[7'h36][10];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :400:26
        latchedDirtys_1 = _RANDOM[7'h36][11];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :400:26
        latchedDirtys_2 = _RANDOM[7'h36][12];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :400:26
        latchedDirtys_3 = _RANDOM[7'h36][13];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :400:26
        latchedDirtys_4 = _RANDOM[7'h36][14];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :400:26
        latchedDirtys_5 = _RANDOM[7'h36][15];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :400:26
        latchedDirtys_6 = _RANDOM[7'h36][16];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :400:26
        latchedDirtys_7 = _RANDOM[7'h36][17];	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :400:26
        flushLineData_0 =
          {_RANDOM[7'h36][31:18],
           _RANDOM[7'h37],
           _RANDOM[7'h38],
           _RANDOM[7'h39],
           _RANDOM[7'h3A],
           _RANDOM[7'h3B],
           _RANDOM[7'h3C],
           _RANDOM[7'h3D],
           _RANDOM[7'h3E][17:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :398:26, :402:26
        flushLineData_1 =
          {_RANDOM[7'h3E][31:18],
           _RANDOM[7'h3F],
           _RANDOM[7'h40],
           _RANDOM[7'h41],
           _RANDOM[7'h42],
           _RANDOM[7'h43],
           _RANDOM[7'h44],
           _RANDOM[7'h45],
           _RANDOM[7'h46][17:0]};	// src/llc/scala/main/LlcPipeline.scala:27:7, :402:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/llc/scala/main/LlcPipeline.scala:27:7
      `FIRRTL_AFTER_INITIAL	// src/llc/scala/main/LlcPipeline.scala:27:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  LlcTagArray tagArray (	// src/llc/scala/main/LlcPipeline.scala:71:28
    .clock                (clock),
    .io_read_enable       (~_GEN_6 & _GEN_5 | s0Fire),	// src/llc/scala/main/LlcPipeline.scala:184:{47,65,77}, :197:16, :418:22
    .io_read_set
      (_GEN_6 | ~_GEN_5 ? (s0Fire ? s0Req_address[14:6] : 9'h0) : curSet),	// src/llc/scala/main/LlcPipeline.scala:134:28, :184:{47,65,77}, :185:19, :186:29, :197:16, :199:29, :394:27, :418:22
    .io_readResp_tags_0   (_tagArray_io_readResp_tags_0),
    .io_readResp_tags_1   (_tagArray_io_readResp_tags_1),
    .io_readResp_tags_2   (_tagArray_io_readResp_tags_2),
    .io_readResp_tags_3   (_tagArray_io_readResp_tags_3),
    .io_readResp_tags_4   (_tagArray_io_readResp_tags_4),
    .io_readResp_tags_5   (_tagArray_io_readResp_tags_5),
    .io_readResp_tags_6   (_tagArray_io_readResp_tags_6),
    .io_readResp_tags_7   (_tagArray_io_readResp_tags_7),
    .io_readResp_valids_0 (_tagArray_io_readResp_valids_0),
    .io_readResp_valids_1 (_tagArray_io_readResp_valids_1),
    .io_readResp_valids_2 (_tagArray_io_readResp_valids_2),
    .io_readResp_valids_3 (_tagArray_io_readResp_valids_3),
    .io_readResp_valids_4 (_tagArray_io_readResp_valids_4),
    .io_readResp_valids_5 (_tagArray_io_readResp_valids_5),
    .io_readResp_valids_6 (_tagArray_io_readResp_valids_6),
    .io_readResp_valids_7 (_tagArray_io_readResp_valids_7),
    .io_readResp_dirtys_0 (_tagArray_io_readResp_dirtys_0),
    .io_readResp_dirtys_1 (_tagArray_io_readResp_dirtys_1),
    .io_readResp_dirtys_2 (_tagArray_io_readResp_dirtys_2),
    .io_readResp_dirtys_3 (_tagArray_io_readResp_dirtys_3),
    .io_readResp_dirtys_4 (_tagArray_io_readResp_dirtys_4),
    .io_readResp_dirtys_5 (_tagArray_io_readResp_dirtys_5),
    .io_readResp_dirtys_6 (_tagArray_io_readResp_dirtys_6),
    .io_readResp_dirtys_7 (_tagArray_io_readResp_dirtys_7),
    .io_write_enable
      (_GEN_19 ? _GEN_2 : _GEN_18 | _mshr_io_complete_valid | dataArray_io_write_enable),	// src/llc/scala/main/LlcPipeline.scala:75:28, :146:32, :295:56, :296:25, :349:24, :357:30, :418:22, :474:32
    .io_write_set
      (_GEN_20
         ? (_mshr_io_complete_valid ? _mshr_io_complete_bits_set : dataArray_io_write_set)
         : curSet),	// src/llc/scala/main/LlcPipeline.scala:75:28, :147:32, :295:56, :296:25, :299:34, :349:24, :358:30, :394:27, :418:22
    .io_write_way
      (_GEN_20
         ? (_mshr_io_complete_valid ? _mshr_io_complete_bits_way : dataArray_io_write_way)
         : curWay),	// src/llc/scala/main/LlcPipeline.scala:75:28, :148:32, :295:56, :296:25, :300:34, :349:24, :359:30, :395:27, :418:22
    .io_write_tag
      (_GEN_20
         ? (_mshr_io_complete_valid ? _mshr_io_complete_bits_tag : _GEN_1 ? s2Tag : 17'h0)
         : _GEN_16),	// src/llc/scala/main/LlcPipeline.scala:75:28, :138:28, :147:32, :249:25, :295:56, :296:25, :299:34, :309:32, :349:24, :360:30, :418:22, :467:35
    .io_write_valid       (_GEN_20 ? _GEN_2 : ~flushInv),	// src/llc/scala/main/LlcPipeline.scala:295:56, :349:24, :357:30, :393:27, :418:22, :478:35
    .io_write_dirty
      (_GEN_20
       & (_mshr_io_complete_valid
            ? _mshr_io_complete_bits_dirty
            : dataArray_io_write_enable))	// src/llc/scala/main/LlcPipeline.scala:75:28, :146:32, :295:56, :296:25, :349:24, :362:30, :418:22
  );	// src/llc/scala/main/LlcPipeline.scala:71:28
  LlcDataArray dataArray (	// src/llc/scala/main/LlcPipeline.scala:72:28
    .clock               (clock),
    .io_read_enable      (~_GEN_10 & _GEN_9 | _GEN),	// src/llc/scala/main/LlcPipeline.scala:240:{16,35}, :418:22
    .io_read_set         (_GEN_11 ? (_GEN ? s1Set : 9'h0) : curSet),	// src/llc/scala/main/LlcPipeline.scala:144:32, :204:18, :240:{16,35}, :242:30, :394:27, :418:22
    .io_read_way
      (_GEN_11
         ? (_GEN ? ((|_hitWay_T) ? hitWay : _wayPartition_io_victimWay) : 3'h0)
         : curWay),	// src/llc/scala/main/LlcPipeline.scala:74:28, :145:32, :223:{24,31}, :239:24, :240:{16,35}, :243:30, :395:27, :418:22, src/main/scala/chisel3/util/OneHot.scala:32:10
    .io_readResp_data_0  (_dataArray_io_readResp_data_0),
    .io_readResp_data_1  (_dataArray_io_readResp_data_1),
    .io_write_enable     (dataArray_io_write_enable),	// src/llc/scala/main/LlcPipeline.scala:146:32, :295:56, :296:25
    .io_write_set        (dataArray_io_write_set),	// src/llc/scala/main/LlcPipeline.scala:147:32, :295:56, :296:25, :299:34
    .io_write_way        (dataArray_io_write_way),	// src/llc/scala/main/LlcPipeline.scala:148:32, :295:56, :296:25, :300:34
    .io_write_data       (_GEN_1 ? s2Req_writeData : 256'h0),	// src/llc/scala/main/LlcPipeline.scala:147:32, :150:32, :247:25, :295:56, :296:25, :299:34, :302:34
    .io_writeLine_enable (_mshr_io_complete_valid),	// src/llc/scala/main/LlcPipeline.scala:75:28
    .io_writeLine_set    (_mshr_io_complete_valid ? _mshr_io_complete_bits_set : 9'h0),	// src/llc/scala/main/LlcPipeline.scala:75:28, :153:32, :349:24, :352:35
    .io_writeLine_way    (_mshr_io_complete_valid ? _mshr_io_complete_bits_way : 3'h0),	// src/llc/scala/main/LlcPipeline.scala:75:28, :154:32, :349:24, :353:35
    .io_writeLine_data_0
      (_mshr_io_complete_valid ? _mshr_io_complete_bits_data_0 : 256'h0),	// src/llc/scala/main/LlcPipeline.scala:75:28, :155:32, :349:24, :354:35
    .io_writeLine_data_1
      (_mshr_io_complete_valid ? _mshr_io_complete_bits_data_1 : 256'h0)	// src/llc/scala/main/LlcPipeline.scala:75:28, :155:32, :349:24, :354:35
  );	// src/llc/scala/main/LlcPipeline.scala:72:28
  LlcPlru plru (	// src/llc/scala/main/LlcPipeline.scala:73:28
    .clock                  (clock),
    .reset                  (reset),
    .io_query_set           (s1Set),	// src/llc/scala/main/LlcPipeline.scala:204:18
    .io_queryResp_victimWay (_plru_io_queryResp_victimWay),
    .io_update_enable       (_mshr_io_complete_valid | _GEN_0),	// src/llc/scala/main/LlcPipeline.scala:75:28, :295:{25,56}, :349:24, :365:27
    .io_update_set
      (_mshr_io_complete_valid ? _mshr_io_complete_bits_set : _GEN_0 ? s2Set : 9'h0),	// src/llc/scala/main/LlcPipeline.scala:75:28, :160:26, :248:25, :295:{25,56}, :322:27, :349:24, :366:27
    .io_update_way
      (_mshr_io_complete_valid ? _mshr_io_complete_bits_way : _GEN_0 ? s2HitWay : 3'h0)	// src/llc/scala/main/LlcPipeline.scala:75:28, :161:26, :251:25, :295:{25,56}, :323:27, :349:24, :367:27
  );	// src/llc/scala/main/LlcPipeline.scala:73:28
  LlcWayPartition wayPartition (	// src/llc/scala/main/LlcPipeline.scala:74:28
    .io_partitionId (s1Req_id[0]),	// src/llc/scala/main/LlcPipeline.scala:203:18, :232:13
    .io_plruVictim  (_plru_io_queryResp_victimWay),	// src/llc/scala/main/LlcPipeline.scala:73:28
    .io_wayValids_0 (_tagArray_io_readResp_valids_0),	// src/llc/scala/main/LlcPipeline.scala:71:28
    .io_wayValids_1 (_tagArray_io_readResp_valids_1),	// src/llc/scala/main/LlcPipeline.scala:71:28
    .io_wayValids_2 (_tagArray_io_readResp_valids_2),	// src/llc/scala/main/LlcPipeline.scala:71:28
    .io_wayValids_3 (_tagArray_io_readResp_valids_3),	// src/llc/scala/main/LlcPipeline.scala:71:28
    .io_wayValids_4 (_tagArray_io_readResp_valids_4),	// src/llc/scala/main/LlcPipeline.scala:71:28
    .io_wayValids_5 (_tagArray_io_readResp_valids_5),	// src/llc/scala/main/LlcPipeline.scala:71:28
    .io_wayValids_6 (_tagArray_io_readResp_valids_6),	// src/llc/scala/main/LlcPipeline.scala:71:28
    .io_wayValids_7 (_tagArray_io_readResp_valids_7),	// src/llc/scala/main/LlcPipeline.scala:71:28
    .io_victimWay   (_wayPartition_io_victimWay)
  );	// src/llc/scala/main/LlcPipeline.scala:74:28
  LlcMshr mshr (	// src/llc/scala/main/LlcPipeline.scala:75:28
    .clock                          (clock),
    .reset                          (reset),
    .io_allocReq_valid              (allocFire),	// src/llc/scala/main/LlcPipeline.scala:330:{27,37,53,75}
    .io_allocReq_bits_address       (mshr_io_addrMatch_query),	// src/llc/scala/main/LlcPipeline.scala:285:44
    .io_allocReq_bits_set           (s2Set),	// src/llc/scala/main/LlcPipeline.scala:248:25
    .io_allocReq_bits_way           (s2VictimWay),	// src/llc/scala/main/LlcPipeline.scala:252:25
    .io_allocReq_bits_dirtyEvict    (s2VictimValid & s2VictimDirty),	// src/llc/scala/main/LlcPipeline.scala:253:26, :254:26, :335:56
    .io_allocReq_bits_evictTag      (s2VictimTag),	// src/llc/scala/main/LlcPipeline.scala:255:25
    .io_allocReq_bits_evictData_0   (_dataArray_io_readResp_data_0),	// src/llc/scala/main/LlcPipeline.scala:72:28
    .io_allocReq_bits_evictData_1   (_dataArray_io_readResp_data_1),	// src/llc/scala/main/LlcPipeline.scala:72:28
    .io_allocReq_bits_reqId         (s2Req_id),	// src/llc/scala/main/LlcPipeline.scala:247:25
    .io_allocReq_bits_reqType       (s2Req_isWrite),	// src/llc/scala/main/LlcPipeline.scala:247:25
    .io_allocReq_bits_writeData     (s2Req_writeData),	// src/llc/scala/main/LlcPipeline.scala:247:25
    .io_allocReq_bits_writeStrb     (s2Req_writeStrb),	// src/llc/scala/main/LlcPipeline.scala:247:25
    .io_allocReq_bits_writeBeatIdx  (s2Req_beatIdx),	// src/llc/scala/main/LlcPipeline.scala:247:25
    .io_allocReady                  (_mshr_io_allocReady),
    .io_wbReq_valid                 (_mshr_io_wbReq_valid),
    .io_wbReq_bits_address          (_mshr_io_wbReq_bits_address),
    .io_wbReq_bits_data_0           (_mshr_io_wbReq_bits_data_0),
    .io_wbReq_bits_data_1           (_mshr_io_wbReq_bits_data_1),
    .io_wbDone                      (io_wbDone),
    .io_refillReq_valid             (io_refillReq_valid),
    .io_refillReq_bits_address      (io_refillReq_bits_address),
    .io_refillReq_bits_id           (io_refillReq_bits_id),
    .io_refillReady                 (io_refillReady),
    .io_refillData_valid            (io_refillData_valid),
    .io_refillData_bits_data        (io_refillData_bits_data),
    .io_refillData_bits_last        (io_refillData_bits_last),
    .io_complete_valid              (_mshr_io_complete_valid),
    .io_complete_bits_set           (_mshr_io_complete_bits_set),
    .io_complete_bits_way           (_mshr_io_complete_bits_way),
    .io_complete_bits_tag           (_mshr_io_complete_bits_tag),
    .io_complete_bits_data_0        (_mshr_io_complete_bits_data_0),
    .io_complete_bits_data_1        (_mshr_io_complete_bits_data_1),
    .io_complete_bits_dirty         (_mshr_io_complete_bits_dirty),
    .io_complete_bits_reqType       (_mshr_io_complete_bits_reqType),
    .io_complete_bits_earlyRespDone (_mshr_io_complete_bits_earlyRespDone),
    .io_earlyResp_valid             (_mshr_io_earlyResp_valid),
    .io_earlyResp_bits_data         (_mshr_io_earlyResp_bits_data),
    .io_earlyResp_bits_beatIdx      (_mshr_io_earlyResp_bits_beatIdx),
    .io_allIdle                     (_mshr_io_allIdle),
    .io_addrMatch_query             (mshr_io_addrMatch_query),	// src/llc/scala/main/LlcPipeline.scala:285:44
    .io_addrMatch_hit               (_mshr_io_addrMatch_hit)
  );	// src/llc/scala/main/LlcPipeline.scala:75:28
  assign io_reqIn_ready = io_reqIn_ready_0;	// src/llc/scala/main/LlcPipeline.scala:27:7, :194:{36,48,64}
  assign io_respOut_valid = respValidReg;	// src/llc/scala/main/LlcPipeline.scala:27:7, :93:29
  assign io_respOut_payload_isWrite = respDataReg_isWrite;	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25
  assign io_respOut_payload_data_0 = respDataReg_data_0;	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25
  assign io_respOut_payload_data_1 = respDataReg_data_1;	// src/llc/scala/main/LlcPipeline.scala:27:7, :94:25
  assign io_wbReq_valid = ~_GEN_14 & _GEN_13 | ~(|flushState) & _mshr_io_wbReq_valid;	// src/llc/scala/main/LlcPipeline.scala:27:7, :75:28, :78:12, :392:27, :404:29, :412:21, :413:27, :418:22
  assign io_wbReq_bits_address =
    _GEN_17
      ? ((|flushState) ? 32'h0 : _mshr_io_wbReq_bits_address)
      : {_GEN_16, curSet, 6'h0};	// src/llc/scala/main/LlcPipeline.scala:27:7, :75:28, :78:12, :151:32, :392:27, :394:27, :404:29, :412:21, :414:27, :418:22, :467:35
  assign io_wbReq_bits_data_0 =
    _GEN_17 ? ((|flushState) ? 256'h0 : _mshr_io_wbReq_bits_data_0) : flushLineData_0;	// src/llc/scala/main/LlcPipeline.scala:27:7, :75:28, :78:12, :392:27, :402:26, :404:29, :412:21, :415:27, :418:22
  assign io_wbReq_bits_data_1 =
    _GEN_17 ? ((|flushState) ? 256'h0 : _mshr_io_wbReq_bits_data_1) : flushLineData_1;	// src/llc/scala/main/LlcPipeline.scala:27:7, :75:28, :78:12, :392:27, :402:26, :404:29, :412:21, :415:27, :418:22
  assign io_perfEvents_readHit = _hitFire_T_2 & ~s2Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25, :513:34, :514:{43,46}
  assign io_perfEvents_readMiss = allocFire & ~s2Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25, :330:{27,37,53,75}, :514:46, :517:45
  assign io_perfEvents_writeHit = _hitFire_T_2 & s2Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25, :513:34, :515:43
  assign io_perfEvents_writeMiss = allocFire & s2Req_isWrite;	// src/llc/scala/main/LlcPipeline.scala:27:7, :247:25, :330:{27,37,53,75}, :518:45
  assign io_perfEvents_dirtyEvict = _io_perfEvents_cleanEvict_T & s2VictimDirty;	// src/llc/scala/main/LlcPipeline.scala:27:7, :254:26, :520:{45,62}
  assign io_perfEvents_cleanEvict = _io_perfEvents_cleanEvict_T & ~s2VictimDirty;	// src/llc/scala/main/LlcPipeline.scala:27:7, :254:26, :520:45, :521:{62,65}
  assign io_perfEvents_mshrFullStall = s2MshrFull;	// src/llc/scala/main/LlcPipeline.scala:27:7, :291:{31,54}
  assign io_perfEvents_refillComplete = _mshr_io_complete_valid;	// src/llc/scala/main/LlcPipeline.scala:27:7, :75:28
  assign io_flushBusy = |flushState;	// src/llc/scala/main/LlcPipeline.scala:27:7, :392:27, :404:29
  assign io_flushDone = flushState == 4'hB;	// src/llc/scala/main/LlcPipeline.scala:27:7, :392:27, :499:40, :507:31
endmodule

