// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Fb_FbIm2colAddrGen(	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
  input         clock,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
                reset,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
                io_start,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
  input  [31:0] io_srcBase,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_dstBase,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
  input  [1:0]  io_elemBytesLog2,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
  input  [7:0]  io_kernel_0,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_kernel_1,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_stride_0,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_stride_1,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_pad_0,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_pad_1,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_dilation_0,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_dilation_1,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
  input  [15:0] io_inShape_0,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_inShape_1,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_inShape_2,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
  output        io_valid,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
  input         io_advance,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
  output [31:0] io_srcAddr,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_dstAddr,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
  output        io_isPad,	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
                io_done	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
);

  reg  [7:0]  kH;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:43:21
  reg  [7:0]  kW;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:44:21
  reg  [7:0]  sH;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:45:21
  reg  [7:0]  sW;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:46:21
  reg  [7:0]  pH;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:47:21
  reg  [7:0]  pW;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:48:21
  reg  [7:0]  dH;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:49:21
  reg  [15:0] C;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:51:21
  reg  [15:0] H;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:52:21
  reg  [15:0] W;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:53:21
  reg  [15:0] outH;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:54:21
  reg  [15:0] outW;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:55:21
  reg  [3:0]  elemBytes;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:56:26
  reg  [31:0] srcBaseReg;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:58:27
  reg  [31:0] dstBaseReg;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:59:27
  reg  [7:0]  cntKh;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:64:22
  reg  [15:0] cntC;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:65:22
  reg  [15:0] cntOw;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:66:22
  reg  [15:0] cntOh;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:67:22
  reg         running;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:72:25
  reg         doneReg;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:73:25
  reg  [31:0] dstOffset;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:76:26
  wire [23:0] _ihRaw_T_3 =
    {8'h0, {8'h0, cntKh} * {8'h0, dH}} + {8'h0, cntOh} * {16'h0, sH};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:45:21, :49:21, :64:22, :67:22, :165:{25,39,48,57}
  wire [23:0] _GEN = {16'h0, pH};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:47:21, :166:24
  wire [23:0] _ihVal_T_1 = _ihRaw_T_3 - _GEN;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:165:{39,57}, :166:{24,32}, :167:24
  wire [31:0] _GEN_0 = {16'h0, W};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:53:21, :185:63
  always @(posedge clock) begin	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
    if (reset) begin	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
      kH <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:43:21
      kW <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:44:21
      sH <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:45:21
      sW <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:46:21
      pH <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:47:21
      pW <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:48:21
      dH <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:49:21
      C <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:51:21
      H <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:52:21
      W <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:53:21
      outH <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:54:21
      outW <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:55:21
      elemBytes <= 4'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :56:26
      srcBaseReg <= 32'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:58:27
      dstBaseReg <= 32'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:59:27
      cntKh <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:64:22
      cntC <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:65:22
      cntOw <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:66:22
      cntOh <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:67:22
      running <= 1'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:72:25
      doneReg <= 1'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:72:25, :73:25
      dstOffset <= 32'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:76:26
    end
    else begin	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
      automatic logic _GEN_1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:124:{16,30}
      automatic logic khWrap;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:125:24
      automatic logic cWrap;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:126:23
      automatic logic owWrap;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:127:24
      automatic logic ohWrap;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:128:24
      automatic logic _GEN_2;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:81:18, :124:43, :131:18, :134:19, :137:22, :140:24, :141:21
      _GEN_1 = running & io_advance & ~doneReg;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:72:25, :73:25, :124:{16,30,33}
      khWrap = cntKh == kH - 8'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:43:21, :64:22, :125:{24,32}
      cWrap = cntC == C - 16'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:51:21, :65:22, :126:{23,30}
      owWrap = cntOw == outW - 16'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:55:21, :66:22, :127:{24,34}
      ohWrap = cntOh == outH - 16'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:54:21, :67:22, :128:{24,34}
      _GEN_2 = _GEN_1 & khWrap & cWrap & owWrap & ohWrap;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:81:18, :124:{16,30,43}, :125:24, :126:23, :127:24, :128:24, :131:18, :134:19, :137:22, :140:24, :141:21
      if (io_start) begin	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
        automatic logic [39:0] _outH_T_1 =
          ({19'h0, {5'h0, io_inShape_1} + {12'h0, io_pad_0, 1'h0}}
           - {32'h0, io_dilation_0} * {31'h0, {1'h0, io_kernel_0} - 9'h1} - 40'h1)
          / {32'h0, io_stride_0};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:72:25, :98:33, :100:{40,59,64}, :101:{24,30,38}, :102:22
        automatic logic [39:0] _outW_T_1 =
          ({19'h0, {5'h0, io_inShape_2} + {12'h0, io_pad_1, 1'h0}}
           - {32'h0, io_dilation_1} * {31'h0, {1'h0, io_kernel_1} - 9'h1} - 40'h1)
          / {32'h0, io_stride_1};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:72:25, :105:33, :107:{40,59,64}, :108:{24,30,38}, :109:22
        automatic logic [6:0]  _elemBytes_T = 7'h1 << io_elemBytesLog2;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:93:27
        kH <= io_kernel_0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:43:21
        kW <= io_kernel_1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:44:21
        sH <= io_stride_0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:45:21
        sW <= io_stride_1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:46:21
        pH <= io_pad_0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:47:21
        pW <= io_pad_1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:48:21
        dH <= io_dilation_0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:49:21
        C <= io_inShape_0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:51:21
        H <= io_inShape_1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:52:21
        W <= io_inShape_2;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:53:21
        outH <= _outH_T_1[15:0] + 16'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:54:21, :102:{22,45,53}
        outW <= _outW_T_1[15:0] + 16'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:55:21, :109:{22,45,53}
        elemBytes <= _elemBytes_T[3:0];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:56:26, :93:{15,27}
        srcBaseReg <= io_srcBase;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:58:27
        dstBaseReg <= io_dstBase;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:59:27
      end
      if (_GEN_1) begin	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:124:{16,30}
        cntKh <= khWrap ? 8'h0 : cntKh + 8'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:64:22, :100:{59,64}, :125:24, :131:18, :132:13, :153:{13,22}
        dstOffset <= dstOffset + {20'h0, {4'h0, kW} * {8'h0, elemBytes}};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :44:21, :56:26, :76:26, :157:{28,33}
      end
      else if (io_start) begin	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
        cntKh <= 8'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:64:22
        dstOffset <= 32'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:76:26
      end
      if (_GEN_1 & khWrap)	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:81:18, :124:{16,30,43}, :125:24, :131:18, :134:19
        cntC <= cWrap ? 16'h0 : cntC + 16'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:65:22, :126:23, :134:19, :135:14, :150:{14,22}
      else if (io_start)	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
        cntC <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:65:22
      if (_GEN_1 & khWrap & cWrap)	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:81:18, :124:{16,30,43}, :125:24, :126:23, :131:18, :134:19, :137:22
        cntOw <= owWrap ? 16'h0 : cntOw + 16'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:66:22, :127:24, :137:22, :138:17, :147:{17,26}
      else if (io_start)	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
        cntOw <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:66:22
      if (~(_GEN_1 & khWrap & cWrap & owWrap) | ohWrap) begin	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:81:18, :124:{16,30,43}, :125:24, :126:23, :127:24, :128:24, :131:18, :134:19, :137:22, :140:24
        if (io_start)	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:17:14
          cntOh <= 16'h0;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:67:22
      end
      else	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:81:18, :124:43, :131:18, :134:19, :137:22, :140:24
        cntOh <= cntOh + 16'h1;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:67:22, :144:28
      running <= ~_GEN_2 & (io_start | running);	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:72:25, :81:18, :117:13, :124:43, :131:18, :134:19, :137:22, :140:24, :141:21, :142:21
      doneReg <= _GEN_2 | ~io_start & doneReg;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:73:25, :81:18, :118:13, :124:43, :131:18, :134:19, :137:22, :140:24, :141:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
      `FIRRTL_BEFORE_INITIAL	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
      automatic logic [31:0] _RANDOM[0:9];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
      `ifdef INIT_RANDOM_PROLOG_	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
        `INIT_RANDOM_PROLOG_	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
        for (logic [3:0] i = 4'h0; i < 4'hA; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
        end	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
        kH = _RANDOM[4'h0][7:0];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :43:21
        kW = _RANDOM[4'h0][15:8];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :43:21, :44:21
        sH = _RANDOM[4'h0][23:16];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :43:21, :45:21
        sW = _RANDOM[4'h0][31:24];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :43:21, :46:21
        pH = _RANDOM[4'h1][7:0];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :47:21
        pW = _RANDOM[4'h1][15:8];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :47:21, :48:21
        dH = _RANDOM[4'h1][23:16];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :47:21, :49:21
        C = _RANDOM[4'h2][15:0];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :51:21
        H = _RANDOM[4'h2][31:16];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :51:21, :52:21
        W = _RANDOM[4'h3][15:0];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :53:21
        outH = _RANDOM[4'h3][31:16];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :53:21, :54:21
        outW = _RANDOM[4'h4][15:0];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :55:21
        elemBytes = _RANDOM[4'h4][19:16];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :55:21, :56:26
        srcBaseReg = {_RANDOM[4'h4][31:20], _RANDOM[4'h5][19:0]};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :55:21, :58:27
        dstBaseReg = {_RANDOM[4'h5][31:20], _RANDOM[4'h6][19:0]};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :58:27, :59:27
        cntKh = _RANDOM[4'h6][27:20];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :59:27, :64:22
        cntC = {_RANDOM[4'h6][31:28], _RANDOM[4'h7][11:0]};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :59:27, :65:22
        cntOw = _RANDOM[4'h7][27:12];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :65:22, :66:22
        cntOh = {_RANDOM[4'h7][31:28], _RANDOM[4'h8][11:0]};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :65:22, :67:22
        running = _RANDOM[4'h8][12];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :67:22, :72:25
        doneReg = _RANDOM[4'h8][13];	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :67:22, :73:25
        dstOffset = {_RANDOM[4'h8][31:14], _RANDOM[4'h9][13:0]};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :67:22, :76:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
      `FIRRTL_AFTER_INITIAL	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_valid = running & ~doneReg;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :72:25, :73:25, :124:33, :197:23
  assign io_srcAddr =
    srcBaseReg
    + ({16'h0, cntOw * {8'h0, sW} - {8'h0, pW}} + {16'h0, cntC} * {16'h0, H} * _GEN_0
       + {16'h0, _ihVal_T_1[15:0]} * _GEN_0) * {28'h0, elemBytes};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :46:21, :48:21, :52:21, :56:26, :58:27, :65:22, :66:22, :166:32, :167:24, :172:25, :173:32, :174:24, :185:{41,63,86}, :186:{23,49,72}, :187:33, :188:{28,38}
  assign io_dstAddr = dstBaseReg + dstOffset;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :59:27, :76:26, :191:28
  assign io_isPad = _ihRaw_T_3 < _GEN | _ihVal_T_1 >= {8'h0, H};	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :52:21, :165:{39,57}, :166:{24,32}, :167:24, :168:24, :169:25
  assign io_done = doneReg;	// src/foragerbee/scala/main/FbIm2colAddrGen.scala:15:7, :73:25
endmodule

