// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Fb_FbDispatcher(	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
  input         clock,	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
                reset,	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
                io_push_valid,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output        io_push_ready,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [2:0]  io_push_payload_op,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [7:0]  io_push_payload_tag,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [2:0]  io_push_payload_dimCount,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [15:0] io_push_payload_shape_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_shape_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_shape_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_shape_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [31:0] io_push_payload_srcStride_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_srcStride_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_srcStride_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_srcStride_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_dstStride_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_dstStride_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_dstStride_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_dstStride_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_srcAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_dstAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [1:0]  io_push_payload_elemBytesLog2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [2:0]  io_push_payload_permVec_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_permVec_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_permVec_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_permVec_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [15:0] io_push_payload_padBefore_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_padBefore_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_padAfter_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_padAfter_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [31:0] io_push_payload_nextDescAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input         io_push_payload_chainMode,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_cvtEnable,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [2:0]  io_push_payload_srcFmt,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_dstFmt,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [31:0] io_push_payload_cvtScale,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_cvtZeroPoint,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [7:0]  io_push_payload_im2colKernel_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colKernel_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colStride_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colStride_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colPad_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colPad_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colDilation_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colDilation_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [15:0] io_push_payload_im2colInShape_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colInShape_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_push_payload_im2colInShape_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [31:0] io_push_payload_sgListAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input  [15:0] io_push_payload_sgEntryCount,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_occupancy,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output        io_pop_0_valid,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input         io_pop_0_ready,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_pop_0_payload_op,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [7:0]  io_pop_0_payload_tag,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_pop_0_payload_dimCount,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [15:0] io_pop_0_payload_shape_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_shape_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_shape_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_shape_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [31:0] io_pop_0_payload_srcStride_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_srcStride_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_srcStride_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_srcStride_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_dstStride_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_dstStride_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_dstStride_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_dstStride_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_srcAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_dstAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [1:0]  io_pop_0_payload_elemBytesLog2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_pop_0_payload_permVec_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_permVec_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_permVec_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_permVec_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [15:0] io_pop_0_payload_padBefore_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_padBefore_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_padAfter_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_padAfter_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output        io_pop_0_payload_cvtEnable,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_pop_0_payload_srcFmt,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_dstFmt,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [31:0] io_pop_0_payload_cvtScale,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_cvtZeroPoint,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_0_payload_sgListAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [15:0] io_pop_0_payload_sgEntryCount,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output        io_pop_1_valid,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input         io_pop_1_ready,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_pop_1_payload_op,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [7:0]  io_pop_1_payload_tag,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_pop_1_payload_dimCount,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [15:0] io_pop_1_payload_shape_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_shape_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_shape_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_shape_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [31:0] io_pop_1_payload_srcStride_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_srcStride_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_srcStride_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_srcStride_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_dstStride_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_dstStride_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_dstStride_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_srcAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_dstAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [1:0]  io_pop_1_payload_elemBytesLog2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_pop_1_payload_permVec_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_permVec_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_permVec_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_permVec_3,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [15:0] io_pop_1_payload_padBefore_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_padBefore_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_padAfter_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_padAfter_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output        io_pop_1_payload_cvtEnable,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [2:0]  io_pop_1_payload_srcFmt,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_dstFmt,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [31:0] io_pop_1_payload_cvtScale,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_cvtZeroPoint,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [7:0]  io_pop_1_payload_im2colKernel_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colKernel_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colStride_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colStride_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colPad_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colPad_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colDilation_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colDilation_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [15:0] io_pop_1_payload_im2colInShape_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colInShape_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_pop_1_payload_im2colInShape_2,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [31:0] io_pop_1_payload_sgListAddr,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  output [15:0] io_pop_1_payload_sgEntryCount,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
  input         io_chBusy_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_chBusy_1,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_chDone_0,	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
                io_chDone_1	// src/foragerbee/scala/main/FbDispatcher.scala:31:14
);

  wire             _fifo_io_pop_valid;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [2:0]       _fifo_io_pop_payload_op;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [7:0]       _fifo_io_pop_payload_tag;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [2:0]       _fifo_io_pop_payload_dimCount;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_shape_0;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_shape_1;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_shape_2;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_shape_3;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_srcStride_0;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_srcStride_1;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_srcStride_2;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_srcStride_3;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_dstStride_1;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_dstStride_2;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_dstStride_3;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_srcAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_dstAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [1:0]       _fifo_io_pop_payload_elemBytesLog2;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [2:0]       _fifo_io_pop_payload_permVec_0;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [2:0]       _fifo_io_pop_payload_permVec_1;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [2:0]       _fifo_io_pop_payload_permVec_2;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [2:0]       _fifo_io_pop_payload_permVec_3;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_padBefore_0;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_padBefore_1;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_padAfter_0;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_padAfter_1;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire             _fifo_io_pop_payload_cvtEnable;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [2:0]       _fifo_io_pop_payload_srcFmt;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [2:0]       _fifo_io_pop_payload_dstFmt;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_cvtScale;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_cvtZeroPoint;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [31:0]      _fifo_io_pop_payload_sgListAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  wire [15:0]      _fifo_io_pop_payload_sgEntryCount;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  reg  [31:0]      infSrcStart_0;	// src/foragerbee/scala/main/FbDispatcher.scala:56:28
  reg  [31:0]      infSrcStart_1;	// src/foragerbee/scala/main/FbDispatcher.scala:56:28
  reg  [31:0]      infSrcEnd_0;	// src/foragerbee/scala/main/FbDispatcher.scala:57:28
  reg  [31:0]      infSrcEnd_1;	// src/foragerbee/scala/main/FbDispatcher.scala:57:28
  reg  [31:0]      infDstStart_0;	// src/foragerbee/scala/main/FbDispatcher.scala:58:28
  reg  [31:0]      infDstStart_1;	// src/foragerbee/scala/main/FbDispatcher.scala:58:28
  reg  [31:0]      infDstEnd_0;	// src/foragerbee/scala/main/FbDispatcher.scala:59:28
  reg  [31:0]      infDstEnd_1;	// src/foragerbee/scala/main/FbDispatcher.scala:59:28
  reg              infValid_0;	// src/foragerbee/scala/main/FbDispatcher.scala:60:28
  reg              infValid_1;	// src/foragerbee/scala/main/FbDispatcher.scala:60:28
  wire [5:0]       eb = 6'h1 << _fifo_io_pop_payload_elemBytesLog2;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :89:21
  wire             isPermute = _fifo_io_pop_payload_op == 3'h2;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :93:26, :104:29
  wire [3:0][31:0] _GEN =
    {{_fifo_io_pop_payload_srcStride_3},
     {_fifo_io_pop_payload_srcStride_2},
     {_fifo_io_pop_payload_srcStride_1},
     {_fifo_io_pop_payload_srcStride_0}};	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :105:23
  wire             newSrcEnd_contributions_active_1 =
    _fifo_io_pop_payload_dimCount > 3'h2;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :104:29
  wire [31:0]      _GEN_0 = {16'h0, _fifo_io_pop_payload_shape_2 - 16'h1};	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :106:{36,43}
  wire [31:0]      _GEN_1 = {16'h0, _fifo_io_pop_payload_shape_3 - 16'h1};	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :106:{36,43}
  wire [31:0]      _GEN_2 = {10'h0, {6'h0, _fifo_io_pop_payload_shape_0} * {16'h0, eb}};	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :89:21, :90:{33,42}, :111:57
  wire             _GEN_3 =
    _fifo_io_pop_payload_op == 3'h4 | _fifo_io_pop_payload_op == 3'h5
    | _fifo_io_pop_payload_op == 3'h3;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :94:25, :95:{32,49,59}, :104:29, :116:8
  wire [31:0]      newSrcEnd =
    _GEN_3
      ? {16'h0, _fifo_io_pop_payload_shape_0} + _fifo_io_pop_payload_srcAddr
      : _GEN_2 + _fifo_io_pop_payload_srcAddr
        + ((|(_fifo_io_pop_payload_dimCount[2:1]))
             ? {16'h0, _fifo_io_pop_payload_shape_1 - 16'h1}
               * (isPermute
                    ? _GEN[_fifo_io_pop_payload_permVec_1[1:0]]
                    : _fifo_io_pop_payload_srcStride_1)
             : 32'h0)
        + (newSrcEnd_contributions_active_1
             ? _GEN_0
               * (isPermute
                    ? _GEN[_fifo_io_pop_payload_permVec_2[1:0]]
                    : _fifo_io_pop_payload_srcStride_2)
             : 32'h0)
        + (_fifo_io_pop_payload_dimCount[2]
             ? _GEN_1
               * (isPermute
                    ? _GEN[_fifo_io_pop_payload_permVec_3[1:0]]
                    : _fifo_io_pop_payload_srcStride_3)
             : 32'h0);	// <stdin>:21027:79, :21035:81, :21043:81, src/foragerbee/scala/main/FbDispatcher.scala:50:20, :90:42, :93:26, :95:49, :104:29, :105:23, :106:{36,43}, :107:10, :110:48, :111:{37,45,57}, :113:{48,67}, :116:8
  wire [63:0]      _GEN_4 =
    {_fifo_io_pop_payload_padBefore_0,
     _fifo_io_pop_payload_padAfter_0,
     _fifo_io_pop_payload_padBefore_1,
     _fifo_io_pop_payload_padAfter_1};	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :123:{33,41,60,68}, :124:{33,41,60}
  wire [31:0]      newDstEnd =
    _GEN_3
      ? {16'h0, _fifo_io_pop_payload_shape_1} + _fifo_io_pop_payload_dstAddr
      : _fifo_io_pop_payload_dstAddr
        + ((|(_fifo_io_pop_payload_dimCount[2:1]))
             ? {14'h0,
                ((|_GEN_4)
                   ? {1'h0,
                      {1'h0, _fifo_io_pop_payload_padBefore_1}
                        + {1'h0, _fifo_io_pop_payload_shape_1}}
                     + {2'h0, _fifo_io_pop_payload_padAfter_1}
                   : {2'h0, _fifo_io_pop_payload_shape_1}) - 18'h1}
               * _fifo_io_pop_payload_dstStride_1
             : 32'h0)
        + (newSrcEnd_contributions_active_1
             ? _GEN_0 * _fifo_io_pop_payload_dstStride_2
             : 32'h0)
        + (_fifo_io_pop_payload_dimCount[2]
             ? _GEN_1 * _fifo_io_pop_payload_dstStride_3
             : 32'h0)
        + ((|_GEN_4)
             ? {8'h0,
                {6'h0,
                 {1'h0,
                  {1'h0, _fifo_io_pop_payload_padBefore_0}
                    + {1'h0, _fifo_io_pop_payload_shape_0}}
                   + {2'h0, _fifo_io_pop_payload_padAfter_0}} * {18'h0, eb}}
             : _GEN_2);	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :89:21, :90:{33,42}, :95:49, :104:29, :106:{36,43}, :111:57, :116:8, :123:{33,41,60,68}, :124:{33,41,60}, :125:{36,52}, :126:{36,52}, :130:{27,47,56}, :133:35, :134:{30,37}, :135:10, :138:48, :139:{37,45,57}, :141:{48,67}, :144:8
  wire             capable_1 = _fifo_io_pop_payload_op != 3'h1;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :89:21, :163:28, :173:20
  wire             capable = _fifo_io_pop_payload_op != 3'h3;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :94:25, :104:29, :173:86
  wire             idle = ~io_chBusy_0 & ~infValid_0;	// src/foragerbee/scala/main/FbDispatcher.scala:60:28, :174:{16,30,33}
  wire             idle_1 = ~io_chBusy_1 & ~infValid_1;	// src/foragerbee/scala/main/FbDispatcher.scala:60:28, :174:{16,30,33}
  wire [1:0]       effectiveEligible =
    {capable_1, capable} == 2'h0 ? {idle_1, idle} : {capable_1 & idle_1, capable & idle};	// src/foragerbee/scala/main/FbDispatcher.scala:94:25, :163:28, :173:{20,86}, :174:30, :177:35, :181:{42,49}, :182:{30,61,85}
  wire             canDispatch =
    _fifo_io_pop_valid
    & {infValid_1
         & (~(newSrcEnd <= infDstStart_1 | infDstEnd_1 <= _fifo_io_pop_payload_srcAddr)
            | ~(newDstEnd <= infSrcStart_1 | infSrcEnd_1 <= _fifo_io_pop_payload_dstAddr)
            | ~(newDstEnd <= infDstStart_1
                | infDstEnd_1 <= _fifo_io_pop_payload_dstAddr)),
       infValid_0
         & (~(newSrcEnd <= infDstStart_0 | infDstEnd_0 <= _fifo_io_pop_payload_srcAddr)
            | ~(newDstEnd <= infSrcStart_0 | infSrcEnd_0 <= _fifo_io_pop_payload_dstAddr)
            | ~(newDstEnd <= infDstStart_0
                | infDstEnd_0 <= _fifo_io_pop_payload_dstAddr))} == 2'h0
    & (|effectiveEligible);	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :56:28, :57:28, :58:28, :59:28, :60:28, :116:8, :144:8, :150:{5,12,22,30}, :158:{35,43,50}, :160:{33,40}, :182:30, :185:39, :189:{30,46}
  wire             fifo_io_pop_ready =
    canDispatch & (effectiveEligible[0] ? io_pop_0_ready : io_pop_1_ready);	// src/foragerbee/scala/main/FbDispatcher.scala:182:30, :189:{30,46}, :196:21, :198:21, :204:23, src/main/scala/chisel3/util/OneHot.scala:48:45
  always @(posedge clock) begin	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
    if (reset) begin	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
      infSrcStart_0 <= 32'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:56:28
      infSrcStart_1 <= 32'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:56:28
      infSrcEnd_0 <= 32'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:57:28
      infSrcEnd_1 <= 32'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:57:28
      infDstStart_0 <= 32'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:58:28
      infDstStart_1 <= 32'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:58:28
      infDstEnd_0 <= 32'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:59:28
      infDstEnd_1 <= 32'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:59:28
      infValid_0 <= 1'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:60:28
      infValid_1 <= 1'h0;	// src/foragerbee/scala/main/FbDispatcher.scala:60:28
    end
    else begin	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
      automatic logic _GEN_5 = _fifo_io_pop_valid & fifo_io_pop_ready;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :196:21, :198:21, :204:23, src/utils/Stream/Stream.scala:43:26
      automatic logic _GEN_6 = canDispatch & _GEN_5 & effectiveEligible[0];	// src/foragerbee/scala/main/FbDispatcher.scala:56:28, :182:30, :189:{30,46}, :198:21, :207:28, :208:36, src/main/scala/chisel3/util/OneHot.scala:48:45, src/utils/Stream/Stream.scala:43:26
      automatic logic _GEN_7 = canDispatch & _GEN_5 & ~(effectiveEligible[0]);	// src/foragerbee/scala/main/FbDispatcher.scala:56:28, :182:30, :189:{30,46}, :198:21, :207:28, :208:36, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:48:45, src/utils/Stream/Stream.scala:43:26
      if (_GEN_6) begin	// src/foragerbee/scala/main/FbDispatcher.scala:56:28, :198:21, :207:28, :208:36
        infSrcStart_0 <= _fifo_io_pop_payload_srcAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :56:28
        infSrcEnd_0 <= newSrcEnd;	// src/foragerbee/scala/main/FbDispatcher.scala:57:28, :116:8
        infDstStart_0 <= _fifo_io_pop_payload_dstAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :58:28
        infDstEnd_0 <= newDstEnd;	// src/foragerbee/scala/main/FbDispatcher.scala:59:28, :144:8
      end
      if (_GEN_7) begin	// src/foragerbee/scala/main/FbDispatcher.scala:56:28, :198:21, :207:28, :208:36
        infSrcStart_1 <= _fifo_io_pop_payload_srcAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :56:28
        infSrcEnd_1 <= newSrcEnd;	// src/foragerbee/scala/main/FbDispatcher.scala:57:28, :116:8
        infDstStart_1 <= _fifo_io_pop_payload_dstAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:50:20, :58:28
        infDstEnd_1 <= newDstEnd;	// src/foragerbee/scala/main/FbDispatcher.scala:59:28, :144:8
      end
      infValid_0 <= _GEN_6 | ~io_chDone_0 & infValid_0;	// src/foragerbee/scala/main/FbDispatcher.scala:56:28, :60:28, :64:24, :65:19, :198:21, :207:28, :208:36, :212:36
      infValid_1 <= _GEN_7 | ~io_chDone_1 & infValid_1;	// src/foragerbee/scala/main/FbDispatcher.scala:56:28, :60:28, :64:24, :65:19, :198:21, :207:28, :208:36, :212:36
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
      `FIRRTL_BEFORE_INITIAL	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
      automatic logic [31:0] _RANDOM[0:8];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
      `ifdef INIT_RANDOM_PROLOG_	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
        `INIT_RANDOM_PROLOG_	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
        end	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
        infSrcStart_0 = _RANDOM[4'h0];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :56:28
        infSrcStart_1 = _RANDOM[4'h1];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :56:28
        infSrcEnd_0 = _RANDOM[4'h2];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :57:28
        infSrcEnd_1 = _RANDOM[4'h3];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :57:28
        infDstStart_0 = _RANDOM[4'h4];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :58:28
        infDstStart_1 = _RANDOM[4'h5];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :58:28
        infDstEnd_0 = _RANDOM[4'h6];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :59:28
        infDstEnd_1 = _RANDOM[4'h7];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :59:28
        infValid_0 = _RANDOM[4'h8][0];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :60:28
        infValid_1 = _RANDOM[4'h8][1];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :60:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
      `FIRRTL_AFTER_INITIAL	// src/foragerbee/scala/main/FbDispatcher.scala:30:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Fb_StreamFifo fifo (	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
    .clock                            (clock),
    .reset                            (reset),
    .io_push_valid                    (io_push_valid),
    .io_push_ready                    (io_push_ready),
    .io_push_payload_op               (io_push_payload_op),
    .io_push_payload_tag              (io_push_payload_tag),
    .io_push_payload_dimCount         (io_push_payload_dimCount),
    .io_push_payload_shape_0          (io_push_payload_shape_0),
    .io_push_payload_shape_1          (io_push_payload_shape_1),
    .io_push_payload_shape_2          (io_push_payload_shape_2),
    .io_push_payload_shape_3          (io_push_payload_shape_3),
    .io_push_payload_srcStride_0      (io_push_payload_srcStride_0),
    .io_push_payload_srcStride_1      (io_push_payload_srcStride_1),
    .io_push_payload_srcStride_2      (io_push_payload_srcStride_2),
    .io_push_payload_srcStride_3      (io_push_payload_srcStride_3),
    .io_push_payload_dstStride_0      (io_push_payload_dstStride_0),
    .io_push_payload_dstStride_1      (io_push_payload_dstStride_1),
    .io_push_payload_dstStride_2      (io_push_payload_dstStride_2),
    .io_push_payload_dstStride_3      (io_push_payload_dstStride_3),
    .io_push_payload_srcAddr          (io_push_payload_srcAddr),
    .io_push_payload_dstAddr          (io_push_payload_dstAddr),
    .io_push_payload_elemBytesLog2    (io_push_payload_elemBytesLog2),
    .io_push_payload_permVec_0        (io_push_payload_permVec_0),
    .io_push_payload_permVec_1        (io_push_payload_permVec_1),
    .io_push_payload_permVec_2        (io_push_payload_permVec_2),
    .io_push_payload_permVec_3        (io_push_payload_permVec_3),
    .io_push_payload_padBefore_0      (io_push_payload_padBefore_0),
    .io_push_payload_padBefore_1      (io_push_payload_padBefore_1),
    .io_push_payload_padAfter_0       (io_push_payload_padAfter_0),
    .io_push_payload_padAfter_1       (io_push_payload_padAfter_1),
    .io_push_payload_nextDescAddr     (io_push_payload_nextDescAddr),
    .io_push_payload_chainMode        (io_push_payload_chainMode),
    .io_push_payload_cvtEnable        (io_push_payload_cvtEnable),
    .io_push_payload_srcFmt           (io_push_payload_srcFmt),
    .io_push_payload_dstFmt           (io_push_payload_dstFmt),
    .io_push_payload_cvtScale         (io_push_payload_cvtScale),
    .io_push_payload_cvtZeroPoint     (io_push_payload_cvtZeroPoint),
    .io_push_payload_im2colKernel_0   (io_push_payload_im2colKernel_0),
    .io_push_payload_im2colKernel_1   (io_push_payload_im2colKernel_1),
    .io_push_payload_im2colStride_0   (io_push_payload_im2colStride_0),
    .io_push_payload_im2colStride_1   (io_push_payload_im2colStride_1),
    .io_push_payload_im2colPad_0      (io_push_payload_im2colPad_0),
    .io_push_payload_im2colPad_1      (io_push_payload_im2colPad_1),
    .io_push_payload_im2colDilation_0 (io_push_payload_im2colDilation_0),
    .io_push_payload_im2colDilation_1 (io_push_payload_im2colDilation_1),
    .io_push_payload_im2colInShape_0  (io_push_payload_im2colInShape_0),
    .io_push_payload_im2colInShape_1  (io_push_payload_im2colInShape_1),
    .io_push_payload_im2colInShape_2  (io_push_payload_im2colInShape_2),
    .io_push_payload_sgListAddr       (io_push_payload_sgListAddr),
    .io_push_payload_sgEntryCount     (io_push_payload_sgEntryCount),
    .io_pop_valid                     (_fifo_io_pop_valid),
    .io_pop_ready                     (fifo_io_pop_ready),	// src/foragerbee/scala/main/FbDispatcher.scala:196:21, :198:21, :204:23
    .io_pop_payload_op                (_fifo_io_pop_payload_op),
    .io_pop_payload_tag               (_fifo_io_pop_payload_tag),
    .io_pop_payload_dimCount          (_fifo_io_pop_payload_dimCount),
    .io_pop_payload_shape_0           (_fifo_io_pop_payload_shape_0),
    .io_pop_payload_shape_1           (_fifo_io_pop_payload_shape_1),
    .io_pop_payload_shape_2           (_fifo_io_pop_payload_shape_2),
    .io_pop_payload_shape_3           (_fifo_io_pop_payload_shape_3),
    .io_pop_payload_srcStride_0       (_fifo_io_pop_payload_srcStride_0),
    .io_pop_payload_srcStride_1       (_fifo_io_pop_payload_srcStride_1),
    .io_pop_payload_srcStride_2       (_fifo_io_pop_payload_srcStride_2),
    .io_pop_payload_srcStride_3       (_fifo_io_pop_payload_srcStride_3),
    .io_pop_payload_dstStride_0       (io_pop_0_payload_dstStride_0),
    .io_pop_payload_dstStride_1       (_fifo_io_pop_payload_dstStride_1),
    .io_pop_payload_dstStride_2       (_fifo_io_pop_payload_dstStride_2),
    .io_pop_payload_dstStride_3       (_fifo_io_pop_payload_dstStride_3),
    .io_pop_payload_srcAddr           (_fifo_io_pop_payload_srcAddr),
    .io_pop_payload_dstAddr           (_fifo_io_pop_payload_dstAddr),
    .io_pop_payload_elemBytesLog2     (_fifo_io_pop_payload_elemBytesLog2),
    .io_pop_payload_permVec_0         (_fifo_io_pop_payload_permVec_0),
    .io_pop_payload_permVec_1         (_fifo_io_pop_payload_permVec_1),
    .io_pop_payload_permVec_2         (_fifo_io_pop_payload_permVec_2),
    .io_pop_payload_permVec_3         (_fifo_io_pop_payload_permVec_3),
    .io_pop_payload_padBefore_0       (_fifo_io_pop_payload_padBefore_0),
    .io_pop_payload_padBefore_1       (_fifo_io_pop_payload_padBefore_1),
    .io_pop_payload_padAfter_0        (_fifo_io_pop_payload_padAfter_0),
    .io_pop_payload_padAfter_1        (_fifo_io_pop_payload_padAfter_1),
    .io_pop_payload_cvtEnable         (_fifo_io_pop_payload_cvtEnable),
    .io_pop_payload_srcFmt            (_fifo_io_pop_payload_srcFmt),
    .io_pop_payload_dstFmt            (_fifo_io_pop_payload_dstFmt),
    .io_pop_payload_cvtScale          (_fifo_io_pop_payload_cvtScale),
    .io_pop_payload_cvtZeroPoint      (_fifo_io_pop_payload_cvtZeroPoint),
    .io_pop_payload_im2colKernel_0    (io_pop_1_payload_im2colKernel_0),
    .io_pop_payload_im2colKernel_1    (io_pop_1_payload_im2colKernel_1),
    .io_pop_payload_im2colStride_0    (io_pop_1_payload_im2colStride_0),
    .io_pop_payload_im2colStride_1    (io_pop_1_payload_im2colStride_1),
    .io_pop_payload_im2colPad_0       (io_pop_1_payload_im2colPad_0),
    .io_pop_payload_im2colPad_1       (io_pop_1_payload_im2colPad_1),
    .io_pop_payload_im2colDilation_0  (io_pop_1_payload_im2colDilation_0),
    .io_pop_payload_im2colDilation_1  (io_pop_1_payload_im2colDilation_1),
    .io_pop_payload_im2colInShape_0   (io_pop_1_payload_im2colInShape_0),
    .io_pop_payload_im2colInShape_1   (io_pop_1_payload_im2colInShape_1),
    .io_pop_payload_im2colInShape_2   (io_pop_1_payload_im2colInShape_2),
    .io_pop_payload_sgListAddr        (_fifo_io_pop_payload_sgListAddr),
    .io_pop_payload_sgEntryCount      (_fifo_io_pop_payload_sgEntryCount),
    .io_occupancy                     (io_occupancy)
  );	// src/foragerbee/scala/main/FbDispatcher.scala:50:20
  assign io_pop_0_valid = canDispatch & effectiveEligible[0];	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :182:30, :189:{30,46}, :193:21, :198:21, :201:23, src/main/scala/chisel3/util/OneHot.scala:48:45
  assign io_pop_0_payload_op = _fifo_io_pop_payload_op;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_tag = _fifo_io_pop_payload_tag;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_dimCount = _fifo_io_pop_payload_dimCount;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_shape_0 = _fifo_io_pop_payload_shape_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_shape_1 = _fifo_io_pop_payload_shape_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_shape_2 = _fifo_io_pop_payload_shape_2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_shape_3 = _fifo_io_pop_payload_shape_3;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_srcStride_0 = _fifo_io_pop_payload_srcStride_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_srcStride_1 = _fifo_io_pop_payload_srcStride_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_srcStride_2 = _fifo_io_pop_payload_srcStride_2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_srcStride_3 = _fifo_io_pop_payload_srcStride_3;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_dstStride_1 = _fifo_io_pop_payload_dstStride_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_dstStride_2 = _fifo_io_pop_payload_dstStride_2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_dstStride_3 = _fifo_io_pop_payload_dstStride_3;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_srcAddr = _fifo_io_pop_payload_srcAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_dstAddr = _fifo_io_pop_payload_dstAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_elemBytesLog2 = _fifo_io_pop_payload_elemBytesLog2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_permVec_0 = _fifo_io_pop_payload_permVec_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_permVec_1 = _fifo_io_pop_payload_permVec_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_permVec_2 = _fifo_io_pop_payload_permVec_2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_permVec_3 = _fifo_io_pop_payload_permVec_3;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_padBefore_0 = _fifo_io_pop_payload_padBefore_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_padBefore_1 = _fifo_io_pop_payload_padBefore_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_padAfter_0 = _fifo_io_pop_payload_padAfter_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_padAfter_1 = _fifo_io_pop_payload_padAfter_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_cvtEnable = _fifo_io_pop_payload_cvtEnable;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_srcFmt = _fifo_io_pop_payload_srcFmt;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_dstFmt = _fifo_io_pop_payload_dstFmt;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_cvtScale = _fifo_io_pop_payload_cvtScale;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_cvtZeroPoint = _fifo_io_pop_payload_cvtZeroPoint;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_sgListAddr = _fifo_io_pop_payload_sgListAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_0_payload_sgEntryCount = _fifo_io_pop_payload_sgEntryCount;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_valid = canDispatch & ~(effectiveEligible[0]);	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :182:30, :189:{30,46}, :193:21, :198:21, :201:23, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:48:45
  assign io_pop_1_payload_op = _fifo_io_pop_payload_op;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_tag = _fifo_io_pop_payload_tag;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_dimCount = _fifo_io_pop_payload_dimCount;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_shape_0 = _fifo_io_pop_payload_shape_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_shape_1 = _fifo_io_pop_payload_shape_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_shape_2 = _fifo_io_pop_payload_shape_2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_shape_3 = _fifo_io_pop_payload_shape_3;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_srcStride_0 = _fifo_io_pop_payload_srcStride_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_srcStride_1 = _fifo_io_pop_payload_srcStride_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_srcStride_2 = _fifo_io_pop_payload_srcStride_2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_srcStride_3 = _fifo_io_pop_payload_srcStride_3;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_dstStride_1 = _fifo_io_pop_payload_dstStride_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_dstStride_2 = _fifo_io_pop_payload_dstStride_2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_dstStride_3 = _fifo_io_pop_payload_dstStride_3;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_srcAddr = _fifo_io_pop_payload_srcAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_dstAddr = _fifo_io_pop_payload_dstAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_elemBytesLog2 = _fifo_io_pop_payload_elemBytesLog2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_permVec_0 = _fifo_io_pop_payload_permVec_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_permVec_1 = _fifo_io_pop_payload_permVec_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_permVec_2 = _fifo_io_pop_payload_permVec_2;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_permVec_3 = _fifo_io_pop_payload_permVec_3;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_padBefore_0 = _fifo_io_pop_payload_padBefore_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_padBefore_1 = _fifo_io_pop_payload_padBefore_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_padAfter_0 = _fifo_io_pop_payload_padAfter_0;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_padAfter_1 = _fifo_io_pop_payload_padAfter_1;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_cvtEnable = _fifo_io_pop_payload_cvtEnable;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_srcFmt = _fifo_io_pop_payload_srcFmt;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_dstFmt = _fifo_io_pop_payload_dstFmt;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_cvtScale = _fifo_io_pop_payload_cvtScale;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_cvtZeroPoint = _fifo_io_pop_payload_cvtZeroPoint;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_sgListAddr = _fifo_io_pop_payload_sgListAddr;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
  assign io_pop_1_payload_sgEntryCount = _fifo_io_pop_payload_sgEntryCount;	// src/foragerbee/scala/main/FbDispatcher.scala:30:7, :50:20
endmodule

