// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Fb_StreamArbiter(	// src/utils/Stream/Stream.scala:388:7
  input        clock,	// src/utils/Stream/Stream.scala:388:7
               reset,	// src/utils/Stream/Stream.scala:388:7
               io_inputs_0_valid,	// src/utils/Stream/Stream.scala:393:14
  output       io_inputs_0_ready,	// src/utils/Stream/Stream.scala:393:14
  input  [7:0] io_inputs_0_payload_tag,	// src/utils/Stream/Stream.scala:393:14
  input        io_inputs_0_payload_err,	// src/utils/Stream/Stream.scala:393:14
               io_inputs_1_valid,	// src/utils/Stream/Stream.scala:393:14
  output       io_inputs_1_ready,	// src/utils/Stream/Stream.scala:393:14
  input  [7:0] io_inputs_1_payload_tag,	// src/utils/Stream/Stream.scala:393:14
  input        io_inputs_1_payload_err,	// src/utils/Stream/Stream.scala:393:14
  output       io_output_valid,	// src/utils/Stream/Stream.scala:393:14
  input        io_output_ready,	// src/utils/Stream/Stream.scala:393:14
  output [7:0] io_output_payload_tag,	// src/utils/Stream/Stream.scala:393:14
  output       io_output_payload_err	// src/utils/Stream/Stream.scala:393:14
);

  wire       maskProposal_1;	// src/utils/Stream/Stream.scala:435:79
  wire       maskProposal_0;	// src/utils/Stream/Stream.scala:435:79
  reg        locked;	// src/utils/Stream/Stream.scala:400:23
  reg        maskLocked_0;	// src/utils/Stream/Stream.scala:402:27
  reg        maskLocked_1;	// src/utils/Stream/Stream.scala:402:27
  wire       maskRouted_0 = locked ? maskLocked_0 : maskProposal_0;	// src/utils/Stream/Stream.scala:400:23, :402:27, :403:23, :435:79
  wire       maskRouted_1 = locked ? maskLocked_1 : maskProposal_1;	// src/utils/Stream/Stream.scala:400:23, :402:27, :403:23, :435:79
  wire       io_output_valid_0 =
    io_inputs_0_valid & maskRouted_0 | io_inputs_1_valid & maskRouted_1;	// src/utils/Stream/Stream.scala:403:23, :407:{79,95}
  wire [3:0] _doubleGrants_T_2 =
    ~({io_inputs_1_valid, io_inputs_0_valid, io_inputs_1_valid, io_inputs_0_valid}
      - {2'h0, maskLocked_0, maskLocked_1});	// src/utils/Stream/Stream.scala:352:{41,58}, :402:27
  wire [1:0] _GEN = {io_inputs_1_valid, io_inputs_0_valid};	// src/utils/Stream/Stream.scala:352:39, :353:17
  wire [1:0] _GEN_0 = _GEN & _doubleGrants_T_2[3:2] | _GEN & _doubleGrants_T_2[1:0];	// src/utils/Stream/Stream.scala:352:{39,41}, :353:{17,40,54}
  assign maskProposal_0 = _GEN_0[0];	// src/utils/Stream/Stream.scala:353:40, :435:79
  assign maskProposal_1 = _GEN_0[1];	// src/utils/Stream/Stream.scala:353:40, :435:79
  always @(posedge clock) begin	// src/utils/Stream/Stream.scala:388:7
    if (reset) begin	// src/utils/Stream/Stream.scala:388:7
      locked <= 1'h0;	// src/utils/Stream/Stream.scala:388:7, :400:23
      maskLocked_0 <= 1'h1;	// src/utils/Stream/Stream.scala:388:7, :402:27
      maskLocked_1 <= 1'h0;	// src/utils/Stream/Stream.scala:388:7, :402:27
    end
    else begin	// src/utils/Stream/Stream.scala:388:7
      locked <= ~(io_output_valid_0 & io_output_ready) & (io_output_valid_0 | locked);	// src/utils/Stream/Stream.scala:43:26, :400:23, :407:95, :460:{34,48}, :461:{33,47}
      if (~io_output_valid_0 | locked) begin	// src/utils/Stream/Stream.scala:400:23, :402:27, :405:{25,38}, :407:95
      end
      else begin	// src/utils/Stream/Stream.scala:402:27, :405:{25,38}
        maskLocked_0 <= maskProposal_0;	// src/utils/Stream/Stream.scala:402:27, :435:79
        maskLocked_1 <= maskProposal_1;	// src/utils/Stream/Stream.scala:402:27, :435:79
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/utils/Stream/Stream.scala:388:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/utils/Stream/Stream.scala:388:7
      `FIRRTL_BEFORE_INITIAL	// src/utils/Stream/Stream.scala:388:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/utils/Stream/Stream.scala:388:7
      automatic logic [31:0] _RANDOM[0:0];	// src/utils/Stream/Stream.scala:388:7
      `ifdef INIT_RANDOM_PROLOG_	// src/utils/Stream/Stream.scala:388:7
        `INIT_RANDOM_PROLOG_	// src/utils/Stream/Stream.scala:388:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/utils/Stream/Stream.scala:388:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/utils/Stream/Stream.scala:388:7
        locked = _RANDOM[/*Zero width*/ 1'b0][0];	// src/utils/Stream/Stream.scala:388:7, :400:23
        maskLocked_0 = _RANDOM[/*Zero width*/ 1'b0][1];	// src/utils/Stream/Stream.scala:388:7, :400:23, :402:27
        maskLocked_1 = _RANDOM[/*Zero width*/ 1'b0][2];	// src/utils/Stream/Stream.scala:388:7, :400:23, :402:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/utils/Stream/Stream.scala:388:7
      `FIRRTL_AFTER_INITIAL	// src/utils/Stream/Stream.scala:388:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_inputs_0_ready = maskRouted_0 & io_output_ready;	// src/utils/Stream/Stream.scala:388:7, :403:23, :410:27
  assign io_inputs_1_ready = maskRouted_1 & io_output_ready;	// src/utils/Stream/Stream.scala:388:7, :403:23, :410:27
  assign io_output_valid = io_output_valid_0;	// src/utils/Stream/Stream.scala:388:7, :407:95
  assign io_output_payload_tag =
    (maskRouted_0 ? io_inputs_0_payload_tag : 8'h0)
    | (maskRouted_1 ? io_inputs_1_payload_tag : 8'h0);	// src/utils/Stream/Stream.scala:388:7, :403:23, :408:29
  assign io_output_payload_err =
    maskRouted_0 & io_inputs_0_payload_err | maskRouted_1 & io_inputs_1_payload_err;	// src/utils/Stream/Stream.scala:388:7, :403:23, :408:29
endmodule

