// Generated by CIRCT firtool-1.149.0
module Fb_StreamFifo(	// src/utils/Stream/Stream.scala:361:7
  input         clock,	// src/utils/Stream/Stream.scala:361:7
                reset,	// src/utils/Stream/Stream.scala:361:7
                io_push_valid,	// src/utils/Stream/Stream.scala:363:14
  output        io_push_ready,	// src/utils/Stream/Stream.scala:363:14
  input  [2:0]  io_push_payload_op,	// src/utils/Stream/Stream.scala:363:14
  input  [7:0]  io_push_payload_tag,	// src/utils/Stream/Stream.scala:363:14
  input  [2:0]  io_push_payload_dimCount,	// src/utils/Stream/Stream.scala:363:14
  input  [15:0] io_push_payload_shape_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_shape_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_shape_2,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_shape_3,	// src/utils/Stream/Stream.scala:363:14
  input  [31:0] io_push_payload_srcStride_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_srcStride_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_srcStride_2,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_srcStride_3,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_dstStride_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_dstStride_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_dstStride_2,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_dstStride_3,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_srcAddr,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_dstAddr,	// src/utils/Stream/Stream.scala:363:14
  input  [1:0]  io_push_payload_elemBytesLog2,	// src/utils/Stream/Stream.scala:363:14
  input  [2:0]  io_push_payload_permVec_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_permVec_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_permVec_2,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_permVec_3,	// src/utils/Stream/Stream.scala:363:14
  input  [15:0] io_push_payload_padBefore_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_padBefore_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_padAfter_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_padAfter_1,	// src/utils/Stream/Stream.scala:363:14
  input  [31:0] io_push_payload_nextDescAddr,	// src/utils/Stream/Stream.scala:363:14
  input         io_push_payload_chainMode,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_cvtEnable,	// src/utils/Stream/Stream.scala:363:14
  input  [2:0]  io_push_payload_srcFmt,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_dstFmt,	// src/utils/Stream/Stream.scala:363:14
  input  [31:0] io_push_payload_cvtScale,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_cvtZeroPoint,	// src/utils/Stream/Stream.scala:363:14
  input  [7:0]  io_push_payload_im2colKernel_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colKernel_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colStride_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colStride_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colPad_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colPad_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colDilation_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colDilation_1,	// src/utils/Stream/Stream.scala:363:14
  input  [15:0] io_push_payload_im2colInShape_0,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colInShape_1,	// src/utils/Stream/Stream.scala:363:14
                io_push_payload_im2colInShape_2,	// src/utils/Stream/Stream.scala:363:14
  input  [31:0] io_push_payload_sgListAddr,	// src/utils/Stream/Stream.scala:363:14
  input  [15:0] io_push_payload_sgEntryCount,	// src/utils/Stream/Stream.scala:363:14
  output        io_pop_valid,	// src/utils/Stream/Stream.scala:363:14
  input         io_pop_ready,	// src/utils/Stream/Stream.scala:363:14
  output [2:0]  io_pop_payload_op,	// src/utils/Stream/Stream.scala:363:14
  output [7:0]  io_pop_payload_tag,	// src/utils/Stream/Stream.scala:363:14
  output [2:0]  io_pop_payload_dimCount,	// src/utils/Stream/Stream.scala:363:14
  output [15:0] io_pop_payload_shape_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_shape_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_shape_2,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_shape_3,	// src/utils/Stream/Stream.scala:363:14
  output [31:0] io_pop_payload_srcStride_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_srcStride_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_srcStride_2,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_srcStride_3,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_dstStride_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_dstStride_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_dstStride_2,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_dstStride_3,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_srcAddr,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_dstAddr,	// src/utils/Stream/Stream.scala:363:14
  output [1:0]  io_pop_payload_elemBytesLog2,	// src/utils/Stream/Stream.scala:363:14
  output [2:0]  io_pop_payload_permVec_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_permVec_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_permVec_2,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_permVec_3,	// src/utils/Stream/Stream.scala:363:14
  output [15:0] io_pop_payload_padBefore_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_padBefore_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_padAfter_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_padAfter_1,	// src/utils/Stream/Stream.scala:363:14
  output        io_pop_payload_cvtEnable,	// src/utils/Stream/Stream.scala:363:14
  output [2:0]  io_pop_payload_srcFmt,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_dstFmt,	// src/utils/Stream/Stream.scala:363:14
  output [31:0] io_pop_payload_cvtScale,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_cvtZeroPoint,	// src/utils/Stream/Stream.scala:363:14
  output [7:0]  io_pop_payload_im2colKernel_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colKernel_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colStride_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colStride_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colPad_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colPad_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colDilation_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colDilation_1,	// src/utils/Stream/Stream.scala:363:14
  output [15:0] io_pop_payload_im2colInShape_0,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colInShape_1,	// src/utils/Stream/Stream.scala:363:14
                io_pop_payload_im2colInShape_2,	// src/utils/Stream/Stream.scala:363:14
  output [31:0] io_pop_payload_sgListAddr,	// src/utils/Stream/Stream.scala:363:14
  output [15:0] io_pop_payload_sgEntryCount,	// src/utils/Stream/Stream.scala:363:14
  output [2:0]  io_occupancy	// src/utils/Stream/Stream.scala:363:14
);

  Fb_Queue4_FbCmd queue (	// src/utils/Stream/Stream.scala:371:21
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (io_push_ready),
    .io_enq_valid                 (io_push_valid),
    .io_enq_bits_op               (io_push_payload_op),
    .io_enq_bits_tag              (io_push_payload_tag),
    .io_enq_bits_dimCount         (io_push_payload_dimCount),
    .io_enq_bits_shape_0          (io_push_payload_shape_0),
    .io_enq_bits_shape_1          (io_push_payload_shape_1),
    .io_enq_bits_shape_2          (io_push_payload_shape_2),
    .io_enq_bits_shape_3          (io_push_payload_shape_3),
    .io_enq_bits_srcStride_0      (io_push_payload_srcStride_0),
    .io_enq_bits_srcStride_1      (io_push_payload_srcStride_1),
    .io_enq_bits_srcStride_2      (io_push_payload_srcStride_2),
    .io_enq_bits_srcStride_3      (io_push_payload_srcStride_3),
    .io_enq_bits_dstStride_0      (io_push_payload_dstStride_0),
    .io_enq_bits_dstStride_1      (io_push_payload_dstStride_1),
    .io_enq_bits_dstStride_2      (io_push_payload_dstStride_2),
    .io_enq_bits_dstStride_3      (io_push_payload_dstStride_3),
    .io_enq_bits_srcAddr          (io_push_payload_srcAddr),
    .io_enq_bits_dstAddr          (io_push_payload_dstAddr),
    .io_enq_bits_elemBytesLog2    (io_push_payload_elemBytesLog2),
    .io_enq_bits_permVec_0        (io_push_payload_permVec_0),
    .io_enq_bits_permVec_1        (io_push_payload_permVec_1),
    .io_enq_bits_permVec_2        (io_push_payload_permVec_2),
    .io_enq_bits_permVec_3        (io_push_payload_permVec_3),
    .io_enq_bits_padBefore_0      (io_push_payload_padBefore_0),
    .io_enq_bits_padBefore_1      (io_push_payload_padBefore_1),
    .io_enq_bits_padAfter_0       (io_push_payload_padAfter_0),
    .io_enq_bits_padAfter_1       (io_push_payload_padAfter_1),
    .io_enq_bits_nextDescAddr     (io_push_payload_nextDescAddr),
    .io_enq_bits_chainMode        (io_push_payload_chainMode),
    .io_enq_bits_cvtEnable        (io_push_payload_cvtEnable),
    .io_enq_bits_srcFmt           (io_push_payload_srcFmt),
    .io_enq_bits_dstFmt           (io_push_payload_dstFmt),
    .io_enq_bits_cvtScale         (io_push_payload_cvtScale),
    .io_enq_bits_cvtZeroPoint     (io_push_payload_cvtZeroPoint),
    .io_enq_bits_im2colKernel_0   (io_push_payload_im2colKernel_0),
    .io_enq_bits_im2colKernel_1   (io_push_payload_im2colKernel_1),
    .io_enq_bits_im2colStride_0   (io_push_payload_im2colStride_0),
    .io_enq_bits_im2colStride_1   (io_push_payload_im2colStride_1),
    .io_enq_bits_im2colPad_0      (io_push_payload_im2colPad_0),
    .io_enq_bits_im2colPad_1      (io_push_payload_im2colPad_1),
    .io_enq_bits_im2colDilation_0 (io_push_payload_im2colDilation_0),
    .io_enq_bits_im2colDilation_1 (io_push_payload_im2colDilation_1),
    .io_enq_bits_im2colInShape_0  (io_push_payload_im2colInShape_0),
    .io_enq_bits_im2colInShape_1  (io_push_payload_im2colInShape_1),
    .io_enq_bits_im2colInShape_2  (io_push_payload_im2colInShape_2),
    .io_enq_bits_sgListAddr       (io_push_payload_sgListAddr),
    .io_enq_bits_sgEntryCount     (io_push_payload_sgEntryCount),
    .io_deq_ready                 (io_pop_ready),
    .io_deq_valid                 (io_pop_valid),
    .io_deq_bits_op               (io_pop_payload_op),
    .io_deq_bits_tag              (io_pop_payload_tag),
    .io_deq_bits_dimCount         (io_pop_payload_dimCount),
    .io_deq_bits_shape_0          (io_pop_payload_shape_0),
    .io_deq_bits_shape_1          (io_pop_payload_shape_1),
    .io_deq_bits_shape_2          (io_pop_payload_shape_2),
    .io_deq_bits_shape_3          (io_pop_payload_shape_3),
    .io_deq_bits_srcStride_0      (io_pop_payload_srcStride_0),
    .io_deq_bits_srcStride_1      (io_pop_payload_srcStride_1),
    .io_deq_bits_srcStride_2      (io_pop_payload_srcStride_2),
    .io_deq_bits_srcStride_3      (io_pop_payload_srcStride_3),
    .io_deq_bits_dstStride_0      (io_pop_payload_dstStride_0),
    .io_deq_bits_dstStride_1      (io_pop_payload_dstStride_1),
    .io_deq_bits_dstStride_2      (io_pop_payload_dstStride_2),
    .io_deq_bits_dstStride_3      (io_pop_payload_dstStride_3),
    .io_deq_bits_srcAddr          (io_pop_payload_srcAddr),
    .io_deq_bits_dstAddr          (io_pop_payload_dstAddr),
    .io_deq_bits_elemBytesLog2    (io_pop_payload_elemBytesLog2),
    .io_deq_bits_permVec_0        (io_pop_payload_permVec_0),
    .io_deq_bits_permVec_1        (io_pop_payload_permVec_1),
    .io_deq_bits_permVec_2        (io_pop_payload_permVec_2),
    .io_deq_bits_permVec_3        (io_pop_payload_permVec_3),
    .io_deq_bits_padBefore_0      (io_pop_payload_padBefore_0),
    .io_deq_bits_padBefore_1      (io_pop_payload_padBefore_1),
    .io_deq_bits_padAfter_0       (io_pop_payload_padAfter_0),
    .io_deq_bits_padAfter_1       (io_pop_payload_padAfter_1),
    .io_deq_bits_cvtEnable        (io_pop_payload_cvtEnable),
    .io_deq_bits_srcFmt           (io_pop_payload_srcFmt),
    .io_deq_bits_dstFmt           (io_pop_payload_dstFmt),
    .io_deq_bits_cvtScale         (io_pop_payload_cvtScale),
    .io_deq_bits_cvtZeroPoint     (io_pop_payload_cvtZeroPoint),
    .io_deq_bits_im2colKernel_0   (io_pop_payload_im2colKernel_0),
    .io_deq_bits_im2colKernel_1   (io_pop_payload_im2colKernel_1),
    .io_deq_bits_im2colStride_0   (io_pop_payload_im2colStride_0),
    .io_deq_bits_im2colStride_1   (io_pop_payload_im2colStride_1),
    .io_deq_bits_im2colPad_0      (io_pop_payload_im2colPad_0),
    .io_deq_bits_im2colPad_1      (io_pop_payload_im2colPad_1),
    .io_deq_bits_im2colDilation_0 (io_pop_payload_im2colDilation_0),
    .io_deq_bits_im2colDilation_1 (io_pop_payload_im2colDilation_1),
    .io_deq_bits_im2colInShape_0  (io_pop_payload_im2colInShape_0),
    .io_deq_bits_im2colInShape_1  (io_pop_payload_im2colInShape_1),
    .io_deq_bits_im2colInShape_2  (io_pop_payload_im2colInShape_2),
    .io_deq_bits_sgListAddr       (io_pop_payload_sgListAddr),
    .io_deq_bits_sgEntryCount     (io_pop_payload_sgEntryCount),
    .io_count                     (io_occupancy)
  );	// src/utils/Stream/Stream.scala:371:21
endmodule

