// Generated by CIRCT firtool-1.149.0
module Hive_HiveMacFp(	// src/hive/scala/main/HiveWorkUnit.scala:205:7
  input  [31:0] io_a,	// src/hive/scala/main/HiveWorkUnit.scala:208:14
                io_b,	// src/hive/scala/main/HiveWorkUnit.scala:208:14
  input  [39:0] io_c,	// src/hive/scala/main/HiveWorkUnit.scala:208:14
  input  [2:0]  io_rnd,	// src/hive/scala/main/HiveWorkUnit.scala:208:14
  output [39:0] io_sum	// src/hive/scala/main/HiveWorkUnit.scala:208:14
);

  wire        prod32_sOut = io_a[31] ^ io_b[31];	// src/hive/scala/main/Fp32.scala:9:30, :100:19
  wire [47:0] prod32_mProd = {25'h1, io_a[22:0]} * {25'h1, io_b[22:0]};	// src/hive/scala/main/Fp32.scala:11:30, :104:22
  wire [8:0]  _prod32_eAdj_T_2 =
    {1'h0, io_a[30:23]} + {1'h0, io_b[30:23]} + {8'h0, prod32_mProd[47]};	// src/hive/scala/main/Fp32.scala:10:29, :104:22, :108:19, :109:{21,32}
  wire [22:0] prod32_mNorm = prod32_mProd[47] ? prod32_mProd[46:24] : prod32_mProd[45:23];	// src/hive/scala/main/Fp32.scala:104:22, :109:32, :113:{20,37,52}
  wire        prod32_guardBit = prod32_mProd[47] ? prod32_mProd[23] : prod32_mProd[22];	// src/hive/scala/main/Fp32.scala:104:22, :109:32, :115:{23,40,51}
  wire [31:0] prod32 =
    io_a[30:23] == 8'h0 & io_a[22:0] == 23'h0 | io_b[30:23] == 8'h0 & io_b[22:0] == 23'h0
      ? 32'h0
      : {prod32_sOut,
         _prod32_eAdj_T_2 > 9'h7E ? _prod32_eAdj_T_2[7:0] - 8'h7F : 8'h0,
         io_rnd != 3'h1
         & (io_rnd == 3'h2
              ? prod32_sOut & prod32_guardBit
              : (io_rnd != 3'h3 | ~prod32_sOut) & prod32_guardBit)
           ? prod32_mNorm + 23'h1
           : prod32_mNorm};	// src/hive/scala/main/Fp32.scala:10:29, :11:30, :14:50, :100:19, :108:19, :109:21, :110:{19,25,41}, :113:20, :115:23, :119:{21,30,37}, :120:{21,30,37}, :121:{8,15}, :246:{22,27}, :247:{10,15,42}, :248:{12,17,39}, :250:{8,25}
  wire [30:0] pMant31 = {1'h1, prod32[22:0], 7'h0};	// src/hive/scala/main/Fp32.scala:11:30, :121:8, src/hive/scala/main/HiveWorkUnit.scala:231:20
  wire [8:0]  _expDiffRaw_T_2 = {1'h0, prod32[30:23]} - {1'h0, io_c[38:31]};	// src/hive/scala/main/Fp32.scala:10:29, :121:8, src/hive/scala/main/HiveWorkUnit.scala:222:19, :235:30
  wire        pGtC = $signed(_expDiffRaw_T_2) > -9'sh1;	// src/hive/scala/main/HiveWorkUnit.scala:235:30, :236:25
  wire [8:0]  _shiftAmt_T_8 = 9'h0 - _expDiffRaw_T_2;	// src/hive/scala/main/HiveWorkUnit.scala:235:30, :236:25, :239:10
  wire [7:0]  baseExp = pGtC ? prod32[30:23] : io_c[38:31];	// src/hive/scala/main/Fp32.scala:10:29, :121:8, src/hive/scala/main/HiveWorkUnit.scala:222:19, :236:25, :240:20
  wire [30:0] _GEN =
    {26'h0,
     pGtC
       ? ($signed(_expDiffRaw_T_2) > 9'sh1F ? 5'h1F : _expDiffRaw_T_2[4:0])
       : $signed(_shiftAmt_T_8) > 9'sh1F ? 5'h1F : _shiftAmt_T_8[4:0]};	// src/hive/scala/main/HiveWorkUnit.scala:235:30, :236:25, :237:21, :238:{8,20,56}, :239:{8,10,23,43,62}, :243:46
  wire [30:0] pAligned = pGtC ? pMant31 : pMant31 >> _GEN;	// src/hive/scala/main/HiveWorkUnit.scala:231:20, :236:25, :243:{21,46}
  wire [30:0] cAligned = pGtC ? io_c[30:0] >> _GEN : io_c[30:0];	// src/hive/scala/main/HiveWorkUnit.scala:223:19, :236:25, :243:46, :244:{21,35}
  wire        effectSub = prod32[31] ^ io_c[39];	// src/hive/scala/main/Fp32.scala:9:30, :121:8, src/hive/scala/main/HiveWorkUnit.scala:221:19, :247:25
  wire        pIsLarger = $signed(_expDiffRaw_T_2) > 9'sh0 | pAligned >= cAligned;	// src/hive/scala/main/HiveWorkUnit.scala:235:30, :243:21, :244:21, :252:{31,38,51}
  wire [30:0] largeM = pIsLarger ? pAligned : cAligned;	// src/hive/scala/main/HiveWorkUnit.scala:243:21, :244:21, :252:38, :253:19
  wire [30:0] smallM = pIsLarger ? cAligned : pAligned;	// src/hive/scala/main/HiveWorkUnit.scala:243:21, :244:21, :252:38, :254:19
  wire [31:0] addRes = {1'h0, largeM} + {1'h0, smallM};	// src/hive/scala/main/HiveWorkUnit.scala:253:19, :254:19, :257:23
  wire [30:0] _subRes_T = largeM - smallM;	// src/hive/scala/main/HiveWorkUnit.scala:253:19, :254:19, :258:23
  assign io_sum =
    prod32[30:23] == 8'h0 & prod32[22:0] == 23'h0
      ? io_c
      : io_c[38:31] == 8'h0 & io_c[30:0] == 31'h0
          ? {prod32[31:23], 1'h1, prod32[22:0], 7'h0}
          : effectSub & _subRes_T == 31'h0
              ? 40'h0
              : {pIsLarger ? prod32[31] : io_c[39],
                 effectSub | ~(addRes[31]) ? baseExp : baseExp + 8'h1,
                 effectSub ? _subRes_T : addRes[31] ? addRes[31:1] : addRes[30:0]};	// src/hive/scala/main/Fp32.scala:9:30, :10:29, :11:30, :109:26, :121:8, :250:25, src/hive/scala/main/HiveWorkUnit.scala:205:7, :221:19, :222:19, :223:19, :224:{21,30,40}, :231:20, :232:{21,30,40}, :240:20, :247:25, :252:38, :255:19, :257:23, :258:23, :264:19, :266:13, :267:13, :269:{16,22}, :271:{15,24}, :272:26, :275:{15,24}, :281:19, :282:21, :283:{8,19}, :284:{10,21,32}
endmodule

