// Generated by CIRCT firtool-1.149.0
module Hive_HiveCvtOpMx(	// src/hive/scala/main/HiveWorkUnit.scala:87:7
  input         clock,	// src/hive/scala/main/HiveWorkUnit.scala:87:7
                reset,	// src/hive/scala/main/HiveWorkUnit.scala:87:7
  input  [7:0]  io_in,	// src/hive/scala/main/HiveWorkUnit.scala:88:14
  input  [2:0]  io_fmt,	// src/hive/scala/main/HiveWorkUnit.scala:88:14
  input  [7:0]  io_scale,	// src/hive/scala/main/HiveWorkUnit.scala:88:14
  output [31:0] io_out	// src/hive/scala/main/HiveWorkUnit.scala:88:14
);

  wire       isE5_layerCapture = io_fmt == 3'h5;	// src/hive/scala/main/HiveWorkUnit.scala:94:21
  wire [4:0] e5_layerCapture = io_in[6:2];	// src/hive/scala/main/Fp32.scala:60:14
  wire       _io_out_isSub_T = e5_layerCapture == 5'h0;	// src/hive/scala/main/Fp32.scala:60:14, :63:23
  wire [8:0] _GEN = {1'h0, io_scale};	// src/hive/scala/main/Fp32.scala:71:23
  wire [9:0] _io_out_expSigned_T_1 = {1'h0, {4'h0, e5_layerCapture} + _GEN} - 10'hF;	// src/hive/scala/main/Fp32.scala:60:14, :71:23, :72:33
  wire [3:0] e4_layerCapture = io_in[6:3];	// src/hive/scala/main/Fp32.scala:60:14
  wire [2:0] m4_layerCapture = io_in[2:0];	// src/hive/scala/main/Fp32.scala:61:14
  wire       _io_out_isSub_T_2 = e4_layerCapture == 4'h0;	// src/hive/scala/main/Fp32.scala:60:14, :63:23, :71:23
  wire [9:0] _io_out_expSigned_T_4 = {1'h0, {5'h0, e4_layerCapture} + _GEN} - 10'h7;	// src/hive/scala/main/Fp32.scala:60:14, :63:23, :71:23, :72:33
  assign io_out =
    {io_in[7],
     isE5_layerCapture
       ? (_io_out_isSub_T & io_in[1:0] == 2'h0 | _io_out_isSub_T & (|(io_in[1:0]))
            ? 31'h0
            : (&e5_layerCapture) | $signed(_io_out_expSigned_T_1) > 10'shFE
                ? 31'h7F7FFFFF
                : $signed(_io_out_expSigned_T_1) < 10'sh1
                    ? 31'h0
                    : {_io_out_expSigned_T_1[7:0], io_in[1:0], 21'h0})
       : _io_out_isSub_T_2 & m4_layerCapture == 3'h0 | _io_out_isSub_T_2
         & (|m4_layerCapture)
           ? 31'h0
           : (&e4_layerCapture) & (&m4_layerCapture)
             | $signed(_io_out_expSigned_T_4) > 10'shFE
               ? 31'h7F7FFFFF
               : $signed(_io_out_expSigned_T_4) < 10'sh1
                   ? 31'h0
                   : {_io_out_expSigned_T_4[7:0], m4_layerCapture, 20'h0}};	// src/hive/scala/main/Fp32.scala:59:14, :60:14, :61:14, :63:{23,32,38}, :64:{32,38}, :65:{46,51,56,69}, :68:18, :72:33, :73:31, :74:31, :76:25, :78:{25,45}, :80:{8,16}, :81:{10,20}, :82:12, src/hive/scala/main/HiveWorkUnit.scala:87:7, :94:21, :95:16
endmodule

