// Generated by CIRCT firtool-1.149.0
`ifndef layers_Llc_Verification_Assume	// src/llc/scala/main/Llc.scala:15:7
  `define layers_Llc_Verification_Assume
  `include "layers-Llc-Verification.sv"	// src/llc/scala/main/Llc.scala:15:7
`endif // not def layers_Llc_Verification_Assume
