// Generated by CIRCT firtool-1.149.0
`ifndef layers_Hive_HiveCore_Verification_Cover	// src/hive/scala/main/HiveCore.scala:21:7
  `define layers_Hive_HiveCore_Verification_Cover
  `include "layers-Hive_HiveCore-Verification.sv"	// src/hive/scala/main/HiveCore.scala:21:7
`endif // not def layers_Hive_HiveCore_Verification_Cover
