// Generated by CIRCT firtool-1.149.0
`ifndef layers_Hive_HiveCell_Verification	// src/hive/scala/main/HiveCell.scala:33:7
  `define layers_Hive_HiveCell_Verification
  `include "layers-Hive_HiveWorker-Verification.sv"	// src/hive/scala/main/HiveCell.scala:33:7
`endif // not def layers_Hive_HiveCell_Verification
