// Generated by CIRCT firtool-1.149.0
`ifndef layers_Hive_HiveCoreExecutor_Verification	// src/hive/scala/main/HiveCoreExecutor.scala:30:7
  `define layers_Hive_HiveCoreExecutor_Verification
`endif // not def layers_Hive_HiveCoreExecutor_Verification
