// Generated by CIRCT firtool-1.149.0
module Hive_HiveMacFp(	// src/hive/scala/main/HiveWorkUnit.scala:173:7
  input  [31:0] io_a,	// src/hive/scala/main/HiveWorkUnit.scala:174:14
                io_b,	// src/hive/scala/main/HiveWorkUnit.scala:174:14
                io_c,	// src/hive/scala/main/HiveWorkUnit.scala:174:14
  input  [2:0]  io_rnd,	// src/hive/scala/main/HiveWorkUnit.scala:174:14
  output [31:0] io_sum	// src/hive/scala/main/HiveWorkUnit.scala:174:14
);

  wire [31:0] _mul_io_prod;	// src/hive/scala/main/HiveWorkUnit.scala:181:19
  Hive_HiveMulFp mul (	// src/hive/scala/main/HiveWorkUnit.scala:181:19
    .io_a    (io_a),
    .io_b    (io_b),
    .io_rnd  (io_rnd),
    .io_prod (_mul_io_prod)
  );	// src/hive/scala/main/HiveWorkUnit.scala:181:19
  Hive_HiveAddFp add (	// src/hive/scala/main/HiveWorkUnit.scala:192:19
    .io_cReg (io_c),
    .io_prod (_mul_io_prod),	// src/hive/scala/main/HiveWorkUnit.scala:181:19
    .io_rnd  (io_rnd),
    .io_sum  (io_sum)
  );	// src/hive/scala/main/HiveWorkUnit.scala:192:19
endmodule

