// Generated by CIRCT firtool-1.149.0
module Hive_HiveCvtOpFp(	// src/hive/scala/main/HiveWorkUnit.scala:66:7
  input  [15:0] io_in,	// src/hive/scala/main/HiveWorkUnit.scala:67:14
  input  [1:0]  io_fmt,	// src/hive/scala/main/HiveWorkUnit.scala:67:14
  output [31:0] io_out	// src/hive/scala/main/HiveWorkUnit.scala:67:14
);

  wire _io_out_isZero_T = io_in[14:10] == 5'h0;	// src/hive/scala/main/Fp32.scala:25:15, :28:21
  assign io_out =
    io_fmt == 2'h1
      ? {io_in, 16'h0}
      : {io_in[15],
         _io_out_isZero_T & io_in[9:0] == 10'h0
           ? 31'h0
           : {_io_out_isZero_T ? 8'h0 : {3'h0, io_in[14:10]} + 8'h70, io_in[9:0], 13'h0}};	// src/hive/scala/main/Fp32.scala:17:38, :24:14, :25:15, :26:16, :28:{17,21,44}, :29:18, :30:{31,39}, :31:{8,20,39}, src/hive/scala/main/HiveWorkUnit.scala:66:7, :76:{16,24}
endmodule

