// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Hive_HiveCoreDmaWrOnly(	// src/hive/scala/main/HiveCoreDma.scala:283:7
  input          clock,	// src/hive/scala/main/HiveCoreDma.scala:283:7
                 reset,	// src/hive/scala/main/HiveCoreDma.scala:283:7
                 io_start,	// src/hive/scala/main/HiveCoreDma.scala:286:14
                 io_peekBlock,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  output         io_doneBlock,	// src/hive/scala/main/HiveCoreDma.scala:286:14
                 io_busy,	// src/hive/scala/main/HiveCoreDma.scala:286:14
                 io_err,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  input          io_dmaExtWrIF_rsp_valid,	// src/hive/scala/main/HiveCoreDma.scala:286:14
                 io_dmaExtWrIF_rsp_payload_err,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  output         io_dmaExtWrIF_req_valid,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  input          io_dmaExtWrIF_req_ready,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  output [31:0]  io_dmaExtWrIF_req_payload_addr,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  output [511:0] io_dmaExtWrIF_req_payload_data,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  input  [15:0]  io_calcConfig_nTile,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  input  [31:0]  io_calcConfig_cRowAddressOffset,	// src/hive/scala/main/HiveCoreDma.scala:286:14
                 io_regFile_regs_0,	// src/hive/scala/main/HiveCoreDma.scala:286:14
                 io_regFile_regs_5,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  input          io_bufPop_valid,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  output         io_bufPop_ready,	// src/hive/scala/main/HiveCoreDma.scala:286:14
  input  [511:0] io_bufPop_payload	// src/hive/scala/main/HiveCoreDma.scala:286:14
);

  reg  [2:0]  state;	// src/hive/scala/main/HiveCoreDma.scala:313:22
  reg  [31:0] curAddr;	// src/hive/scala/main/HiveCoreDma.scala:318:24
  reg  [31:0] colAddr;	// src/hive/scala/main/HiveCoreDma.scala:319:24
  reg  [31:0] rowStep;	// src/hive/scala/main/HiveCoreDma.scala:320:24
  reg  [15:0] lineCounter;	// src/hive/scala/main/HiveCoreDma.scala:321:28
  reg  [15:0] nCnt;	// src/hive/scala/main/HiveCoreDma.scala:322:21
  reg         errReg;	// src/hive/scala/main/HiveCoreDma.scala:323:23
  reg  [11:0] ostCredit;	// src/hive/scala/main/HiveCoreDma.scala:324:26
  wire        _io_bufPop_ready_T = state == 3'h2;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22, :329:44
  wire        io_dmaExtWrIF_req_valid_0 = _io_bufPop_ready_T & io_bufPop_valid;	// src/hive/scala/main/HiveCoreDma.scala:329:{44,61}
  wire        io_bufPop_ready_0 = _io_bufPop_ready_T & io_dmaExtWrIF_req_ready;	// src/hive/scala/main/HiveCoreDma.scala:329:44, :333:61
  wire        _GEN = state == 3'h0;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22, :340:14
  wire        _GEN_0 = state == 3'h1;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22, :359:17
  wire        _GEN_1 = io_bufPop_valid & io_bufPop_ready_0;	// src/hive/scala/main/HiveCoreDma.scala:333:61, src/utils/Stream/Stream.scala:43:26
  wire        _GEN_2 = {16'h0, lineCounter} == io_regFile_regs_0 - 32'h1;	// src/hive/scala/main/HiveCoreDma.scala:321:28, :392:{26,43}
  wire        _GEN_3 = _GEN | _GEN_0;	// src/hive/scala/main/HiveCoreDma.scala:338:16, :340:14, :359:17
  always @(posedge clock) begin	// src/hive/scala/main/HiveCoreDma.scala:283:7
    if (reset) begin	// src/hive/scala/main/HiveCoreDma.scala:283:7
      state <= 3'h0;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22
      curAddr <= 32'h0;	// src/hive/scala/main/HiveCoreDma.scala:318:24
      colAddr <= 32'h0;	// src/hive/scala/main/HiveCoreDma.scala:318:24, :319:24
      rowStep <= 32'h0;	// src/hive/scala/main/HiveCoreDma.scala:318:24, :320:24
      lineCounter <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:321:28
      nCnt <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:322:21
      errReg <= 1'h0;	// src/hive/scala/main/HiveCoreDma.scala:323:23
      ostCredit <= 12'h0;	// src/hive/scala/main/HiveCoreDma.scala:324:26
    end
    else begin	// src/hive/scala/main/HiveCoreDma.scala:283:7
      automatic logic _GEN_4 = _GEN & io_start;	// src/hive/scala/main/HiveCoreDma.scala:340:14, :352:31, :359:17, :367:22, :369:16
      if (_GEN) begin	// src/hive/scala/main/HiveCoreDma.scala:340:14
        if (io_start) begin	// src/hive/scala/main/HiveCoreDma.scala:286:14
          state <= 3'h1;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22
          curAddr <= io_regFile_regs_5;	// src/hive/scala/main/HiveCoreDma.scala:318:24
          colAddr <= 32'h40;	// src/hive/scala/main/HiveCoreDma.scala:319:24
          nCnt <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:322:21
        end
        ostCredit <= 12'h0;	// src/hive/scala/main/HiveCoreDma.scala:324:26
      end
      else begin	// src/hive/scala/main/HiveCoreDma.scala:340:14
        automatic logic _GEN_5;	// src/utils/Stream/Stream.scala:43:26
        automatic logic _GEN_6;	// src/hive/scala/main/HiveCoreDma.scala:359:17
        automatic logic _GEN_7;	// src/hive/scala/main/HiveCoreDma.scala:405:17
        _GEN_5 = io_dmaExtWrIF_req_valid_0 & io_dmaExtWrIF_req_ready;	// src/hive/scala/main/HiveCoreDma.scala:329:61, src/utils/Stream/Stream.scala:43:26
        _GEN_6 = state == 3'h3;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22, :359:17
        _GEN_7 = nCnt == io_calcConfig_nTile - 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:322:21, :405:{17,41}
        if (_GEN_0) begin	// src/hive/scala/main/HiveCoreDma.scala:359:17
          if (io_peekBlock)	// src/hive/scala/main/HiveCoreDma.scala:286:14
            state <= 3'h2;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22
        end
        else if (_io_bufPop_ready_T) begin	// src/hive/scala/main/HiveCoreDma.scala:329:44
          if (_GEN_1 & _GEN_2)	// src/hive/scala/main/HiveCoreDma.scala:313:22, :391:28, :392:{26,50}, :394:17, src/utils/Stream/Stream.scala:43:26
            state <= 3'h3;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22
          if (~_GEN_1 | _GEN_2) begin	// src/hive/scala/main/HiveCoreDma.scala:318:24, :321:28, :359:17, :391:28, :392:{26,50}, src/utils/Stream/Stream.scala:43:26
          end
          else	// src/hive/scala/main/HiveCoreDma.scala:318:24, :391:28, :392:50
            curAddr <= curAddr + rowStep;	// src/hive/scala/main/HiveCoreDma.scala:318:24, :320:24, :398:30
        end
        else begin	// src/hive/scala/main/HiveCoreDma.scala:329:44
          if (_GEN_6) begin	// src/hive/scala/main/HiveCoreDma.scala:359:17
            if (_GEN_7)	// src/hive/scala/main/HiveCoreDma.scala:405:17
              state <= 3'h4;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22
            else if (io_peekBlock)	// src/hive/scala/main/HiveCoreDma.scala:286:14
              state <= 3'h2;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22
          end
          else if (state == 3'h4 & ostCredit == 12'h0)	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22, :324:26, :359:17, :421:{22,31}, :423:15
            state <= 3'h0;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22
          if (~_GEN_6 | _GEN_7 | ~io_peekBlock) begin	// src/hive/scala/main/HiveCoreDma.scala:318:24, :322:21, :359:17, :405:{17,47}, :408:27
          end
          else	// src/hive/scala/main/HiveCoreDma.scala:318:24, :359:17, :405:47, :408:27
            curAddr <= curAddr + colAddr;	// src/hive/scala/main/HiveCoreDma.scala:318:24, :319:24, :410:30
        end
        if (_GEN_0 | _io_bufPop_ready_T | ~_GEN_6 | _GEN_7 | ~io_peekBlock) begin	// src/hive/scala/main/HiveCoreDma.scala:322:21, :329:44, :359:17, :405:{17,47}, :408:27
        end
        else begin	// src/hive/scala/main/HiveCoreDma.scala:322:21, :359:17, :405:47, :408:27
          colAddr <= colAddr + 32'h40;	// src/hive/scala/main/HiveCoreDma.scala:319:24, :411:30
          nCnt <= nCnt + 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:322:21, :409:24
        end
        if (~(_GEN_5 & io_dmaExtWrIF_rsp_valid)) begin	// src/hive/scala/main/HiveCoreDma.scala:343:33, src/utils/Stream/Stream.scala:43:26
          if (io_dmaExtWrIF_rsp_valid)	// src/hive/scala/main/HiveCoreDma.scala:286:14
            ostCredit <= ostCredit - 12'h1;	// src/hive/scala/main/HiveCoreDma.scala:324:26, :346:30
          else if (_GEN_5)	// src/utils/Stream/Stream.scala:43:26
            ostCredit <= ostCredit + 12'h1;	// src/hive/scala/main/HiveCoreDma.scala:324:26, :346:30, :348:30
        end
      end
      if (_GEN_4)	// src/hive/scala/main/HiveCoreDma.scala:352:31, :359:17, :367:22, :369:16
        rowStep <= io_calcConfig_cRowAddressOffset;	// src/hive/scala/main/HiveCoreDma.scala:320:24
      if (_GEN_3 | ~_GEN_1) begin	// src/hive/scala/main/HiveCoreDma.scala:321:28, :338:16, :359:17, src/utils/Stream/Stream.scala:43:26
      end
      else	// src/hive/scala/main/HiveCoreDma.scala:321:28, :359:17
        lineCounter <= _GEN_2 ? 16'h0 : lineCounter + 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:321:28, :392:{26,50}, :393:23, :397:{23,38}
      errReg <=
        ~_GEN_4 & (io_dmaExtWrIF_rsp_valid & io_dmaExtWrIF_rsp_payload_err | errReg);	// src/hive/scala/main/HiveCoreDma.scala:323:23, :352:31, :353:40, :354:14, :359:17, :367:22, :369:16
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/hive/scala/main/HiveCoreDma.scala:283:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/hive/scala/main/HiveCoreDma.scala:283:7
      `FIRRTL_BEFORE_INITIAL	// src/hive/scala/main/HiveCoreDma.scala:283:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/hive/scala/main/HiveCoreDma.scala:283:7
      automatic logic [31:0] _RANDOM[0:4];	// src/hive/scala/main/HiveCoreDma.scala:283:7
      `ifdef INIT_RANDOM_PROLOG_	// src/hive/scala/main/HiveCoreDma.scala:283:7
        `INIT_RANDOM_PROLOG_	// src/hive/scala/main/HiveCoreDma.scala:283:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/hive/scala/main/HiveCoreDma.scala:283:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/hive/scala/main/HiveCoreDma.scala:283:7
        end	// src/hive/scala/main/HiveCoreDma.scala:283:7
        state = _RANDOM[3'h0][2:0];	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22
        curAddr = {_RANDOM[3'h0][31:3], _RANDOM[3'h1][2:0]};	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22, :318:24
        colAddr = {_RANDOM[3'h1][31:3], _RANDOM[3'h2][2:0]};	// src/hive/scala/main/HiveCoreDma.scala:283:7, :318:24, :319:24
        rowStep = {_RANDOM[3'h2][31:3], _RANDOM[3'h3][2:0]};	// src/hive/scala/main/HiveCoreDma.scala:283:7, :319:24, :320:24
        lineCounter = _RANDOM[3'h3][18:3];	// src/hive/scala/main/HiveCoreDma.scala:283:7, :320:24, :321:28
        nCnt = {_RANDOM[3'h3][31:19], _RANDOM[3'h4][2:0]};	// src/hive/scala/main/HiveCoreDma.scala:283:7, :320:24, :322:21
        errReg = _RANDOM[3'h4][3];	// src/hive/scala/main/HiveCoreDma.scala:283:7, :322:21, :323:23
        ostCredit = _RANDOM[3'h4][15:4];	// src/hive/scala/main/HiveCoreDma.scala:283:7, :322:21, :324:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/hive/scala/main/HiveCoreDma.scala:283:7
      `FIRRTL_AFTER_INITIAL	// src/hive/scala/main/HiveCoreDma.scala:283:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_doneBlock = ~_GEN_3 & _GEN_1 & _GEN_2;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :338:16, :359:17, :391:28, :392:{26,50}, src/utils/Stream/Stream.scala:43:26
  assign io_busy = |state;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :313:22, :336:20
  assign io_err = errReg;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :323:23
  assign io_dmaExtWrIF_req_valid = io_dmaExtWrIF_req_valid_0;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :329:61
  assign io_dmaExtWrIF_req_payload_addr = curAddr;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :318:24
  assign io_dmaExtWrIF_req_payload_data = io_bufPop_payload;	// src/hive/scala/main/HiveCoreDma.scala:283:7
  assign io_bufPop_ready = io_bufPop_ready_0;	// src/hive/scala/main/HiveCoreDma.scala:283:7, :333:61
endmodule

