// Generated by CIRCT firtool-1.149.0
module Hive_HiveAddInt(	// src/hive/scala/main/HiveWorkUnit.scala:112:7
  input  [31:0] io_cReg,	// src/hive/scala/main/HiveWorkUnit.scala:113:14
                io_prod,	// src/hive/scala/main/HiveWorkUnit.scala:113:14
  output [31:0] io_sum	// src/hive/scala/main/HiveWorkUnit.scala:113:14
);

  assign io_sum = io_cReg + io_prod;	// src/hive/scala/main/HiveWorkUnit.scala:112:7, :118:29
endmodule

