// Generated by CIRCT firtool-1.149.0
module Hive_HiveWorkUnit(	// src/hive/scala/main/HiveWorkUnit.scala:267:7
  input  [15:0] io_a,	// src/hive/scala/main/HiveWorkUnit.scala:283:14
                io_b,	// src/hive/scala/main/HiveWorkUnit.scala:283:14
  input  [39:0] io_cReg,	// src/hive/scala/main/HiveWorkUnit.scala:283:14
  input  [1:0]  io_fmt,	// src/hive/scala/main/HiveWorkUnit.scala:283:14
  input  [2:0]  io_rnd,	// src/hive/scala/main/HiveWorkUnit.scala:283:14
  output [39:0] io_sum	// src/hive/scala/main/HiveWorkUnit.scala:283:14
);

  wire [39:0] _sumFp_macFp_io_sum;	// src/hive/scala/main/HiveWorkUnit.scala:319:23
  wire [31:0] _sumFp_bCvt_io_out;	// src/hive/scala/main/HiveWorkUnit.scala:316:22
  wire [31:0] _sumFp_aCvt_io_out;	// src/hive/scala/main/HiveWorkUnit.scala:313:22
  wire [39:0] _sumInt_macInt_io_sum;	// src/hive/scala/main/HiveWorkUnit.scala:301:24
  wire [15:0] _sumInt_bCvt_io_out;	// src/hive/scala/main/HiveWorkUnit.scala:298:22
  wire [15:0] _sumInt_aCvt_io_out;	// src/hive/scala/main/HiveWorkUnit.scala:295:22
  Hive_HiveCvtOpInt sumInt_aCvt (	// src/hive/scala/main/HiveWorkUnit.scala:295:22
    .io_in  (io_a),
    .io_fmt (io_fmt),
    .io_out (_sumInt_aCvt_io_out)
  );	// src/hive/scala/main/HiveWorkUnit.scala:295:22
  Hive_HiveCvtOpInt sumInt_bCvt (	// src/hive/scala/main/HiveWorkUnit.scala:298:22
    .io_in  (io_b),
    .io_fmt (io_fmt),
    .io_out (_sumInt_bCvt_io_out)
  );	// src/hive/scala/main/HiveWorkUnit.scala:298:22
  Hive_HiveMacInt sumInt_macInt (	// src/hive/scala/main/HiveWorkUnit.scala:301:24
    .io_a   (_sumInt_aCvt_io_out),	// src/hive/scala/main/HiveWorkUnit.scala:295:22
    .io_b   (_sumInt_bCvt_io_out),	// src/hive/scala/main/HiveWorkUnit.scala:298:22
    .io_c   (io_cReg),
    .io_sum (_sumInt_macInt_io_sum)
  );	// src/hive/scala/main/HiveWorkUnit.scala:301:24
  Hive_HiveCvtOpFp sumFp_aCvt (	// src/hive/scala/main/HiveWorkUnit.scala:313:22
    .io_in  (io_a),
    .io_fmt (io_fmt),
    .io_out (_sumFp_aCvt_io_out)
  );	// src/hive/scala/main/HiveWorkUnit.scala:313:22
  Hive_HiveCvtOpFp sumFp_bCvt (	// src/hive/scala/main/HiveWorkUnit.scala:316:22
    .io_in  (io_b),
    .io_fmt (io_fmt),
    .io_out (_sumFp_bCvt_io_out)
  );	// src/hive/scala/main/HiveWorkUnit.scala:316:22
  Hive_HiveMacFp sumFp_macFp (	// src/hive/scala/main/HiveWorkUnit.scala:319:23
    .io_a   (_sumFp_aCvt_io_out),	// src/hive/scala/main/HiveWorkUnit.scala:313:22
    .io_b   (_sumFp_bCvt_io_out),	// src/hive/scala/main/HiveWorkUnit.scala:316:22
    .io_c   (io_cReg),
    .io_rnd (io_rnd),
    .io_sum (_sumFp_macFp_io_sum)
  );	// src/hive/scala/main/HiveWorkUnit.scala:319:23
  assign io_sum =
    (&io_fmt) | io_fmt == 2'h2 ? _sumInt_macInt_io_sum : _sumFp_macFp_io_sum;	// src/hive/scala/main/HiveWorkUnit.scala:267:7, :301:24, :319:23, :332:{26,46,56}, :333:10
endmodule

