// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Hive_HiveWorker_95(	// src/hive/scala/main/HiveWorker.scala:60:7
  input         clock,	// src/hive/scala/main/HiveWorker.scala:60:7
                reset,	// src/hive/scala/main/HiveWorker.scala:60:7
  input  [15:0] io_aIn,	// src/hive/scala/main/HiveWorker.scala:75:14
  input  [39:0] io_psumIn,	// src/hive/scala/main/HiveWorker.scala:75:14
  output [39:0] io_psumOut,	// src/hive/scala/main/HiveWorker.scala:75:14
  input         io_loadHIn,	// src/hive/scala/main/HiveWorker.scala:75:14
                io_loadVInLock,	// src/hive/scala/main/HiveWorker.scala:75:14
                io_loadVIn,	// src/hive/scala/main/HiveWorker.scala:75:14
  output        io_loadVOut,	// src/hive/scala/main/HiveWorker.scala:75:14
  input         io_loadWInLock,	// src/hive/scala/main/HiveWorker.scala:75:14
                io_validIn,	// src/hive/scala/main/HiveWorker.scala:75:14
                io_validInV,	// src/hive/scala/main/HiveWorker.scala:75:14
  output        io_validOutV,	// src/hive/scala/main/HiveWorker.scala:75:14
  input  [2:0]  io_fmtIn,	// src/hive/scala/main/HiveWorker.scala:75:14
                io_bFmtIn,	// src/hive/scala/main/HiveWorker.scala:75:14
  input  [7:0]  io_scaleAIn,	// src/hive/scala/main/HiveWorker.scala:75:14
                io_scaleBIn,	// src/hive/scala/main/HiveWorker.scala:75:14
  input  [2:0]  io_rndIn,	// src/hive/scala/main/HiveWorker.scala:75:14
  input         io_clear	// src/hive/scala/main/HiveWorker.scala:75:14
);

  wire [39:0] _workUnit_io_sum;	// src/hive/scala/main/HiveWorker.scala:194:24
  reg  [2:0]  fmtReg;	// src/hive/scala/main/HiveWorker.scala:137:19
  reg  [2:0]  rndReg;	// src/hive/scala/main/HiveWorker.scala:138:19
  reg  [2:0]  bFmtReg;	// src/hive/scala/main/HiveWorker.scala:140:20
  reg  [7:0]  scaleBReg;	// src/hive/scala/main/HiveWorker.scala:142:26
  reg  [15:0] wReg;	// src/hive/scala/main/HiveWorker.scala:151:21
  reg  [39:0] psumReg;	// src/hive/scala/main/HiveWorker.scala:208:24
  reg         io_validOutV_REG;	// src/hive/scala/main/HiveWorker.scala:246:26
  reg         io_loadVOut_REG;	// src/hive/scala/main/HiveWorker.scala:247:26
  always @(posedge clock) begin	// src/hive/scala/main/HiveWorker.scala:60:7
    if (io_loadHIn) begin	// src/hive/scala/main/HiveWorker.scala:75:14
      fmtReg <= io_fmtIn;	// src/hive/scala/main/HiveWorker.scala:137:19
      rndReg <= io_rndIn;	// src/hive/scala/main/HiveWorker.scala:138:19
      bFmtReg <= io_bFmtIn;	// src/hive/scala/main/HiveWorker.scala:140:20
    end
    if (reset) begin	// src/hive/scala/main/HiveWorker.scala:60:7
      scaleBReg <= 8'h0;	// src/hive/scala/main/HiveWorker.scala:142:26
      wReg <= 16'h0;	// src/hive/scala/main/HiveWorker.scala:151:21
      psumReg <= 40'h0;	// src/hive/scala/main/HiveWorker.scala:208:24
      io_validOutV_REG <= 1'h0;	// src/hive/scala/main/HiveWorker.scala:125:30, :246:26
      io_loadVOut_REG <= 1'h0;	// src/hive/scala/main/HiveWorker.scala:125:30, :247:26
    end
    else begin	// src/hive/scala/main/HiveWorker.scala:60:7
      if (io_loadVInLock | io_loadWInLock)	// src/hive/scala/main/HiveWorker.scala:179:23
        scaleBReg <= io_scaleBIn;	// src/hive/scala/main/HiveWorker.scala:142:26
      if (io_loadWInLock)	// src/hive/scala/main/HiveWorker.scala:75:14
        wReg <= io_aIn;	// src/hive/scala/main/HiveWorker.scala:151:21
      else if (io_loadVInLock)	// src/hive/scala/main/HiveWorker.scala:75:14
        wReg <= io_psumIn[15:0];	// src/hive/scala/main/HiveWorker.scala:151:21, :157:22
      if (io_clear)	// src/hive/scala/main/HiveWorker.scala:75:14
        psumReg <= 40'h0;	// src/hive/scala/main/HiveWorker.scala:208:24
      else if (io_loadVIn)	// src/hive/scala/main/HiveWorker.scala:75:14
        psumReg <= io_psumIn;	// src/hive/scala/main/HiveWorker.scala:208:24
      else if (io_validIn
               & (fmtReg == 3'h5 | fmtReg == 3'h2 | fmtReg == 3'h4 | fmtReg == 3'h0
                  | fmtReg == 3'h1 | fmtReg == 3'h3))	// src/hive/scala/main/HiveWorker.scala:60:7, :137:19, :148:{45,61}, :213:25
        psumReg <= _workUnit_io_sum;	// src/hive/scala/main/HiveWorker.scala:194:24, :208:24
      io_validOutV_REG <= io_validInV;	// src/hive/scala/main/HiveWorker.scala:246:26
      io_loadVOut_REG <= io_loadVIn;	// src/hive/scala/main/HiveWorker.scala:247:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/hive/scala/main/HiveWorker.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/hive/scala/main/HiveWorker.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/hive/scala/main/HiveWorker.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/hive/scala/main/HiveWorker.scala:60:7
      automatic logic [31:0] _RANDOM[0:3];	// src/hive/scala/main/HiveWorker.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/hive/scala/main/HiveWorker.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/hive/scala/main/HiveWorker.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/hive/scala/main/HiveWorker.scala:60:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// src/hive/scala/main/HiveWorker.scala:60:7
        end	// src/hive/scala/main/HiveWorker.scala:60:7
        fmtReg = _RANDOM[2'h0][4:2];	// src/hive/scala/main/HiveWorker.scala:60:7, :137:19
        rndReg = _RANDOM[2'h0][7:5];	// src/hive/scala/main/HiveWorker.scala:60:7, :137:19, :138:19
        bFmtReg = _RANDOM[2'h0][10:8];	// src/hive/scala/main/HiveWorker.scala:60:7, :137:19, :140:20
        scaleBReg = _RANDOM[2'h0][18:11];	// src/hive/scala/main/HiveWorker.scala:60:7, :137:19, :142:26
        wReg = {_RANDOM[2'h0][31:27], _RANDOM[2'h1][10:0]};	// src/hive/scala/main/HiveWorker.scala:60:7, :137:19, :151:21
        psumReg = {_RANDOM[2'h1][31:11], _RANDOM[2'h2][18:0]};	// src/hive/scala/main/HiveWorker.scala:60:7, :151:21, :208:24
        io_validOutV_REG = _RANDOM[2'h3][4];	// src/hive/scala/main/HiveWorker.scala:60:7, :246:26
        io_loadVOut_REG = _RANDOM[2'h3][5];	// src/hive/scala/main/HiveWorker.scala:60:7, :246:26, :247:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/hive/scala/main/HiveWorker.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/hive/scala/main/HiveWorker.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Hive_HiveWorkUnit workUnit (	// src/hive/scala/main/HiveWorker.scala:194:24
    .clock     (clock),
    .reset     (reset),
    .io_a      (io_aIn),
    .io_b      (wReg),	// src/hive/scala/main/HiveWorker.scala:151:21
    .io_cReg   (io_psumIn),
    .io_aFmt   (fmtReg),	// src/hive/scala/main/HiveWorker.scala:137:19
    .io_bFmt   (bFmtReg),	// src/hive/scala/main/HiveWorker.scala:140:20
    .io_scaleA (io_scaleAIn),
    .io_scaleB (scaleBReg),	// src/hive/scala/main/HiveWorker.scala:142:26
    .io_rnd    (rndReg),	// src/hive/scala/main/HiveWorker.scala:138:19
    .io_sum    (_workUnit_io_sum)
  );	// src/hive/scala/main/HiveWorker.scala:194:24
  assign io_psumOut = psumReg;	// src/hive/scala/main/HiveWorker.scala:60:7, :208:24
  assign io_loadVOut = io_loadVOut_REG;	// src/hive/scala/main/HiveWorker.scala:60:7, :247:26
  assign io_validOutV = io_validOutV_REG;	// src/hive/scala/main/HiveWorker.scala:60:7, :246:26
endmodule

