// Generated by CIRCT firtool-1.149.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Hive_HiveCoreDmaRdOnly(	// src/hive/scala/main/HiveCoreDma.scala:50:7
  input          clock,	// src/hive/scala/main/HiveCoreDma.scala:50:7
                 reset,	// src/hive/scala/main/HiveCoreDma.scala:50:7
                 io_isA,	// src/hive/scala/main/HiveCoreDma.scala:54:14
                 io_start,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  output         io_err,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  input          io_dmaExtRdIF_rsp_valid,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  input  [255:0] io_dmaExtRdIF_rsp_payload_data,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  input          io_dmaExtRdIF_rsp_payload_err,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  output         io_dmaExtRdIF_req_valid,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  input          io_dmaExtRdIF_req_ready,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  output [31:0]  io_dmaExtRdIF_req_payload_addr,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  input  [15:0]  io_calcConfig_nTile,	// src/hive/scala/main/HiveCoreDma.scala:54:14
                 io_calcConfig_kTile,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  input  [31:0]  io_calcConfig_aRowAddressOffset,	// src/hive/scala/main/HiveCoreDma.scala:54:14
                 io_calcConfig_bRowAddressOffset,	// src/hive/scala/main/HiveCoreDma.scala:54:14
                 io_calcConfig_bColTileAddressOffset,	// src/hive/scala/main/HiveCoreDma.scala:54:14
                 io_regFile_regs_0,	// src/hive/scala/main/HiveCoreDma.scala:54:14
                 io_regFile_regs_3,	// src/hive/scala/main/HiveCoreDma.scala:54:14
                 io_regFile_regs_4,	// src/hive/scala/main/HiveCoreDma.scala:54:14
                 io_regFile_regs_7,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  output         io_bufPush_valid,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  output [255:0] io_bufPush_payload,	// src/hive/scala/main/HiveCoreDma.scala:54:14
  input          io_bufPopFire	// src/hive/scala/main/HiveCoreDma.scala:54:14
);

  reg  [1:0]  state;	// src/hive/scala/main/HiveCoreDma.scala:76:22
  reg  [31:0] curAddr;	// src/hive/scala/main/HiveCoreDma.scala:81:24
  reg  [31:0] colAddr;	// src/hive/scala/main/HiveCoreDma.scala:82:24
  reg  [31:0] rowStep;	// src/hive/scala/main/HiveCoreDma.scala:83:24
  reg  [31:0] bNextKTileAddressOffset;	// src/hive/scala/main/HiveCoreDma.scala:84:40
  reg  [15:0] kCnt;	// src/hive/scala/main/HiveCoreDma.scala:85:21
  reg  [15:0] nCnt;	// src/hive/scala/main/HiveCoreDma.scala:86:21
  reg  [15:0] lineTarget;	// src/hive/scala/main/HiveCoreDma.scala:88:28
  reg  [15:0] lineCounter;	// src/hive/scala/main/HiveCoreDma.scala:89:28
  reg  [5:0]  ostCredit;	// src/hive/scala/main/HiveCoreDma.scala:90:25
  reg         errReg;	// src/hive/scala/main/HiveCoreDma.scala:91:23
  wire        _io_dmaExtRdIF_req_valid_T_1 = state == 2'h1;	// src/hive/scala/main/HiveCoreDma.scala:76:22, :103:18, :119:62
  wire        io_dmaExtRdIF_req_valid_0 = (|ostCredit) & _io_dmaExtRdIF_req_valid_T_1;	// src/hive/scala/main/HiveCoreDma.scala:90:25, :119:{46,54,62}
  always @(posedge clock) begin	// src/hive/scala/main/HiveCoreDma.scala:50:7
    if (reset) begin	// src/hive/scala/main/HiveCoreDma.scala:50:7
      state <= 2'h0;	// src/hive/scala/main/HiveCoreDma.scala:76:22
      curAddr <= 32'h0;	// src/hive/scala/main/HiveCoreDma.scala:81:24
      colAddr <= 32'h0;	// src/hive/scala/main/HiveCoreDma.scala:81:24, :82:24
      rowStep <= 32'h0;	// src/hive/scala/main/HiveCoreDma.scala:81:24, :83:24
      bNextKTileAddressOffset <= 32'h0;	// src/hive/scala/main/HiveCoreDma.scala:81:24, :84:40
      kCnt <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:85:21
      nCnt <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:86:21
      lineTarget <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:88:28
      lineCounter <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:89:28
      ostCredit <= 6'h0;	// src/hive/scala/main/HiveCoreDma.scala:90:25
      errReg <= 1'h0;	// src/hive/scala/main/HiveCoreDma.scala:91:23
    end
    else begin	// src/hive/scala/main/HiveCoreDma.scala:50:7
      automatic logic             _GEN;	// src/hive/scala/main/HiveCoreDma.scala:96:14
      automatic logic             _GEN_0;	// src/utils/Stream/Stream.scala:43:26
      automatic logic [31:0]      _colAddr_T;	// src/hive/scala/main/HiveCoreDma.scala:156:60
      automatic logic             _GEN_1;	// src/hive/scala/main/HiveCoreDma.scala:176:28
      automatic logic             _GEN_2;	// src/hive/scala/main/HiveCoreDma.scala:192:19
      automatic logic             _GEN_3;	// src/hive/scala/main/HiveCoreDma.scala:196:21
      automatic logic             _GEN_4;	// src/hive/scala/main/HiveCoreDma.scala:86:21, :192:49, :196:51
      automatic logic             _GEN_5;	// src/hive/scala/main/HiveCoreDma.scala:132:17
      automatic logic [3:0][1:0]  _GEN_6;	// src/hive/scala/main/HiveCoreDma.scala:96:14, :119:62, :132:17, :168:21, :175:35, :191:20
      automatic logic [3:0][31:0] _GEN_7;	// src/hive/scala/main/HiveCoreDma.scala:81:24, :96:14, :119:62, :132:17, :138:20, :175:35, :191:20
      _GEN = state == 2'h0;	// src/hive/scala/main/HiveCoreDma.scala:76:22, :96:14
      _GEN_0 = io_dmaExtRdIF_req_valid_0 & io_dmaExtRdIF_req_ready;	// src/hive/scala/main/HiveCoreDma.scala:119:54, src/utils/Stream/Stream.scala:43:26
      _colAddr_T = io_calcConfig_bRowAddressOffset * 32'hF;	// src/hive/scala/main/HiveCoreDma.scala:156:60
      _GEN_1 = lineCounter == lineTarget - 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:88:28, :89:28, :176:{28,43}
      _GEN_2 = kCnt == io_calcConfig_kTile - 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:85:21, :192:{19,43}
      _GEN_3 = nCnt == io_calcConfig_nTile - 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:86:21, :196:{21,45}
      _GEN_4 = ~_GEN_2 | _GEN_3;	// src/hive/scala/main/HiveCoreDma.scala:86:21, :192:{19,49}, :196:{21,51}
      _GEN_5 = state != 2'h2;	// src/hive/scala/main/HiveCoreDma.scala:76:22, :132:17, :164:112
      _GEN_6 =
        {{(&state) & ostCredit == 6'h20 ? 2'h0 : state},
         {{_GEN_2 & _GEN_3, 1'h1}},
         {_GEN_0 & _GEN_1 ? 2'h2 : state},
         {io_start ? 2'h1 : state}};	// src/hive/scala/main/HiveCoreDma.scala:76:22, :90:25, :96:14, :97:15, :103:18, :119:62, :132:17, :164:112, :168:21, :169:16, :175:35, :176:{28,49}, :177:19, :191:20, :192:{19,49}, :196:{21,51}, :197:19, :200:19, :207:17, :236:{22,37}, :238:15, src/utils/Stream/Stream.scala:43:26
      state <= _GEN_6[state];	// src/hive/scala/main/HiveCoreDma.scala:76:22, :96:14, :119:62, :132:17, :168:21, :175:35, :191:20
      _GEN_7 =
        {{curAddr},
         {io_isA
            ? (_GEN_2 ? io_regFile_regs_3 : io_regFile_regs_3 + colAddr)
            : _GEN_2
                ? (_GEN_3 ? curAddr : io_regFile_regs_4 + colAddr)
                : curAddr + bNextKTileAddressOffset},
         {_GEN_0 ? (io_isA ? curAddr + rowStep : curAddr - rowStep) : curAddr},
         {io_isA ? io_regFile_regs_3 : io_regFile_regs_4 + _colAddr_T}};	// src/hive/scala/main/HiveCoreDma.scala:81:24, :82:24, :83:24, :84:40, :96:14, :119:62, :132:17, :138:20, :143:21, :156:{19,39,60}, :175:35, :182:23, :183:{21,32}, :185:{21,32}, :191:20, :192:{19,49}, :193:19, :196:21, :204:{19,39}, :214:49, :215:51, :219:{21,41}, :226:{21,32}, src/utils/Stream/Stream.scala:43:26
      curAddr <= _GEN_7[state];	// src/hive/scala/main/HiveCoreDma.scala:76:22, :81:24, :96:14, :119:62, :132:17, :138:20, :175:35, :191:20
      if (_GEN) begin	// src/hive/scala/main/HiveCoreDma.scala:96:14
        colAddr <= io_isA ? 32'h20 : io_calcConfig_bColTileAddressOffset + _colAddr_T;	// src/hive/scala/main/HiveCoreDma.scala:82:24, :138:20, :144:21, :156:60, :157:{21,60}
        rowStep <=
          io_isA ? io_calcConfig_aRowAddressOffset : io_calcConfig_bRowAddressOffset;	// src/hive/scala/main/HiveCoreDma.scala:83:24, :138:20, :145:21, :158:21
        lineTarget <= io_isA ? io_regFile_regs_0[15:0] : 16'h10;	// src/hive/scala/main/HiveCoreDma.scala:88:28, :138:20, :146:23, :159:23
        lineCounter <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:89:28
        ostCredit <= 6'h20;	// src/hive/scala/main/HiveCoreDma.scala:90:25, :97:15
      end
      else begin	// src/hive/scala/main/HiveCoreDma.scala:96:14
        if (_io_dmaExtRdIF_req_valid_T_1 | _GEN_5) begin	// src/hive/scala/main/HiveCoreDma.scala:82:24, :119:62, :132:17
        end
        else if (io_isA)	// src/hive/scala/main/HiveCoreDma.scala:54:14
          colAddr <= _GEN_2 ? 32'h20 : colAddr + 32'h20;	// src/hive/scala/main/HiveCoreDma.scala:82:24, :192:{19,49}, :194:19, :205:{19,30}
        else if (_GEN_4) begin	// src/hive/scala/main/HiveCoreDma.scala:82:24, :86:21, :192:49, :196:51, :214:49, :215:51
        end
        else	// src/hive/scala/main/HiveCoreDma.scala:82:24, :214:49, :215:51
          colAddr <= colAddr + io_calcConfig_bColTileAddressOffset;	// src/hive/scala/main/HiveCoreDma.scala:82:24, :220:32
        if (_GEN_0)	// src/utils/Stream/Stream.scala:43:26
          lineCounter <= _GEN_1 ? 16'h0 : lineCounter + 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:89:28, :176:{28,49}, :178:25, :180:{25,40}
        if (~(_GEN_0 & io_bufPopFire)) begin	// src/hive/scala/main/HiveCoreDma.scala:107:33, src/utils/Stream/Stream.scala:43:26
          if (_GEN_0)	// src/utils/Stream/Stream.scala:43:26
            ostCredit <= ostCredit - 6'h1;	// src/hive/scala/main/HiveCoreDma.scala:90:25, :109:30
          else if (io_bufPopFire)	// src/hive/scala/main/HiveCoreDma.scala:54:14
            ostCredit <= ostCredit + 6'h1;	// src/hive/scala/main/HiveCoreDma.scala:90:25, :109:30, :111:30
        end
      end
      if (~_GEN | io_isA) begin	// src/hive/scala/main/HiveCoreDma.scala:84:40, :96:{14,24}, :98:12, :100:33, :132:17, :135:15, :138:20
      end
      else	// src/hive/scala/main/HiveCoreDma.scala:84:40, :132:17, :138:20
        bNextKTileAddressOffset <=
          io_regFile_regs_7[5]
            ? {io_calcConfig_bRowAddressOffset[27:0] + 28'h2, 4'h0}
            : {io_calcConfig_bRowAddressOffset[26:0], 5'h0};	// src/hive/scala/main/HiveCoreDma.scala:54:14, :84:40, :164:{41,112,151}, src/hive/scala/main/HiveInterface.scala:145:26
      if (_GEN | _io_dmaExtRdIF_req_valid_T_1 | _GEN_5) begin	// src/hive/scala/main/HiveCoreDma.scala:86:21, :96:14, :119:62, :132:17
      end
      else if (io_isA) begin	// src/hive/scala/main/HiveCoreDma.scala:54:14
        kCnt <= _GEN_2 ? 16'h0 : kCnt + 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:85:21, :192:{19,49}, :195:16, :206:{16,24}
        if (_GEN_4) begin	// src/hive/scala/main/HiveCoreDma.scala:86:21, :192:49, :196:51
        end
        else	// src/hive/scala/main/HiveCoreDma.scala:86:21, :192:49, :196:51
          nCnt <= nCnt + 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:86:21, :199:26
      end
      else begin	// src/hive/scala/main/HiveCoreDma.scala:54:14
        if (_GEN_2) begin	// src/hive/scala/main/HiveCoreDma.scala:192:19
          if (~_GEN_3)	// src/hive/scala/main/HiveCoreDma.scala:196:21
            kCnt <= 16'h0;	// src/hive/scala/main/HiveCoreDma.scala:85:21
        end
        else	// src/hive/scala/main/HiveCoreDma.scala:192:19
          kCnt <= kCnt + 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:85:21, :225:26
        if (_GEN_4) begin	// src/hive/scala/main/HiveCoreDma.scala:86:21, :192:49, :196:51, :214:49, :215:51
        end
        else	// src/hive/scala/main/HiveCoreDma.scala:86:21, :214:49, :215:51
          nCnt <= nCnt + 16'h1;	// src/hive/scala/main/HiveCoreDma.scala:86:21, :221:26
      end
      errReg <=
        ~_GEN & (io_dmaExtRdIF_rsp_valid & io_dmaExtRdIF_rsp_payload_err | errReg);	// src/hive/scala/main/HiveCoreDma.scala:91:23, :96:{14,24}, :98:12, :100:33, :101:42, :102:16, :132:17, :135:15
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/hive/scala/main/HiveCoreDma.scala:50:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/hive/scala/main/HiveCoreDma.scala:50:7
      `FIRRTL_BEFORE_INITIAL	// src/hive/scala/main/HiveCoreDma.scala:50:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/hive/scala/main/HiveCoreDma.scala:50:7
      automatic logic [31:0] _RANDOM[0:6];	// src/hive/scala/main/HiveCoreDma.scala:50:7
      `ifdef INIT_RANDOM_PROLOG_	// src/hive/scala/main/HiveCoreDma.scala:50:7
        `INIT_RANDOM_PROLOG_	// src/hive/scala/main/HiveCoreDma.scala:50:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/hive/scala/main/HiveCoreDma.scala:50:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/hive/scala/main/HiveCoreDma.scala:50:7
        end	// src/hive/scala/main/HiveCoreDma.scala:50:7
        state = _RANDOM[3'h0][1:0];	// src/hive/scala/main/HiveCoreDma.scala:50:7, :76:22
        curAddr = {_RANDOM[3'h0][31:2], _RANDOM[3'h1][1:0]};	// src/hive/scala/main/HiveCoreDma.scala:50:7, :76:22, :81:24
        colAddr = {_RANDOM[3'h1][31:2], _RANDOM[3'h2][1:0]};	// src/hive/scala/main/HiveCoreDma.scala:50:7, :81:24, :82:24
        rowStep = {_RANDOM[3'h2][31:2], _RANDOM[3'h3][1:0]};	// src/hive/scala/main/HiveCoreDma.scala:50:7, :82:24, :83:24
        bNextKTileAddressOffset = {_RANDOM[3'h3][31:2], _RANDOM[3'h4][1:0]};	// src/hive/scala/main/HiveCoreDma.scala:50:7, :83:24, :84:40
        kCnt = _RANDOM[3'h4][17:2];	// src/hive/scala/main/HiveCoreDma.scala:50:7, :84:40, :85:21
        nCnt = {_RANDOM[3'h4][31:18], _RANDOM[3'h5][1:0]};	// src/hive/scala/main/HiveCoreDma.scala:50:7, :84:40, :86:21
        lineTarget = _RANDOM[3'h5][17:2];	// src/hive/scala/main/HiveCoreDma.scala:50:7, :86:21, :88:28
        lineCounter = {_RANDOM[3'h5][31:18], _RANDOM[3'h6][1:0]};	// src/hive/scala/main/HiveCoreDma.scala:50:7, :86:21, :89:28
        ostCredit = _RANDOM[3'h6][7:2];	// src/hive/scala/main/HiveCoreDma.scala:50:7, :89:28, :90:25
        errReg = _RANDOM[3'h6][8];	// src/hive/scala/main/HiveCoreDma.scala:50:7, :89:28, :91:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/hive/scala/main/HiveCoreDma.scala:50:7
      `FIRRTL_AFTER_INITIAL	// src/hive/scala/main/HiveCoreDma.scala:50:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_err = errReg;	// src/hive/scala/main/HiveCoreDma.scala:50:7, :91:23
  assign io_dmaExtRdIF_req_valid = io_dmaExtRdIF_req_valid_0;	// src/hive/scala/main/HiveCoreDma.scala:50:7, :119:54
  assign io_dmaExtRdIF_req_payload_addr = curAddr;	// src/hive/scala/main/HiveCoreDma.scala:50:7, :81:24
  assign io_bufPush_valid = io_dmaExtRdIF_rsp_valid;	// src/hive/scala/main/HiveCoreDma.scala:50:7
  assign io_bufPush_payload = io_dmaExtRdIF_rsp_payload_data;	// src/hive/scala/main/HiveCoreDma.scala:50:7
endmodule

