// Generated by CIRCT firtool-1.149.0
module Hive_HiveMulInt(	// src/hive/scala/main/HiveWorkUnit.scala:113:7
  input  [15:0] io_a,	// src/hive/scala/main/HiveWorkUnit.scala:114:14
                io_b,	// src/hive/scala/main/HiveWorkUnit.scala:114:14
  output [31:0] io_prod	// src/hive/scala/main/HiveWorkUnit.scala:114:14
);

  assign io_prod = {{16{io_a[15]}}, io_a} * {{16{io_b[15]}}, io_b};	// src/hive/scala/main/HiveWorkUnit.scala:113:7, :119:27
endmodule

