// Generated by CIRCT firtool-1.149.0
module Hive_HiveMacFp(	// src/hive/scala/main/HiveWorkUnit.scala:177:7
  input  [31:0] io_a,	// src/hive/scala/main/HiveWorkUnit.scala:180:14
                io_b,	// src/hive/scala/main/HiveWorkUnit.scala:180:14
  input  [39:0] io_c,	// src/hive/scala/main/HiveWorkUnit.scala:180:14
  input  [2:0]  io_rnd,	// src/hive/scala/main/HiveWorkUnit.scala:180:14
  output [39:0] io_sum	// src/hive/scala/main/HiveWorkUnit.scala:180:14
);

  wire        prod32_sOut = io_a[31] ^ io_b[31];	// src/hive/scala/main/Fp32.scala:9:30, :41:19
  wire [47:0] prod32_mProd = {25'h1, io_a[22:0]} * {25'h1, io_b[22:0]};	// src/hive/scala/main/Fp32.scala:11:30, :45:22
  wire [8:0]  _prod32_eAdj_T_2 =
    {1'h0, io_a[30:23]} + {1'h0, io_b[30:23]} + {8'h0, prod32_mProd[47]};	// src/hive/scala/main/Fp32.scala:10:29, :45:22, :49:19, :50:{21,32}
  wire [22:0] prod32_mNorm = prod32_mProd[47] ? prod32_mProd[46:24] : prod32_mProd[45:23];	// src/hive/scala/main/Fp32.scala:45:22, :50:32, :54:{20,37,52}
  wire        prod32_guardBit = prod32_mProd[47] ? prod32_mProd[23] : prod32_mProd[22];	// src/hive/scala/main/Fp32.scala:45:22, :50:32, :56:{23,40,51}
  wire [31:0] prod32 =
    io_a[30:23] == 8'h0 & io_a[22:0] == 23'h0 | io_b[30:23] == 8'h0 & io_b[22:0] == 23'h0
      ? 32'h0
      : {prod32_sOut,
         _prod32_eAdj_T_2 > 9'h7E ? _prod32_eAdj_T_2[7:0] - 8'h7F : 8'h0,
         io_rnd != 3'h1
         & (io_rnd == 3'h2
              ? prod32_sOut & prod32_guardBit
              : (io_rnd != 3'h3 | ~prod32_sOut) & prod32_guardBit)
           ? prod32_mNorm + 23'h1
           : prod32_mNorm};	// src/hive/scala/main/Fp32.scala:10:29, :11:30, :14:50, :41:19, :49:19, :50:21, :51:{19,25,41}, :54:20, :56:23, :60:{21,30,37}, :61:{21,30,37}, :62:{8,15}, :187:{22,27}, :188:{10,15,42}, :189:{12,17,39}, :191:{8,25}
  wire [30:0] pMant31 = {1'h1, prod32[22:0], 7'h0};	// src/hive/scala/main/Fp32.scala:11:30, :62:8, src/hive/scala/main/HiveWorkUnit.scala:203:20
  wire [8:0]  _expDiffRaw_T_2 = {1'h0, prod32[30:23]} - {1'h0, io_c[38:31]};	// src/hive/scala/main/Fp32.scala:10:29, :62:8, src/hive/scala/main/HiveWorkUnit.scala:194:19, :207:30
  wire        pGtC = $signed(_expDiffRaw_T_2) > -9'sh1;	// src/hive/scala/main/HiveWorkUnit.scala:207:30, :208:25
  wire [8:0]  _shiftAmt_T_8 = 9'h0 - _expDiffRaw_T_2;	// src/hive/scala/main/HiveWorkUnit.scala:207:30, :208:25, :211:10
  wire [7:0]  baseExp = pGtC ? prod32[30:23] : io_c[38:31];	// src/hive/scala/main/Fp32.scala:10:29, :62:8, src/hive/scala/main/HiveWorkUnit.scala:194:19, :208:25, :212:20
  wire [30:0] _GEN =
    {26'h0,
     pGtC
       ? ($signed(_expDiffRaw_T_2) > 9'sh1F ? 5'h1F : _expDiffRaw_T_2[4:0])
       : $signed(_shiftAmt_T_8) > 9'sh1F ? 5'h1F : _shiftAmt_T_8[4:0]};	// src/hive/scala/main/HiveWorkUnit.scala:207:30, :208:25, :209:21, :210:{8,20,56}, :211:{8,10,23,43,62}, :215:46
  wire [30:0] pAligned = pGtC ? pMant31 : pMant31 >> _GEN;	// src/hive/scala/main/HiveWorkUnit.scala:203:20, :208:25, :215:{21,46}
  wire [30:0] cAligned = pGtC ? io_c[30:0] >> _GEN : io_c[30:0];	// src/hive/scala/main/HiveWorkUnit.scala:195:19, :208:25, :215:46, :216:{21,35}
  wire        effectSub = prod32[31] ^ io_c[39];	// src/hive/scala/main/Fp32.scala:9:30, :62:8, src/hive/scala/main/HiveWorkUnit.scala:193:19, :219:25
  wire        pIsLarger = pGtC | pAligned >= cAligned;	// src/hive/scala/main/HiveWorkUnit.scala:208:25, :215:21, :216:21, :221:{24,37}
  wire [30:0] largeM = pIsLarger ? pAligned : cAligned;	// src/hive/scala/main/HiveWorkUnit.scala:215:21, :216:21, :221:24, :222:19
  wire [30:0] smallM = pIsLarger ? cAligned : pAligned;	// src/hive/scala/main/HiveWorkUnit.scala:215:21, :216:21, :221:24, :223:19
  wire [31:0] addRes = {1'h0, largeM} + {1'h0, smallM};	// src/hive/scala/main/HiveWorkUnit.scala:222:19, :223:19, :226:23
  wire [30:0] _subRes_T = largeM - smallM;	// src/hive/scala/main/HiveWorkUnit.scala:222:19, :223:19, :227:23
  assign io_sum =
    prod32[30:23] == 8'h0 & prod32[22:0] == 23'h0
      ? io_c
      : io_c[38:31] == 8'h0 & io_c[30:0] == 31'h0
          ? {prod32[31:23], 1'h1, prod32[22:0], 7'h0}
          : effectSub & _subRes_T == 31'h0
              ? 40'h0
              : {pIsLarger ? prod32[31] : io_c[39],
                 effectSub | ~(addRes[31]) ? baseExp : baseExp + 8'h1,
                 effectSub ? _subRes_T : addRes[31] ? addRes[31:1] : addRes[30:0]};	// src/hive/scala/main/Fp32.scala:9:30, :10:29, :11:30, :50:26, :62:8, :191:25, src/hive/scala/main/HiveWorkUnit.scala:177:7, :193:19, :194:19, :195:19, :196:{21,30,40}, :203:20, :204:{21,30,40}, :212:20, :219:25, :221:24, :224:19, :226:23, :227:23, :233:19, :235:13, :236:13, :238:{16,22}, :240:{15,24}, :241:26, :244:{15,24}, :250:19, :251:21, :252:{8,19}, :253:{10,21,32}
endmodule

